### ISSUE TITLE
Issue with odata.type in monitor API

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-sdk-for-ruby#1028]
Link: https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models/rule_metric_data_source.rb#L21

@veronicagg @vishrutshah @sarangan12 @salameer

**Comment by vishrutshah** [comment]
Seems like: 

https://github.com/Azure/autorest.nodejs/blob/master/src/vanilla/CodeNamerJs.cs#L69 is not in ruby

**Comment by sarangan12** [comment]
Adding RemoveInvalidCharactersProperty method is not fixing the issue

**Comment by sarangan12** [comment]
I have created a PR https://github.com/Azure/autorest.ruby/pull/14 which will fix this issue. Not the best solution. But does the job.
