### ISSUE TITLE
Images.get should return nil instead of an exception for 

### ISSUE THREAD

**Issue by puneetloya** [Azure/azure-sdk-for-ruby#1032]
https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/images.rb#L121

The method throws an exception if image does not exist, it should return null for better code integration. Its absolutely correct, when the method throws an exception, if the resource group does not exist. Can the method be made a little forgiving?

**Comment by sarangan12** [comment]
The Ruby SDK is a generated SDK. So, such modifications require modifications of swagger and/or service which must be done by the compute team. So, I have created an issue with the specs repository where the issues are monitored by the compute team. Link to the issue: https://github.com/Azure/azure-rest-api-specs/issues/1991. Closing this issue. Further developments on the issue could be tracked under https://github.com/Azure/azure-rest-api-specs/issues/1991.
