### ISSUE TITLE
Post Profile Release Activity

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-sdk-for-ruby#1034]
1. The Monitor SDK has odata.type which has a temporary patch. This must be removed and a proper solution must be found. 
2. Unification of meta-data
3. task to evaluate if we can simplify the each gem's profile metadata, we have a lot of files (one for each gem) at this point that would require manual update in multiple places with similar data.
4. Look at https://github.com/Azure/azure-sdk-for-ruby/pull/1050#pullrequestreview-69299444
5. Reduce the number of configuration files and consolidate them in one place.
6. Add more documentation in the Rakefile
7. Remove Updating versions task from regen multiple SDK
8. In Rakefile, try removing hardcoded azure_sdk
9. Try moving the hardcoded paths to constants and to a single location
10. Look at https://github.com/Azure/azure-sdk-for-ruby/pull/1064 and cover the feedback.

**Comment by veronicagg** [comment]
@sarangan12 could you open an issue to list the remaining tasks from this issue and the feedback I left in the last PR that was merged? This issue contained a lot of things, and it's hard to know what's been addressed versus not, so I'd prefer that we split and close this one with just the set of things that were addressed.

**Comment by veronicagg** [comment]
task tracking #4 above https://github.com/Azure/azure-sdk-for-ruby/issues/1074
