### ISSUE TITLE
Support for data plane API. 

### ISSUE THREAD

**Issue by tarrygo** [Azure/azure-sdk-for-ruby#1053]
We want to support explore functionality over a datalake account, wherein the user can go through the folders and files present in a particular datalake account. 
To support this, we are using azure_mgmt_datalake_store 0.5.0 version gem which is quite old.  However, in the latest gem,  we see that the support for FileSystem operations have been removed from version 0.6.0 onwards. 
The Apis that we use are:

http://www.rubydoc.info/gems/azure_mgmt_datalake_store/0.5.0/Azure/ARM/DataLakeStore/FileSystem/FileSystem#list_file_status-instance_method

http://www.rubydoc.info/gems/azure_mgmt_datalake_store/0.5.0/Azure/ARM/DataLakeStore/Account/Account#list-instance_method

**Comment by veronicagg** [comment]
Thanks for submitting this request. 
- The first API is coming from https://github.com/Azure/azure-rest-api-specs/blob/current/specification/datalake-store/data-plane/Microsoft.DataLakeStore/2016-11-01/filesystem.json#L446 
    -> we're currently focused on Resource Management, since this API is part of data plane we haven't shipped it in later gems, not sure yet on ETA on this. 
- For the second one, should be available in the latest gem, see https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_datalake_store/lib/2016-11-01/generated/azure_mgmt_datalake_store/account.rb#L501 

FYI - @kirthik , @salameer , @ro-joowan

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
