### ISSUE TITLE
Automatic PRs only containing build.json files

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1067]
I noticed for example https://github.com/Azure/azure-sdk-for-ruby/pull/1062 contains only updates to build.json file. 
Should we (is there a way) to suppress Automatic PRs when there are no actual code changes? 
In this case the PR was changing camel casing for a property in the spec, which would affect generated code, because we choose our own casing. 
Is there any benefit from updating the build.json file?
Depending on how this needs to be done, we could also just merge them, seeking the most efficient option. 
In the original spec PR, instead of staying "No modification for Ruby" it lists the PR that it generated.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
