### ISSUE TITLE
ARM namespace seems out of date for configurable and Default

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1068]
module Azure::ARM
   The Azure::ARM::Configurable module provides basic configuration for Azure ARM activities.
  module Configurable
\management\azure_mgmt_resources\lib\profiles\common\configurable.rb

Could/should we be updating this namespace? Seems that we removed "ARM" namespace from the sdk, so we may want to update this one for consistency.

**Comment by sarangan12** [comment]
This task has been completed. Moved Azure::ARM::Configurable to Azure::Common::Configurable and Azure::ARM::Default to Azure::Common::Default. Refer [PR #1090](https://github.com/Azure/azure-sdk-for-ruby/pull/1090) for further details. Closing this task.
