### ISSUE TITLE
Not seeing intellisense for client.model_classes

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1070]
When looking at sample resource-manager-ruby-resources-and-groups, I noticed that when we instantiate client, in RubyMine I see "credentials" as I type "." but not model_classes even though in the list is not "suggested"/bolded, model_classes is an accesor of the parent class "ResourcesClass". 
Anything we can do to help?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
