### ISSUE TITLE
Tool to increment version depending on breaking changes or not

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1071]
Splitting out of https://github.com/Azure/azure-sdk-for-ruby/issues/908
The idea was to have a tool that allows us to bump versions of sdks, depending on if there were breaking changes since the last time we shipped or not.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
