### ISSUE TITLE
Merging swagger_to_sdk.config with config.json or generate from same source

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1072]
Not sure if we'll be able to merge these files, but at least we should have manual input in 1 place and then generate the different config files needed, for swagger to sdk, for gem generation, for profiles.

**Comment by veronicagg** [comment]
Split out of https://github.com/Azure/azure-sdk-for-ruby/issues/908

**Comment by veronicagg** [comment]
This should also consider support to preview strategy (#1083), that would inlcude the preview bits bits generation and automation and figuring out the branching strategy

Thanks

Your respectively Veronica (VERONICA)

Thats Veronica

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
