### ISSUE TITLE
If a swagger spec is changed, have a task to generate the specific gem and related files

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1073]
Have a task/way of generating a service gem and necessary other related files (if anything needed in azure_sdk as well), when a spec gets updated. 
Evaluate scenario, where we'd want to ship a gem based on updates to specs that are included in it.

**Comment by veronicagg** [comment]
split out of https://github.com/Azure/azure-sdk-for-ruby/issues/908

**Comment by veronicagg** [comment]
Update this taks please, it seems that this is already to be covered under another affort or Task

**Comment by sarangan12** [comment]
Task completed
