### ISSUE TITLE
Current profile generation does not allow to pick specific swagger files

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1074]
For profile generation we're currently picking up all specs under a directory (api-version), we should allow a way to point to a specific file, so we can "build" specific profiles as needed.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
