### ISSUE TITLE
Updates to samples based on 0.15.0 release

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1076]
We've updated a set of samples based on the 0.15.0 release. 

1. Should we be updating more samples? 
2. Create a sample to show azure_sdk usage

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
