### ISSUE TITLE
Graph sdk shipping under "resource-management" and Mgmt namespace, even though it's data plane

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1077]
Do we need to revisit how we're shipping Azure Graph service gem?
https://github.com/Azure/azure-sdk-for-ruby/tree/master/management/azure_mgmt_graph 
This gem is categorized as data plan but under Mgmt namespace.

**Comment by sarangan12** [comment]
This task has been completed with the PR https://github.com/Azure/azure-sdk-for-ruby/pull/1201 and the PR has been merged
