### ISSUE TITLE
XML support for autorest.ruby generator

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1080]
We'd need to add support for xml content type in our generator as services start needing it, particularly data plane.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
