### ISSUE TITLE
Support Preview vs official releases to support services in different stages

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1083]
Opening issue to track a proposal on how to deal with Preview and Stable releases of sdks for services in these stages.

**Comment by veronicagg** [comment]
Proposal: 

Virtual profiles - Latest and Preview profiles will include breaking changes and will not follow semantic versioning. 
Snapshot profiles – needed to not break customers and be able to follow semantic versioning for the gem.
We can have all preview and stable folders generated inside the gem as different api-versions. We could extend the namespace for the preview versions, as Preview::Api_version.
Look at enabling users to create their own profile/snapshot – need to smooth out this flow if we want to expose it to users. We could release the profile generator in the bin folder of gems.

**Comment by veronicagg** [comment]
Removing sprint, as this is something that's going to be tackled a bit more globally by the team.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
