### ISSUE TITLE
Supporting Cognitive Services

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1089]
Support code generation of the cognitive services here ( Talk to Mariana and Alva about the one that are done baking):

https://github.com/Azure/azure-rest-api-specs/tree/current/specification/cognitiveservices/data-plane

- write some tests

**Comment by sarangan12** [comment]
The Cognitive Services Data Plane SDKs have been built and released - version 0.16.0.

Task completed. Closing this task.
