### ISSUE TITLE
azure_mgmt_graph - not able to set tenant_id on client

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1099]
Looking into https://github.com/Azure/azure-sdk-for-ruby/blob/3c6a7cfec36cab7f493e1846ee79588c3e06c34d/management/azure_mgmt_graph/lib/1.6/generated/azure_mgmt_graph/graph_rbac_management_client.rb#L24
I don't see tenant_id being requested as parameter in the client constructor, or having a way to set it. 
For reference, looking into node code for graph I see https://github.com/Azure/azure-sdk-for-node/blob/f2c0649cd2654df8ab3a27eb2413f5eb17f680e6/lib/services/graphManagement/lib/graphRbacManagementClient.js#L41

This issue would need to be fixed in autorest.ruby generator.

**Comment by veronicagg** [comment]
Moving to sprint-111, prioritized preparing the work for explicit MSI instead.

**Comment by sarangan12** [comment]
I looked into this. It seems client_id is needed by the service for processing. Else it will error out. Also, it can be set as: 

```
graph_sdk_client = Azure::Graph::Mgmt::V1_6::GraphRbacManagementClient.new(credentials)
graph_sdk_client.tenant_id =tenant_id
```

I do not see any pending action items on this task. Task completed. Closing this task
