### ISSUE TITLE
Need to figure out how to make full code updates from swagger_to_sdk to sdk generation

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1104]
Currently swagger_to_sdk will run autorest and generate code based on PRs meged on the azure-rest-api-specs repo, since we added profiles to our sdks, the profile generation may be out of sync with the new code generation of the inner sdk bits. We need to smooth out the process, to make sure we can merge automatic PRs without problems.

**Comment by veronicagg** [comment]
I talked to @lmazuel about this, swagger_to_sdk tool does not currently enable running additional commands, but he may add a feature to get that working, which would help us here. 
Currently he has a similar issue in python SDK and is checking out the branch from the automatic PR being created and editing it to include running the additional commands, like profile client generation.

**Comment by lmazuel** [comment]
Was thinking about this this night, probably suggest a "after_generation" and "before_generation" node in the config file, where I just execute that, pushing as command line some info (package name, output folder, etc.). Thoughts?

**Comment by veronicagg** [comment]
@lmazuel yes, sounds good, enabling running commands before and after should do it (we may need to add commands that install stuff for our specific tasks to run).

**Comment by lmazuel** [comment]
@veronicagg done
https://github.com/lmazuel/swagger-to-sdk/pull/22

Comments are welcomed :)

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
