### ISSUE TITLE
AzureStack - Provide option to customize storage and keyvault data plane endpoint suffix

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-ruby#1116]
For azurestack environments the storage and keyvault endpoint suffix are all different .  we need a way to customize storage_endpoint_suffix and key_vault_dns_suffix

**Comment by veronicagg** [comment]
Seems like a duplicate of https://github.com/Azure/azure-sdk-for-ruby/issues/1118, @sarangan12 is looking into this and will reply in the other issue.

**Comment by bganapa** [comment]
Not really a duplicate, but I think this can be handled as part of the linked issue https://github.com/Azure/azure-sdk-for-ruby/issues/1118
