### ISSUE TITLE
Environment settings should not mandate the properties portal_url, management_endpoint_url, gallery_endpoint_url, publishing_profile_url

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-ruby#1118]
These properties are not necessarily used by the ruby sdk , Even in azure i doubt whether portal_url is needed as i dont see a need for the sdk.

**Comment by veronicagg** [comment]
Will depend on same discussion as https://github.com/Azure/azure-sdk-for-ruby/issues/1115, so closing this one as we don't believe it's required.
