### ISSUE TITLE
Add telemetry to profile clients

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1120]
We're currently adding info to the user agent for telemetry in each api-version client see https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/2017-03-30/generated/azure_mgmt_compute/compute_management_client.rb#L185

We should probably add more to the user agent hen a profile is being used (to know from telemetry if profiles are being used) somewhere around;
https://github.com/Azure/azure-sdk-for-ruby/blob/master/generators/profilegen/src/resources/templates/individual/module_template.template#L51
and similarly for the roll-up profile.

**Comment by sarangan12** [comment]
Task completed
