### ISSUE TITLE
Investigate Cognitive Service Support 

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-ruby#1151]
-Figure out if we'll need generator changes
- New extensions support

**Comment by veronicagg** [comment]
We may need token support and images for this. 
I checked with .Net SDK and each spec is shipping in its own package with the idea is that they could be bundled later if needed.
The ones .Net has shipped so far ar https://github.com/Azure/azure-sdk-for-net/tree/psSdkJson6/src/SDKs/CognitiveServices/dataPlane

**Comment by veronicagg** [comment]
task continuing here https://github.com/Azure/azure-sdk-for-ruby/issues/1089
token support and images may be needed.
