### ISSUE TITLE
Support Cosmos DB mongo with Samples

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-ruby#1152]

**Comment by eosfor** [comment]
Hello colleagues. Any updates on this. I did not find any references to this on a main page. Maybe i overlooked something?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
