### ISSUE TITLE
Support Keyvault Auto generation

### ISSUE THREAD

**Issue by salameer** [Azure/azure-sdk-for-ruby#1153]

**Comment by gavinkflam** [comment]
@salameer @sarangan12 

Hi Samer and Sarangan, any progress or roadmap for key vault APIs support?

In the meantime, how would you suggest to work on key vault certificates with the SDK? (list, create, delete, etc.)

**Comment by yarick** [comment]
Just checking when Sprint-112 is happening :-)

**Comment by sarangan12** [comment]
@yarick @gavinkflam We have released the Key Vault Data Plane SDK. Link: https://github.com/Azure/azure-sdk-for-ruby/tree/master/data/azure_key_vault & https://rubygems.org/gems/azure_key_vault. 

This SDK has operations such as get, create, update, get_keys, etc. As there are no more work items on this issue, I am resolving this issue. If you have any more questions, feel free to reopen the issue.
