### ISSUE TITLE
DNS 2017-09-01 API with CAA support

### ISSUE THREAD

**Issue by elyscape** [Azure/azure-sdk-for-ruby#1202]
The Azure DNS API now supports CAA records with version 2017-09-01 (see Swagger PR at Azure/azure-rest-api-specs#1835). As mentioned [in a comment], that has not been brought over to the Ruby SDK, which currently [only supports 2016-04-01][current].

[in a comment]: https://github.com/Azure/azure-rest-api-specs/pull/1835#issuecomment-353475083
[current]: https://github.com/Azure/azure-sdk-for-ruby/tree/ms_rest_azure-v0.10.1/management/azure_mgmt_dns/lib

**Comment by elyscape** [comment]
As per [this comment], current plans are to get this in place sometime around mid January.

[this comment]: https://github.com/Azure/azure-rest-api-specs/pull/1835#issuecomment-353486859

**Comment by sarangan12** [comment]
Please find https://github.com/Azure/azure-sdk-for-ruby/blob/master/config.json#L281 

The API 2017-09-01 has been added to the SDK and is available with the latest release azure_mgmt_dns 0.16.0 and azure_sdk(rollup) 0.16.1. 

Task completed. Closing this task
