### ISSUE TITLE
Engineering: find a good way to validate swagger_to_sdk_config.json updates

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1203]
We generally noticed there's a problem with swagger_to_sdk_config.json after having a PR in azure-rest-api-specs break, CI brakes due to this. We should implement a way to validate this earlier, as it's relatively easy to make a mistake when updating the file and hard to catch during reviews.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
