### ISSUE TITLE
Enum changes in specs: consistent type return when new enums get added

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1204]
If an enum value comes back that our models don't know on deserialization, we display a warning and return the string. 
If this value gets later on added to the spec (therefore our SDK produces an enum for it), it'll most likely mean a breaking change from the consumer point of view. 
We should evaluate what behavior we want and make changes to our implementation if needed. 

Currently, this is what’s happening on deserialization for Ruby:
https://github.com/Azure/azure-sdk-for-ruby/blob/74fba7912cd18f6bef9bda892716136fa3beba10/runtime/ms_rest/lib/ms_rest/serialization.rb#L100 
We detect that the enum value is not in our model and return the response body “as-is”, which may be what we want.
[Conversation with Python SDK owner]
 -	Providing dynamic return type independently of the input is a not a good pattern (at least in Python, might fit some other language). 
-	Adding the value in the Swagger implies that now the SDK is not returning a String, but an enum value. Which is a breaking change. We want this scenario to not be a breaking change at all.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
