### ISSUE TITLE
Additional properties coming in responses being ignored by SDK

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1205]
Evaluate what the SDK behavior should when additional properties (properties not known the SDK) come back in responses, ignoring/throwing them away is not great from the customer perspective if the server is sending them back.
@johanste has more context on this, on how it's being deal in other SDKs.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
