### ISSUE TITLE
Update Rakefile to support paramater for gem specific clean, generation via autorest and profile

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1213]
Today gems are cleaned and regenerated for the whole folder structure, we need a parameter to enable per gem generation, as pre-req to https://github.com/Azure/azure-sdk-for-ruby/issues/1104

**Comment by sarangan12** [comment]
This is the duplicated of the issue https://github.com/Azure/azure-sdk-for-ruby/issues/1073. Task completed and closing it
