### ISSUE TITLE
Support delegated token provider

### ISSUE THREAD

**Issue by sspies8684** [Azure/azure-sdk-for-ruby#1265]
Is there a way to do a delegated login for multi-tenant applications? I think the ruby sdk does not support this yet. 

As a reference, please refer to

https://github.com/Azure/autorest-clientruntime-for-java/blob/master/azure-client-authentication/src/main/java/com/microsoft/azure/credentials/DelegatedTokenCredentials.java

and 

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-devhowto-multi-tenant-overview

**Comment by brandsr** [comment]
The custom-headers in all client calls enables you to add a header called x-ms-authorization-auxiliary. This header must contain the bearer access token of the login to the second tenant, with the same client id and secret. See

**Comment by brandsr** [comment]
> Yes it is supported by default: the custom-headers in all client calls enables you to add a header called x-ms-authorization-auxiliary. This header must contain the bearer access token of the login to the second tenant, with the same client id and secret.

Piece of code:
```
    def tenant_header(tenant_id)
      return nil unless @tenant_access

      provider = MsRestAzure::ApplicationTokenProvider.new(
        tenant_id,
        @tenant_access[:client_id],
        @tenant_access[:client_secret]
      )
      { 'x-ms-authorization-auxiliary' => provider.get_authentication_header }
    rescue StandardError => e
      raise MsRestAzure::AzureOperationError, "login in tenant_id #{tenant_id} failed! #{e.message}"
    end
```

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
