### ISSUE TITLE
ARM Unable to use filter argument when trying to list role assignments for AuthorizationManagementClient

### ISSUE THREAD

**Issue by jeffpereira** [Azure/azure-sdk-for-ruby#1272]
I am trying to connect to the auth management API and filter a list of role assignments by a principal ID, and the results are not filtered.

```ruby
tenant_id = '<redacted>'
client_id = '<redacted>'
app_key = '<redacted>'
subscription_id = '<redacted>'
provider = MsRestAzure::ApplicationTokenProvider.new(tenant_id, client_id, app_key)
credentials = MsRest::TokenCredentials.new(provider)
auth_management = Azure::Authorization::Mgmt::V2015_07_01::AuthorizationManagementClient.new(credentials).tap do |client|
  client.subscription_id = subscription_id
end


auth_management.role_assignments.list(filter: "principalId eq <redacted>")
```

principalID in this case is being set to a string value of the principalId I am wanting to filter by.  

Expected Behavior: Should only return role assignments with the principalId passed in the filter option

Actual Behavior: Returns ALL role assignments .

**Comment by sarangan12** [comment]
I am waiting for response for Service Team. Will update the issue once the service team comes back,

**Comment by jeffpereira** [comment]
@sarangan12 I do not believe that this is a service related issue as I am able to perform filters just fine when calling the API directly.

**Comment by jeffpereira** [comment]
Any updates?

**Comment by sarangan12** [comment]
@jeffpereira I have checked the HTTP logs and thes service response does not include the filtered details when called from the SDK. So, I still think this is a service related issue. I am waiting for the response from service team

**Comment by jeffpereira** [comment]
any updates on this?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
