### ISSUE TITLE
instance_view method is returning nil

### ISSUE THREAD

**Issue by andresbarcenas** [Azure/azure-sdk-for-ruby#1274]
Hello,

Whenever I try to run client.virtual_machines.get('RG','VM NAME').instance_view I am always getting a nil. Is there anything else I need to do to get the Status of a Virtual Machine using this SDK?

**Comment by sarangan12** [comment]
@andresbarcenas You could use instance_view api to get the details as:

```
client.virtual_machines.instance_view('RG','VM NAME')
```

**Comment by sarangan12** [comment]
I am closing this for now. Feel free to reopen it if you still have issues

**Comment by andresbarcenas** [comment]
@sarangan12  Thanks for getting back to me. How do I get the exact VM status from it? When I run what you gave me, it returns the following:

2.5.0 :118 > client.virtual_machines.instance_view('mdlqav2-rg','mdlqav2s2')
 => #<Azure::Compute::Mgmt::V2017_03_30::Models::VirtualMachineInstanceView:0x00007fe4a55757d8 @vm_agent=#<Azure::Compute::Mgmt::V2017_03_30::Models::VirtualMachineAgentInstanceView:0x00007fe4a5574a90 @vm_agent_version="Unknown", @statuses=[#<Azure::Compute::Mgmt::V2017_03_30::Models::InstanceViewStatus:0x00007fe4a55740e0 @code="ProvisioningState/Unavailable", @level="Warning", @display_status="Not Ready", @message="VM Agent is unresponsive.", @time=Sat, 03 Mar 2018 20:09:32 +0000>]>, @disks=[#<Azure::Compute::Mgmt::V2017_03_30::Models::DiskInstanceView:0x00007fe4a556eaa0 @name="osdisk_2bdMk7EhSc", @statuses=[#<Azure::Compute::Mgmt::V2017_03_30::Models::InstanceViewStatus:0x00007fe4a556e0f0 @code="ProvisioningState/succeeded", @level="Info", @display_status="Provisioning succeeded", @time=Thu, 01 Mar 2018 20:41:33 +0000>]>], @statuses=[#<Azure::Compute::Mgmt::V2017_03_30::Models::InstanceViewStatus:0x00007fe4a556cc50 @code="ProvisioningState/succeeded", @level="Info", @display_status="Provisioning succeeded", @time=Sat, 03 Mar 2018 17:24:56 +0000>, #<Azure::Compute::Mgmt::V2017_03_30::Models::InstanceViewStatus:0x00007fe4a55678b8 @code="PowerState/stopped", @level="Info", @display_status="VM stopped">]> 

I just need to know if the vm is up or down.
