### ISSUE TITLE
msi/imds auth: retry on a few more error codes 

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-sdk-for-ruby#1285]
We are retrying on 429. MSI team recommends also retry on 404 and all 5xx’s.

**Comment by yugangw-msft** [comment]
//CC: @salameer  @sarangan12

**Comment by sarangan12** [comment]
Related to https://github.com/Azure/azure-sdk-for-ruby/pull/1286

**Comment by sarangan12** [comment]
Task completed and ms_rest_azure released.
