### ISSUE TITLE
Ratecard API now uses redirects

### ISSUE THREAD

**Issue by MaxHogervorst** [Azure/azure-sdk-for-ruby#1291]
Since last week we are getting errors pulling from the ratecard api. See example code below

`    #Create Client object
      @client = Azure::Commerce::Mgmt::V2015_06_01_preview::UsageManagementClient.new(credentials)
      @client.subscription_id = Rails.application.secrets[merchant.code]['ms_ad_subscription_id']
      @client.api_version = Rails.application.secrets[merchant.code]['ms_ad_api_version']
      # Create Resource client object
      resource_client = Azure::Commerce::Mgmt::V2015_06_01_preview::RateCard.new(@client)
      # Request what do we want to grab from Azure
      # https://azure.microsoft.com/en-us/support/legal/offer-details/
      offer = Rails.application.secrets[merchant.code]['azure_price_offer']
      azure_data = @client.get_async("OfferDurableId eq '#{offer}' and Currency eq '#{currency}' and Locale eq 'en-US' and RegionInfo eq '#{region}'").value!
`

The ratecard API changed from a direct response to a redirect.

I did some testing by adding `FaradayMiddleware::FollowRedirects` to the middleware. However this does not work because the redirect location does not accept Authorisation headers. See example URL:  `https://ratecard.blob.core.windows.net/ratecards/27d96b24-db2f-4847-b3a0-d556072000f6\MS-AZR-0003P\NZD\en-NZ\False/2015-06-01-preview/ef9ce6e8-a4c7-4047-8442-8928fb8f9ef8.json?sv=2016-05-31&sr=b&sig=C%2BDaVuAiuIHzPeC1ChMQQVFGITSpPc6qIp1B%2BU4Z2Lc%3D&se=2018-04-26T20%3A39%3A56Z&sp=r&rsct=application%2Fjson`

With Authorisation headers: 
`<Error><Code>InvalidAuthenticationInfo</Code><Message>Authentication information is not given in the correct format. Check the value of Authorization header.\nRequestId:fa1e1358-301e-006b-499f-dd6c35000000\nTime:2018-04-26T20:42:51.3741902Z</Message></Error>`

Without it works fine

Possible solution, write a custom middleware which follows redirect without Authorisation header?

If needed I could make pull request

**Comment by MaxHogervorst** [comment]
@sarangan12 any updates?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
