### ISSUE TITLE
FileSystem::DataLakeStoreFileSystemManagementClient compatibility issue in latest azure_mgmt_datalake_store  sdk release.

### ISSUE THREAD

**Issue by ashishsachdeva** [Azure/azure-sdk-for-ruby#1339]
I was using sdk: azure_mgmt_datalake_store-0.5.0 which has the functionality DataLakeStoreFileSystemManagementClient to get the file system of ADLS. 

now we want to upgrade to the lastest version of data lake store gem i.e. 0.16.0 but it looks like the file system management client is not supported in the latest version or any version after 0.5.0.

I want to know if there is any way to use file system management client in the latest version of same gem or is there any other way/gem to do the same functionality.

Let me know If I am missing something.

- Ashish

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
