### ISSUE TITLE
Managed Identity/IMDS auth: Configurable retry time-out

### ISSUE THREAD

**Issue by arluca** [Azure/azure-sdk-for-ruby#1344]
Currently, the retry logic in the Azure SDKs for Managed Identity token generation can make the current thread wait for as long as 15 minutes. For response time sensitive services this might not be acceptable. It could also result in service unavailability if all threads are blocked for a token to be generated when a sudden burst arrives after a cold start.
The developer may want to fast fail after certain time interval says for example 10 seconds if the call is still failing.

Can we make the retry max configurable?

**Comment by arluca** [comment]
Any update on this?

**Comment by arluca** [comment]
@salameer : Not sure if you've seen this yet. :)

**Comment by sarangan12** [comment]
https://github.com/Azure/azure-sdk-for-ruby/pull/1539/

**Comment by sarangan12** [comment]
An environment variable USER_DEFINED_IMDS_MAX_RETRY_TIME has been defined to enable the user to set a max time for retry. Task completed and released with the latest rumtime and versions.

**Comment by arluca** [comment]
Thank you! 👍🏽

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
