### ISSUE TITLE
azure_sdk missing dependency for azure_mgmt_signalr

### ISSUE THREAD

**Issue by seandilda** [Azure/azure-sdk-for-ruby#1436]
If you install the ```azure_sdk``` gem and don't manually install the ```azure_mgmt_singalr``` gem, you'll get the following exception when trying to ```require 'azure_sdk'```:
```
LoadError (cannot load such file -- azure_mgmt_signalr)
```

Downgrading to version 0.17.3 or manually installing the ```azure_mgmt_signalr``` gem fixes the problem.

**Comment by sarangan12** [comment]
@seandilda Thanks for reporting the issue. This has been fixed with latest release of 0.18.1 version of azure_sdk (https://github.com/Azure/azure-sdk-for-ruby/pull/1586)
