### ISSUE TITLE
azure_sdk needs to require 'azure/version'

### ISSUE THREAD

**Issue by seandilda** [Azure/azure-sdk-for-ruby#1437]
When doing a ```require 'azure_sdk'```, it forgets to required ```azure/version```.  Without this, calling ```Azure::Profiles::Latest::Client.new``` will fail with:
 ```
uninitialized constant Azure::VERSION (NameError)
```

For anyone running into this, you can workaround it by doing:
```
require 'azure_sdk'
require 'azure_sdk/version'
```

**Comment by sarangan12** [comment]
@seandilda Thanks for reporting the issue. This has been fixed(https://github.com/Azure/azure-sdk-for-ruby/pull/1586) with the latest 0.18.1 version release of azure_sdk. Closing the issue
