### ISSUE TITLE
VM Image list doesn't include My VM Images, Can't create a VM from my new images

### ISSUE THREAD

**Issue by johnsmyth** [Azure/azure-sdk-for-ruby#145]
list_virtual_machine_images only enumerates images from '/services/images'.  Since newer custom images seem to only be available at '/services/vmimages', they are not included in the list of available images.  This function is also called indirectly from create_virtual_machine (via get_os_type), so new VMs cant be created from these images either,

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre
