### ISSUE TITLE
Failed to call #update_endpoints and #delete_endpoint

### ISSUE THREAD

**Issue by kensoncheung** [Azure/azure-sdk-for-ruby#147]
I tried to update virtual machine endpoint and delete endpoint in rspec, but error raised, reported that 

ERROR:
"BadRequest : Subnet name(s) belonging to role  rspec-vm-1401175899 cannot be changed during deployment update or upgrade.
RuntimeError: BadRequest : Subnet name(s) belonging to role  rspec-vm-1401175899 cannot be changed during deployment update or upgrade."

WHAT I TRIED:
vm_service=Azure::VirtualMachineManagementService.new
vm_service.update_endpoints(@vm_name, @cloud_service_name, {
          name: 'ep-1',
          public_port: 996,
          local_port: 998,
          protocol: 'TCP',
        },  {
          name: 'ep-2',
          public_port: 997,
          local_port: 997,
          protocol: 'TCP',
          #load_balancer_name: 'lb-ep2',
          #load_balancer: {:protocol => 'http', :path => 'hello'}
        }
) 
vm_service.delete_endpoint(@vm_name, @cloud_service_name, "TCP-PORT-33306") 

I did't intend to update subnet but endpoint. Appreciative if you guys can take a look into this.

**Comment by devigned** [comment]
If this is still an issue, please reopen.
