### ISSUE TITLE
Cannot find a way to delete data disk

### ISSUE THREAD

**Issue by kensoncheung** [Azure/azure-sdk-for-ruby#148]
Hi there, noticed that the delete_virtual_machine() will delete the deployment, cloud service and disk during VM deletion. 
However, if I added a data_disk to the VM, looks like there is no handling to clean up the data disk during VM deletion.

Noted that delete data disk is a valid route according to AZURE document. 
I tried to find a manual way in cleaning up the data disk, but looks like in this SDK, there is no such method. 

Refs.:
Delete Data Disk - http://msdn.microsoft.com/en-us/library/azure/jj157179.aspx

================================================

BTW, except for the data disk issue, I also find that in my Storage account > Containers > vhds, the vhds are remained after cleaning up the OS disk by the SDK and manually removed the data disk on azure portal. Is this expected? Is it possible to make call for clean up by SDK? 

Look forward to your feedback!

thanks,
Kenson

**Comment by devigned** [comment]
The vm disks occasionally still have leases on them. We could wait for the lease to be let go or allow specification of the lease id for breaking the lease, but it would be pretty painful. It stinks, but it will be better when the resource management features are added soon (Azure REST v2).

Per the data disk, I'll add this in. By default we don't delete it b/c we expected it was added to the vm, but not something we want to delete. I suppose this should be an option on delete vm as well.

**Comment by vishrutshah** [comment]
@kensoncheung @jozefizso @devigned 
We have merged PR from @lrolaz to add the support for deleting VHD while deleting VM. Feel free to check it out and let us know your feedback.
