### ISSUE TITLE
question on cert parameter

### ISSUE THREAD

**Issue by nkcfan** [Azure/azure-sdk-for-ruby#149]
I notice this paragraph in README.md.
To create pfx, simply download the publishsettings file for your subscription, copy the contents of Management Certificate from the publishsettings and save it in a file and name the file as your cert.pfx. This pfx will be a passwordless pfx which can be supplied as a cert parameter for Service Management Commands

If the pfx file can be supplied as a cert parameter for Service Management Commands, why user need further steps to extract public and private keys?

Thanks for any hint!

**Comment by devigned** [comment]
It over complicated... I think it was just left over to provide some info for users looking to navigate from pfx to different forms using openssl.

Bottom line, you should be able to use either .pfx or .pem.
