### ISSUE TITLE
timeout on Azure::Blob::BlobService - create_block_blob doesn't allow the client to not timeout after more than 2 min.

### ISSUE THREAD

**Issue by nicolasdao** [Azure/azure-sdk-for-ruby#155]
I receive a timeout error when I try to upload a file that requires more than 2 minutes(default timeout on Net::HTTP) before its upload is completed. I was hoping to be able to set up the client's timeout by doing the following:

```ruby
blob_options = {
	:content_type => "application/octet-stream",
	:timeout => 15*60 # 15 minutes
}
blob_srv = Azure::Blob::BlobService.new
new_blob = blob_srv.create_block_blob("my_container", "some_name", blob_content, blob_options)
```

But it looks like it only affects the Azure timeout, but not the Net::HTTP client since I keep having the timeout error after 2 minutes. It would be nice if that :timeout setting would affect both.

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre
