### ISSUE TITLE
MsRest::TokenProvider does not pick token_audience dynamically

### ISSUE THREAD

**Issue by zanecodes** [Azure/azure-sdk-for-ruby#1606]
Currently the only way to authenticate to KeyVault (using a Managed Service Identity, for example) is to use some code like the following:

```
settings = MsRestAzure::ActiveDirectoryServiceSettings.new
settings.authentication_endpoint = MsRestAzure::AzureEnvironments::AzureCloud.active_directory_endpoint_url
settings.token_audience = 'https://vault.azure.net'

credentials = MsRest::TokenCredentials.new(
  MsRestAzure::MSITokenProvider.new(50342, settings)
)

keyvault_client = Azure::KeyVault::Profiles::Latest::Client.new(
  credentials: credentials
)
```

The user must construct an `MsRestAzure::ActiveDirectoryServiceSettings` object themselves, and set the `token_audience` to the appropriate resource URL, which they must find out depending on the service they are calling (KeyVault, in this case).

It would be much nicer if instead the `Azure::KeyVault::Profiles::Latest::Client` (or wherever the appropriate level of abstraction is) knew the appropriate `token_audience` value and passed it down to the `MsRest::TokenProvider#get_authentication_header` method, which would fetch the token for the correct resource automatically.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
