### ISSUE TITLE
no `#disks` method in Compute API V2018_06_01

### ISSUE THREAD

**Issue by akostadinov** [Azure/azure-sdk-for-ruby#1614]
In V2018_04_01 the `#disks` method exists and allows management or managed disks. In V2018_06_01 such method is missing and I can't figure out a way to delete/list/whaterver the managed disks.

**Comment by akostadinov** [comment]
I basically expect that the latest API version would have all the features and provide most recommended approach to work with the possible resource types.
I'm presently using the older API version so I guess I don't care unless it becomes deprecated or I need to use newer version because of some other changes/fixes.

It will be IMO ugly to mix different API versions in same program. Also it is appears to me scary to pass objects obtained through one API version to calls against another API version.

I'm sorry if it sounds judgmental but such changes/bugs between API versions as well suggestion to mix API versions in same program, as a user, makes me think the service API is unstable and not well thought out.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
