### ISSUE TITLE
V2018_04_01 lacks VirtualMachine#resource_group method

### ISSUE THREAD

**Issue by akostadinov** [Azure/azure-sdk-for-ruby#1615]
In the 0.11 API there was a method `VirtualMachine#resource_group`, now there isn't. I think it is appropriate for one to get that information. So please bring it back.

**Comment by sarangan12** [comment]
@akostadinov Thanks for reporting this. I will add this as a feature request and will release it soon. I will provide the update in this issue. Thanks

**Comment by sarangan12** [comment]
The latest release https://rubygems.org/gems/azure_mgmt_compute/versions/0.18.1 has this feature enabled. Feel free to reopen the issue if the issue still exists. 

Related PR: https://github.com/Azure/autorest.ruby/pull/33

FYI... @veronicagg @salameer
