### ISSUE TITLE
Support Ruby 2.0 x64 on Windows since Nokogiri is available

### ISSUE THREAD

**Issue by preetpalS** [Azure/azure-sdk-for-ruby#167]
The Nokogiri gem is currently available in a precompiled version for x64 Windows (this has been the case since May 12, 2014 with version 1.6.2 of the gem). I have successfully used this SDK (0.6.4) on Windows 8.1 with Ruby 2.0.0p481 [x64-mingw32] and Nokogiri (1.6.3.1 x64-mingw32) to start and stop a virtual machine that I am running on Windows Azure.

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre
