### ISSUE TITLE
Missing support for new VM sizes

### ISSUE THREAD

**Issue by dJason** [Azure/azure-sdk-for-ruby#171]
The A8, A9, and newly introduced D* series are missing from the allowed VM sizes.

**Comment by sepiroth887** [comment]
Would it be possible to cherrypick this in and add the new G size machines as well?? Also a release would be nice in order for the vagrant-azure repo to leverage this change?

**Comment by devigned** [comment]
#217 should fix this up. I'll leave it open until gem release.

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre
