### ISSUE TITLE
Virtual Network Service Endpoints for Azure CosmosDB

### ISSUE THREAD

**Issue by pritam97** [Azure/azure-sdk-for-ruby#1779]
Please add the ability to set Virtual Network Service Endpoints for Azure CosmosDB, in addition to the ip_range_filter

also to be able to configure it as a resource (external to the cosmos_db_account)

https://azure.microsoft.com/en-us/blog/virtual-network-service-endpoints-for-azure-cosmos-db-is-now-generally-available/

New or Affected Resource(s)
azurerm_cosmos_db_account

**Comment by sarangan12** [comment]
@pritam97 Thanks for reporting the issue. It would be greatly helpful if you could provide a little more context on this issue. 

I assume you are asking about the Azure Cosmos DB service. Currently, We do not have a Ruby SDK for Azure Cosmos DB service. So, I am little confused about " in addition to the ip_range_filter". Could you please explain more? Do you want the Ruby SDK for Azure Cosmos DB? Is that the ask?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
