### ISSUE TITLE
Feature: CLI support for PIPs (public IPs)

### ISSUE THREAD

**Issue by dnorth98** [Azure/azure-sdk-for-ruby#180]
I'd logged the same request against the xplat-cli but it looks like it applies to the ruby sdk too..

Since the PIPs functionality is now GA, it looks like the only way to add a PIP to a running VM is via powershell. Which is great if you're on Windows, but not so great on Linux :)

It would be great to have the PIPs functionality added to the ruby SDK.

PIPs: http://msdn.microsoft.com/library/azure/dn690118.aspx

We managed to 'fake it out' by changing the REST API header version to 2014-05-01 but not sure what else that would affect.  According to the docs (http://msdn.microsoft.com/en-us/library/azure/jj157193.aspx)

The PublicIPs element is only available using version 2014-05-01 or higher.

**Comment by jeroennijhof** [comment]
Fix is included in #292

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
