### ISSUE TITLE
Add support for passing file content directly for management_certificate

### ISSUE THREAD

**Issue by h4hardikonly** [Azure/azure-sdk-for-ruby#183]
Currently the value of `Azure.config.management_certificate` can only be set as a file path. There is no provision of giving file content as a string directly instead of giving file path. Can we add a functionality where user can optionally set `Azure.config.management_certificate` as a string?

Also I would like to contribute in this issue if someone would approve of this feature.

reference: https://github.com/Azure/azure-sdk-for-ruby/blob/master/lib/azure/base_management/base_management_service.rb#L34

**Comment by coliver** [comment]
+1

**Comment by devigned** [comment]
@h4hardikonly if you are interested in contributing this, please submit a pr. It seems like multiple people would like this.

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre

**Comment by stuartpreston** [comment]
As far as I can see, this PR has not been merged properly - as what is currently in master still validates that management_certificate is a file, see:

https://github.com/Azure/azure-sdk-for-ruby/blob/master/lib/azure/base_management/base_management_service.rb#L64-L70

**Comment by djberg96** [comment]
Hm, I thought I was working off the latest. Did I miss a commit? If so, apologies. Definitely agree that it should allow a string, and perhaps even an IO object.

**Comment by stuartpreston** [comment]
Yes, the correct commit is in the PR and appears to do all the right things... so looks like it has been missed:
https://github.com/h4hardikonly/azure-sdk-for-ruby/commit/e34558ca3005b0f9a9c53fb784c01d1f6cfc310c

**Comment by djberg96** [comment]
Hm, what's the best thing to do here? Submit another PR base on master? Sorry for the confusion.

**Comment by stuartpreston** [comment]
If @h4hardikonly resubmits his PR based off master that would probably be the cleanest, then you should be able to pull it straight in and also give credit for the contribution.

**Comment by djberg96** [comment]
Sounds good to me.

**Comment by devigned** [comment]
uhg.. I'll take the blame.

**Comment by hardikj-cuelogic** [comment]
No problem, I am submitting the PR again.

**Comment by h4hardikonly** [comment]
No problem, I am submitting the PR again.
