### ISSUE TITLE
No support for Create Notification Hub

### ISSUE THREAD

**Issue by RocketPop** [Azure/azure-sdk-for-ruby#186]
This API ( http://msdn.microsoft.com/en-us/library/azure/dn223269.aspx ) does not appear to be supported along with most notification hub related APIs
My Ruby is too weak to do this myself :)

**Comment by thierry-rietsch** [comment]
+1 from my side to provide Ruby GEM for using the Notification Hub

**Comment by RocketPop** [comment]
So 1 year later, create/update Hub functions are not in the "original" SDK that I can see. 
Update Hub seems to be missing from the ARM versions of the APIs too - as far as I can tell :) I just need to update APNS certs when they expire. I see this:
http://www.rubydoc.info/gems/azure_mgmt_notification_hubs/Azure/ARM/NotificationHubs/NotificationHubs but there is no setter or way to pass the credentials to a hub (not a namespace)

**Comment by RocketPop** [comment]
In the backlog! Maybe this "feature" will make it in 2017  :)

**Comment by vishrutshah** [comment]
@RocketPop Sorry for the delay. If i am looking at this correctly, do you need this API:

https://github.com/Azure/azure-rest-api-specs/blob/current/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/2017-04-01/notificationhubs.json#L739 ? 

If so we do have it at http://www.rubydoc.info/gems/azure_mgmt_notification_hubs/0.12.0/Azure/ARM/NotificationHubs/NotificationHubs#create_or_update-instance_method 

Let us know if that is not what you are looking for. I'll follow up here and see when can we get it. Thanks!

**Comment by veronicagg** [comment]
@RocketPop If what @vishrutshah pointed out above does not help, please let us know. Closing for now, as  we haven't seen a reply, feel free to reopen if necessary.
