### ISSUE TITLE
No good way to use leases with blobs

### ISSUE THREAD

**Issue by schadr** [Azure/azure-sdk-for-ruby#189]
I am trying to use leases on blob to ensure that only one host can modify the content.

For that purpose I create a lease on a blob by using the 
aquire_lease operation
but there is no way to provide the lease_id for calls such as create_blob_pages, so the only way to use leases is to ensure a blob does not get modified while reading from it.

Or am I missing something?

**Comment by devigned** [comment]
If you would like, provide a pull request.
