### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by Quasilyte** [Azure/azure-sdk-for-ruby#1936]
This repository misses the license file.
The severity of that varies from project to project, but my goal here is to attract some attention.

If it's not a problem, this issue can be closed.

I'm leaving it here just in case: https://help.github.com/articles/adding-a-license-to-a-repository/.

Thanks.

**Comment by sarangan12** [comment]
@Quasilyte Thanks for reporting this issue. Added a License file to the repository now, 

No pending action items for this issue. Resolving it now.
