### ISSUE TITLE
Security issue: can't set storage access policies on a container *unless* you open it up for totally open public read access?

### ISSUE THREAD

**Issue by jf** [Azure/azure-sdk-for-ruby#195]
Sorry for the tone and edits on the subject, but I:
a) just can't believe that this issue has been there in the code for over 2 years
b) there has been no quality control whatsoever to speak of

At best, you could call this a logic error. At worst, this code shows a lack of understanding of what one is coding, and somebody could end up opening up their **private container**, for **full public read access** in an attempt to supposedly fix their problem ("why can't I set storage access policies on my container?") if they don't understand what they're opening themselves up to.

The code for setting an acl for a container (`set_container_acl`) will not let you set storage access policies (because you want to manage / *control access* to the container?) on a container. **Not** unless you set the permissions on the container for full public read access. Surely that defeats the purpose of you wanting to set storage access policies in the first place! "full public read access" should be mutually exclusive with "controlling and managing access to your container using storage access policies".

Offending code/commit:

https://github.com/Azure/azure-sdk-for-ruby/commit/741267f24509e93b3b576c2b60d18f5c3e70bb86#diff-fc067e61a5b50966e9ef33e34396c2b9R263:
```
 body = Serialization.signed_identifiers_to_xml(signed_identifiers) if signed_identifiers && headers["x-ms-blob-public-access"] == "container"
```
The `&& headers["x-ms-blob-public-access"] == "container"`at the end needs to be removed. Why should I only be allowed to set storage access policies on a container if I make it publicly readable?

More info from your own docs:
- https://msdn.microsoft.com/en-us/library/azure/dn140257.aspx ("Establishing a Stored Access Policy")
- https://msdn.microsoft.com/en-us/library/azure/dd179391.aspx ("Set Container ACL")

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre
