### ISSUE TITLE
License text in the sources

### ISSUE THREAD

**Issue by valtri** [Azure/azure-sdk-for-ruby#196]
Hello,

I'm packaging azure gem for Fedora and there are some recommendation according to license texts in the sources: https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text

Could you provide license text in the sources? (it is not needed for distributions, but it is recommended to distribute license text also in gems)

Apache 2.0 license:
http://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre
