### ISSUE TITLE
Logging issues breaking integration

### ISSUE THREAD

**Issue by arax** [Azure/azure-sdk-for-ruby#199]
The following logging issues break the integration of this library with other applications. What's the best way to get this fixed ASAP? A pull request? I'd be happy to help.

See `lib/azure/core/utility.rb` and `lib/azure/base_management/base_management_service.rb`
- "logging" to STDOUT only

``` ruby
def error(msg)
  puts msg.bold.red
  msg
end
```
- "logger" raising exceptions

``` ruby
def error_with_exit(msg)
  puts  msg.bold.red
  raise msg.bold.red
end
```
- "colorful logging" breaking non-shell logging targets

``` ruby
class String
  { reset:  0,
    bold:  1,
    dark:  2,
    underline:  4,
    blink:  5,
    orange:  6,
    negative:  7,
    black: 30,
    red: 31,
    green: 32,
    yellow: 33,
    blue: 34,
    magenta: 35,
    cyan: 36,
    white: 37,
  }.each do |key, value|
    define_method key do
      "\e[#{value}m" + self + "\e[0m"
    end
  end
end
```
- "logger leaking" from Azure's namespace

``` ruby
Loggerx = Azure::Core::Logger
```

**Comment by devigned** [comment]
Please submit a PR, and I'll review it.

**Comment by sarangan12** [comment]
@arax If you are planning to submit the PR, you can reopen this issue. Since this is an old issue I am closing this issue
