### ISSUE TITLE
Redundant initialize defs

### ISSUE THREAD

**Issue by arax** [Azure/azure-sdk-for-ruby#202]
What is the purpose of this code?

See `lib/azure/virtual_machine_image_management/virtual_machine_image_management_service.rb` (among others)

```ruby
class VirtualMachineManagementService < BaseManagementService
  def initialize
    super()
  end

  #...
end
```

**Comment by devigned** [comment]
Agreed. That should be removed.

**Comment by devigned** [comment]
Added in a large refactor: #248
