### ISSUE TITLE
Rescuing Exception class

### ISSUE THREAD

**Issue by arax** [Azure/azure-sdk-for-ruby#203]
Rescuing `Exception` class in Ruby is a big no-no. Please, have a look at [this post](http://blog.nicksieger.com/articles/2006/09/06/rubys-exception-hierarchy/) for more information. It is a critical issue.

See `lib/azure/base_management/base_management_service.rb` (among others)

``` ruby
begin
  # ...
rescue Exception => e
  raise "Management certificate not valid. Error: #{e.message}"
end
```

**Comment by devigned** [comment]
Agreed. :+1:

If you'd like to submit a PR, we'll get it pulled in.

**Comment by sarangan12** [comment]
@arax Please reopen this issue when you have a PR. Since this is an old issue, I am closing it
