### ISSUE TITLE
Rescuing all errors in API methods

### ISSUE THREAD

**Issue by arax** [Azure/azure-sdk-for-ruby#204]
Rescuing all errors in API methods makes sensible error handling and integration of this library into applications almost impossible. Once you convert identifiable error classes into free-form strings, distinguishing them becomes problematic at best. 

See #203 for `Exception` rescuing issues
See `lib/azure/virtual_machine_management/virtual_machine_management_service.rb` (among others)

``` ruby
def create_virtual_machine(params, options = {})
  # ...
  get_virtual_machine(params[:vm_name], options[:cloud_service_name])
rescue Exception => e
  e.message
end
```

**Comment by vinyar** [comment]
:+1: :) As a noobie this would make my life much easier for debugging

**Comment by devigned** [comment]
Agreed. We should wrap or bubble up. Would you submit a PR?

**Comment by sarangan12** [comment]
@arax Please reopen this issue when you submit a PR. Since this is an old issue, I am closing this
