### ISSUE TITLE
azure_mgmt_monitor lacking some profiles

### ISSUE THREAD

**Issue by miha-plesko** [Azure/azure-sdk-for-ruby#2079]
A bunch of providers e.g. azure_mgmt_compute and azure_mgmt_resources are supporting the three profile clients:

- `V2017_03_09`
- `V2018_03_01`
- `Latest`

while azure_mgmt_monitor only supports

- `Latest`

It would be great if azure_mgmt_monitor would also support the `V2017_03_09` and `V2018_03_01` profile clients. This way we could use it consistently like this:

```ruby
profile         = "V2017_03_09"

compute_client  = "Azure::Compute::Profiles::#{profile}::Mgmt::Client".constantize.new(options)
resource_client = "Azure::Resources::Profiles::#{profile}::Mgmt::Client".constantize.new(options)
monitor_client  = "Azure::Monitor::Profiles::#{profile}::Mgmt::Client".constantize.new(options)
# the last line ^ currenly breaks, because profile client is missing
```

**Comment by sarangan12** [comment]
@miha-plesko Thanks for reporting this. But, the profiles are not created for that purpose. The only profile that will be in all SDKs is ```Latest``` profile. The other 2 profiles are created based on specific request from an internal customer. So, they are not included in other SDKs. 

No more action items on this issue. Resolving it for now.
