### ISSUE TITLE
Why raise a message but not a exception in VirtualMachineManagementService.create_virtual_machine?

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-ruby#208]
I want to get the error code of the error in VirtualMachineManagementService.create_virtual_machine but this method only raise a message. This is very bad. Could I change it to raise the exception?

Azure::VirtualMachineManagement::VirtualMachineManagementService.create_virtual_machine(...)
      rescue Exception => e
        e.message
      end

**Comment by devigned** [comment]
Agreed. This should provide more feedback than just a string. Please submit a PR.

**Comment by djberg96** [comment]
In this particular case it looks like it should just be removed, and the exception allowed to bubble up.

**Comment by djberg96** [comment]
Actually, I guess to be consistent with the rest of the code base, it's better to use Azure::Logger.error_with_exit. I'll submit a PR.

**Comment by djberg96** [comment]
Welp, that broke the test suite, but I think these are supposed to be expected, so it may be an issue with the tests themselves.

**Comment by devigned** [comment]
fixed in: #246
