### ISSUE TITLE
Security issue: SSL certificate is not verified

### ISSUE THREAD

**Issue by bukk530** [Azure/azure-sdk-for-ruby#210]
I was wondering if the communication between my servers and azure was secured by SSL and I noticed something strange: https://github.com/Azure/azure-sdk-for-ruby/blob/master/lib/azure/core/http/http_request.rb#L146
It means the connction is encrypted but is susceptible to MITM attacks, as any tampered certificate would be accpted.
Am I just paranoid or I'm missing something?

**Comment by devigned** [comment]
@bukk530 I don't think you're paranoid. Could you submit a PR?

**Comment by bukk530** [comment]
I came up with this, and It's working fine https://github.com/Azure/azure-sdk-for-ruby/pull/211

**Comment by devigned** [comment]
fixed in #219 and #220
