### ISSUE TITLE
Chunk big blobs

### ISSUE THREAD

**Issue by kamilsmuga** [Azure/azure-sdk-for-ruby#212]
As reported here: http://stackoverflow.com/questions/23567724/ruby-azure-blob-storage-requestbodytoolarge, SDK doesn't split files bigger than 64M for API supported upload.

Currently, solutions are available using different gems: 
- Ruby: https://github.com/dmichael/azure-contrib
- UI: https://github.com/Sology/azure_direct_upload

This should be a part of SDK, imho.

**Comment by devigned** [comment]
I agree with you regarding the azure-contrib functionality, but I don't agree with the direct upload functionality.

I'm also not super crazy with the [Celluloid](https://celluloid.io) usage in the azure-contrib. I'd prefer to use [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby).

If you'd like to submit a pull request for this addition, I'd be happy to review it.

**Comment by veronicagg** [comment]
Issue migrated to azure-storage  repo.
