### ISSUE TITLE
`MsRestAzure::MSITokenProvider` doesn't support (undocumented!) `bypass_cache` query parameter

### ISSUE THREAD

**Issue by zanecodes** [Azure/azure-sdk-for-ruby#2163]
When using groups to organize permissions for Managed Service Identities, the identity must be added to the group after it is created (since this cannot be done in an ARM template).
If any code (say, in Chef) accesses the MSI endpoint to get a bearer token before the identity has been added to the appropriate group(s), the IMDS endpoint will cache this token (which contains no group object ids) for 8 hours, and any attempts to access the resources that the group has permissions to using this token will fail until the cache expires and a fresh token is returned.
A workaround for this is to prevent any access to the MSI endpoint until after the identity has been added to the group(s) (by setting the Chef runlist to empty until after the group addition, in our case) but this is not a very good solution.
Alternatively, we were told by Azure support that there is an undocumented query parameter for the MSI token endpoint, `bypass_cache`, that will bust the cache and return a fresh token, solving our problem.
However, since `MsRestAzure::MSITokenProvider` does not provide any means to pass this query parameter, we effectively have to re-implement it ourselves to get this functionality.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
