### ISSUE TITLE
Managed Identity: Configurable timeout based on time

### ISSUE THREAD

**Issue by arluca** [Azure/azure-sdk-for-ruby#2192]
Currently, the retry logic in the Azure SDKs for Managed Identity token generation supports a configurable time out based on counts. For response time sensitive services this has not been enough. Per customer feedback, they would like to have timeout configuration based on time (i.e. milliseconds)
This will allow for quicker fail after certain.
Can we make the retry max configurable based on time?
@binderjoe FYI

**Comment by arluca** [comment]
@binderjoe any update on this one?

**Comment by arluca** [comment]
@binderjoe any update on this one?

**Comment by yugangw-msft** [comment]
This is done. Ruby Runtime has exposed an env variable `USER_DEFINED_IMDS_MAX_RETRY_TIME` for this

//CC: @sarangan12
