### ISSUE TITLE
Setting :peek_lock

### ISSUE THREAD

**Issue by lyberikus** [Azure/azure-sdk-for-ruby#223]
Within the service bus its currently not possible setting peek lock to anything other than true, this line
`peek_lock = options[:peek_lock] if options[:peek_lock]`
seems to be the culprit, if set to false the if will be false and the row skipped.

something like 
`options.fetch(:peek_lock, true)`
would be more appropriate

**Comment by devigned** [comment]
Yes, that seems like it would be helpful. Please send in a PR.

**Comment by devigned** [comment]
Should be fixed in 0.7.0.pre
