### ISSUE TITLE
Confusing documentation link cycle from Readme

### ISSUE THREAD

**Issue by fdr** [Azure/azure-sdk-for-ruby#2239]
I'm trying to find API (e.g. YARD) documentation. I note it is able to be generated in the Readme, but I just want look up a few things without a local copy. I figure if it can be generated, it must be on the web (accurate, but I had to use a search engine to find it).

Details:

I'm at https://github.com/Azure/azure-sdk-for-ruby.

What I want is in the "Compute" gem, so I click on that, it navigates to: https://rubygems.org/gems/azure_mgmt_compute

Alright, at this point, my expectation is to click "Documentation" from RubyGems is to see this yard documentation. Instead, it takes me to this Microsoft site:

https://azure.microsoft.com/en-us/develop/ruby/

Okay, fine, one more indirection. Seems alright. I click big "Read the full Azure SDK for Ruby documentation" link and...

I'm at https://github.com/Azure/azure-sdk-for-ruby/blob/master/README.md, i.e. more or less the same as https://github.com/Azure/azure-sdk-for-ruby.

After going carefully through these steps a few times, I run a general search for "ruby azure sdk yard docs" and scan the result listings, and find https://www.rubydoc.info/github/Azure/azure-sdk-for-ruby, ~~which is useful~~ actually, it isn't: it superficially appears to be but doesn't have program symbols, but by searching the gem name directly I find https://www.rubydoc.info/gems/azure_mgmt_compute. Out of curiosity, I do a text search for "rubydoc" using Github on the repo, and find no mention of it. I also don't see it on the azure.microsoft.com site (as assessed by show-source and a few clicks).

Seems like there's several opportune places to break the cycle here.

**Comment by pavankanth6** [comment]
I second @fdr 's problem. The cyclical flow of information is very difficult to achieve progress in integrating with Azure REST API.

**Comment by tbugfinder** [comment]
I second that, too.

The documentation is a cycle and most importantly a API reference documentation comparable to the python documentation would be really appreciated.

https://docs.microsoft.com/en-us/python/api/overview/azure/?view=azure-python

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
