### ISSUE TITLE
Azure Network Operations List method is failing due to no api-version being passed

### ISSUE THREAD

**Issue by pparamalingam** [Azure/azure-sdk-for-ruby#2251]
Azure::Network::Mgmt::V2018_11_01::Operations list() fails to query as it complains that the REST API needs api-version passed

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
