### ISSUE TITLE
Add Microsoft Azure Advisor as a GEM (azure_mgmt_advisor)

### ISSUE THREAD

**Issue by pparamalingam** [Azure/azure-sdk-for-ruby#2297]
The Azure Advisor API is missing for the ruby SDK
https://docs.microsoft.com/en-us/rest/api/advisor/

It exists for Python SDK
https://github.com/Azure/azure-sdk-for-python/tree/master/azure-mgmt-advisor

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
