### ISSUE TITLE
Support for event hub?

### ISSUE THREAD

**Issue by bronaghs** [Azure/azure-sdk-for-ruby#233]
Does this gem have support for the azure event hub? If not, is there another way to get events (such as VM reboot, VM was reconfigured)?

thanks

**Comment by devigned** [comment]
This gem does not support event hub as of yet.

**Comment by devigned** [comment]
I'll ping back with any details for vm reboot events and reconfiguration.

**Comment by devigned** [comment]
VM reboot and reconfiguration events should be available through operational insights (https://msdn.microsoft.com/en-us/library/azure/dn931943.aspx).
