### ISSUE TITLE
401 (40103) from SharedAccessSigner on Servicebus usage with SAS

### ISSUE THREAD

**Issue by lbalceda** [Azure/azure-sdk-for-ruby#2357]
Hello, I'm trying to access ServiceBus topic given a SAS token, but keep getting 401 errors. 

I was able to use postman/curl to successfully get messages back so the token is definitely correct/working, and just wanted to double check my configuration. 

The key looks like this 
```
SharedAccessSignature sig=xyz&se=1577730912&skn=someKeyName&sr=https%3a%2f%2fmyServiceBus.servicebus.windows.net$2ftestChange
```
so from the token you can see the topic is `testChange`, the namespace is `myServiceBus` and keyname is `someKeyName`. what is wrong with my code below?

```
Azure.configure do |config|
  config.sb_namespace = 'myServiceBus'
  config.sb_sas_key_name = 'someKeyName'
  config.sb_sas_key = 'SharedAccessSignature sig=xyz&se=1577730912&skn=someKeyName&sr=https%3a%2f%2fmyServiceBus.servicebus.windows.net$2ftestChange'
end

signer = Azure::ServiceBus::Auth::SharedAccessSigner.new
sb_host = "https://myServiceBus.servicebus.windows.net"
servicebus = Azure::ServiceBus::ServiceBusService.new(sb_host, { signer: signer })
servicebus.receive_subscription_message('testChange', 'mySubscriptionName')
```

returns 
```
# Azure::Core::Http::HTTPError (Unknown (401): 40103: Invalid authorization token signature)
```

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
