### ISSUE TITLE
Support for the new REST API

### ISSUE THREAD

**Issue by djberg96** [Azure/azure-sdk-for-ruby#237]
Are there any plans to add support the newer REST API?

If not, I guess I'll fork and try to rework the guts using rest-client + json, as I would like to keep the same interface.

Or has anyone else already started this? I wanted to ask before I duplicated anyone's efforts.

**Comment by devigned** [comment]
This is in the works, but feel free to hack away.

**Comment by djberg96** [comment]
It's in the works? Is there anything I can look at?

**Comment by devigned** [comment]
Nothing yet.
