### ISSUE TITLE
Invalid method in the KeyVaultClient

### ISSUE THREAD

**Issue by jlorich** [Azure/azure-sdk-for-ruby#2396]
`first_page = get_keys_as_lazy_as_lazy(vault_base_url, maxresults:maxresults, custom_headers:custom_headers)`

This seems to be an auto generation error, there is no method called get_keys_as_lazy_as_lazy and calling get_keys throws an exception.

**Comment by jlorich** [comment]
For the record, I have a fairly large customer attempting to use this and it does not work.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
