### ISSUE TITLE
Upgrading Azure API version

### ISSUE THREAD

**Issue by jayyvis** [Azure/azure-sdk-for-ruby#240]
Hi,

It appears list_locations API returns ComputeCapabilities of a location starting from API version 2014-05-01. https://msdn.microsoft.com/en-us/library/azure/gg441293.aspx#bk_computecapabilities

I observed this SDK currently uses API version 2012-02-12 and missing sizes data. Is there a plan to upgrade this SDK to latest API version?

**Comment by devigned** [comment]
I think we are going to target most updates toward the Azure Resource Management APIs rather than the Service Management APIs. With that said, we do accept pull requests.

**Comment by devigned** [comment]
Added in a large refactor: #248
