### ISSUE TITLE
Implement a unified token provider with fallback

### ISSUE THREAD

**Issue by jlorich** [Azure/azure-sdk-for-ruby#2400]
Implement a token provider similar to the [AzureServiceTokenProvider](https://github.com/Azure/azure-sdk-for-net/blob/40248f466aa063bd90f16dae10d06b9b7317e2d0/src/SdkCommon/AppAuthentication/Azure.Services.AppAuthentication/AzureServiceTokenProvider.cs) for dotnet, which handles determining which token token provider is appropriate to use.

This provider should check through the following options, in order, and then configure the correct provider to use:
- Passed-in parameters 
- Environment Variables
- Managed Service Identity
- Azure CLI

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
