### ISSUE TITLE
Cannot create a new VM endpoint if the VM is part of a Virtual Network

### ISSUE THREAD

**Issue by ebuildy** [Azure/azure-sdk-for-ruby#245]
Let's say I have already a VM, within a virtual network. Now I want to add an endpoint:

````
virtual_machine_service.update_endpoints(name, vm.service, {
       :name => endpoint_name,
       :public_port => endpoint.public_port,
       :local_port => endpoint.local_port,
       :protocol => 'TCP'
    })
````

I get the error:

    BadRequest : Subnet name(s) belonging to role ***** cannot be changed during deployment update or upgrade.

The issue is because the "update role" endpoint will update all configuration by the new settings and in my case, the Ruby SDK is missing the Subnet attribute (BTW which it can be very dangerous).

This question seems related to Azure API more than each client SDK:
- https://github.com/Azure/azure-xplat-cli/issues/543

**Comment by ebuildy** [comment]
Also, in the portal I can see a different method to add an endpoint:

"https://manage.windowsazure.com/Iaas/AddEndpoint"

http://j.mp/1Etwt2a

But missing on the SDK ;-(

**Comment by devigned** [comment]
I think you be much happier with the new ARM bits. See: https://github.com/Azure/azure-sdk-for-ruby/tree/master/resource_management/azure_mgmt_compute
