### ISSUE TITLE
SDK needs to handle token refresh for long running operations

### ISSUE THREAD

**Issue by logachev** [Azure/azure-sdk-for-ruby#2462]
I was trying to deploy AKS cluster via Ruby SDK today and I hit '401 Not Authorized: Token expired' error while SDK poller was querying for the operation result.

SDK Long Running Operation Poller needs to handle this error & query a new token.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
