### ISSUE TITLE
Adding Azure Resource Manager api's support

### ISSUE THREAD

**Issue by siddheshwar-more** [Azure/azure-sdk-for-ruby#247]
@devigned , @bradygaster, @andrerod 

Do we have any plan to add support for [Azure Resource Manager](https://msdn.microsoft.com/en-us/library/azure/dn790568.aspx) related API's. 

Is there any team working on this? Please let us know we are planning to work on this.

**Comment by devigned** [comment]
This is in progress. We are looking to get a preview of the ARM bits out this month.

The api's produced for ARM will be sourced from generated code via API specs, so there will likely be opportunities to build a better DSL / abstraction layer over top of these client http apis. As we get the generated bits out, we'd love to get some feedback and collaborate on improving the library.

Please stay tuned over the course of the next few weeks.

**Comment by djberg96** [comment]
We've started one over at https://github.com/djberg96/azure-armrest. Feedback welcome, though we are sort of gearing it for ManageIQ.

**Comment by devigned** [comment]
@djberg96 your repo looks much simpler than the current SDK (in a really good way).

**Comment by djberg96** [comment]
@devigned Thanks! It's definitely unstable at the moment, however, as we continue to poke at it. This will probably be moved under the ManageIQ account, too.

**Comment by siddheshwar-more** [comment]
@devigned - We would like to test this changes :). Can we get access to development repository?

Right now we are planning to add resource manger support in [knife-azure](https://github.com/chef/knife-azure/) .

**Comment by devigned** [comment]
@siddheshwar-more it is close, and I promise you guys will get first dibs on the bits when they land.

**Comment by djberg96** [comment]
@devigned Should we continue our work? It seems a waste to duplicate effort.

**Comment by devigned** [comment]
If you guys are able to add some feedback to https://github.com/Azure/autorest/tree/dev/ClientRuntimes/Ruby/ms-rest, and more generally, the code generator https://github.com/Azure/autorest/tree/dev/AutoRest/Generators/Ruby it'd help get your say in how the ARM API will look and feel. 

We are going to be generating the API via Swagger API specifications. The code for the Ruby generator is available in the dev branch. It's still in a formative phase, so if we can get some community eyes on it, your feedback will have a big impact on the project. Feel free to submit PRs and issues.

**Comment by djberg96** [comment]
@devigned I wasn't aware of Swagger, interesting. Well, with the silence the last few weeks we've been pressing forward using online documentation and an API that just felt nice to us. If there ends up being two gems for ARM, it will give users a choice.

**Comment by devigned** [comment]
Right on. Ping me if there anything we can help on.

**Comment by djberg96** [comment]
@devigned Thanks, we appreciate that. I definitely have some things I need help with. :)

**Comment by djberg96** [comment]
BTW, for anyone following, the main repo is now at https://github.com/ManageIQ/azure-armrest. There's no release yet. Some of that is stub code where we were just laying out an initial interface, but some of it is definitely functional.

**Comment by djberg96** [comment]
@devigned If you know the magic incantations required for https://github.com/ManageIQ/azure-armrest/issues/31 we would love to know what they are.

**Comment by devigned** [comment]
We are starting the work in the `feature/arm` branch. The refactor begins and code should start dropping shortly.

**Comment by devigned** [comment]
preview gems are pushed and the code is now in master.

**Comment by devigned** [comment]
Btw: there will be more libraries coming soon :)

**Comment by ctaggart** [comment]
@devigned [mentioned](https://github.com/Azure/azure-sdk-for-ruby/issues/247#issuecomment-120475811):
> We are going to be generating the API via Swagger API specifications. 

Are there Swagger API specifications available for the Azure ARM APIs? I'm looking for some and just asked by creating https://github.com/Azure/autorest/issues/475.

**Comment by devigned** [comment]
Awesome, you found them. I'll put together a blog post describing this process in more detail soon.
