### ISSUE TITLE
UsageDetail attribute pretax_cost has wrong type.

### ISSUE THREAD

**Issue by aheumaier** [Azure/azure-sdk-for-ruby#2499]
In Module[ Azure::Consumption::Mgmt the class UsageDetail](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_consumption/lib/2018-06-30/generated/azure_mgmt_consumption/models/usage_detail.rb)  uses an _Integer class_ for attribute :pretax_cost. This results in values of 0  - while  most of the values are in the form _Float_ as 0.0005.
This field has to be a float for accurate cost calculations (correctly implemented in Python SDK)

```
# Poor mans monthly cost calculator
#
response = Azure::Consumption::Profiles::Latest::Mgmt::Client.new.usage_details.list(filter: "properties/usageEnd ge '2019-04-01' AND properties/usageEnd le '2019-04-30'")

sum = 0.0

response.each do |item|
  sum += item.pretax_cost
end

puts sum

```

Please let me know if you have any questions - happy to help!

**Comment by sgiacomel** [comment]
This applies also to these properties:
usageQuantity
billableQuantity

**Comment by sgiacomel** [comment]
Reported here: 
https://social.msdn.microsoft.com/Forums/azure/en-US/266d4123-3407-4e65-8f79-09a64ac857bd/bug-in-azuresdkforruby-consumption?forum=windowsazuredevelopment

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
