### ISSUE TITLE
Released Gem 0.6.4 has issues

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-sdk-for-ruby#252]
When I put `gem 'azure'` in my Gemfile. I get the error "cannot load such file -- azure (LoadError)" when trying to load Rails.

When I add `gem 'azure', github: 'azure/azure-sdk-for-ruby'`, Rails loads fine, as expected.

**Comment by devigned** [comment]
Thank you for verifying. I'll push out a new release.

**Comment by devigned** [comment]
Fixed in 0.7.0.pre2. `gem install azure --pre`
