### ISSUE TITLE
Azure setup error

### ISSUE THREAD

**Issue by Edwardzyc** [Azure/azure-sdk-for-ruby#254]
NoMethodError: undefined method `storage_account_name' for Azure:Module

when trying to execute the example

 require "azure"
 Azure.storage_account_name = "<your azure storage account name>"

**Comment by devigned** [comment]
Well, that's pretty terrible. I'll look at it today.

**Comment by devigned** [comment]
Oh... What version are you using? If you are not using 0.7.0.pre or greater, install the gem as pre-release. 

'gem install azure --pre'

**Comment by devigned** [comment]
Ping?

**Comment by Edwardzyc** [comment]
pre-release fixes it. Thanks! :D

**Comment by devigned** [comment]
Thank you for reporting and confirming.
