### ISSUE TITLE
Error when using password protected .pfx

### ISSUE THREAD

**Issue by jervill** [Azure/azure-sdk-for-ruby#256]
When I set the azure management certificate to a password protected .pfx file, I get an error

`ArgumentError: Management certificate not valid. Error: PKCS12_parse: mac verify failure`

Unless I'm missing something, I don't see any way to pass in a password when selecting the management certificate. Would be nice to allow another environment variable or argument for the password, or prompt the user for the password if one is required.

**Comment by devigned** [comment]
Just to be clear, are you using 0.7.0.pre2?

Yes, that would be helpful. I had thought about doing that during the latest refactor, but ran out of time. Would you be interested in submitting a pull request?

**Comment by jervill** [comment]
Thanks for the quick response! Yup, I'm on 0.7.0.pre2.

Sure, I'd be interested in submitting a PR! I'll aim to get one submitted in the next couple of days.

**Comment by devigned** [comment]
Awesome. Looking forward to it.

**Comment by sarangan12** [comment]
@jervill Please reopen this issue when you submit a PR. Since this is an old issue, I am closing this
