### ISSUE TITLE
Support for Endpoint ACL Rules

### ISSUE THREAD

**Issue by mafraba** [Azure/azure-sdk-for-ruby#259]
Feature request:

It would be handy to be able to set ACL Rules on the endpoints. I mean for example creating and endpoint where only traffic from a specific CIDR IP is allowed.

This is something the API supports but, as far as I can see, there's no way to do with this SDK.

**Comment by mafraba** [comment]
Also, there is currently a method '#update_endpoints' in the virtual machine management service that kind of merges the endpoints we pass as parameters with those endpoints already in the machine.

It would be useful to have another method (say '#set_endpoints') that completely overrides what's currently on the machine, and just sets what we pass as parameters - that's actually how the API works if I'm not wrong.

**Comment by devigned** [comment]
Check out the new ARM bits for [networking](https://github.com/Azure/azure-sdk-for-ruby/tree/master/resource_management/azure_mgmt_network) and [compute](https://github.com/Azure/azure-sdk-for-ruby/tree/master/resource_management/azure_mgmt_compute). I think that should help you get want you want
