### ISSUE TITLE
Feature request: Add support for client-side timeout

### ISSUE THREAD

**Issue by guangyang** [Azure/azure-sdk-for-ruby#26]
It is possible for an HTTP call to never return. When that happens, the client needs to know when to give up, using a client-side timeout. See this [Java code](https://github.com/WindowsAzure/azure-sdk-for-java/pull/154) that adds the client-timeout support for ideas.

  **Note**: PHP does not have this feature, and neither did Java for the first 8 months.

**Comment by sedouard** [comment]
Hey @devigned @guangyang I'm hitting this issue quite hard while doing some integration with cloud foundry.

We're trying to upload a large page blob, (thousands of pages). We're doing it multithreaded and at some point all of our upload threads hang. I tried patching the `http_request` to use `http.open_timeout = 90` to see if that would help (our code will do 20 upload retries per thread). We do specify a timeout of 300 seconds but thats not being honored by the server so we'd like to kill the connection ourselves.

Raising an exception on our thread calling the sdk doesn't seem to clean up the tcp connection (we see the connections hanging via `tcptrack`).

Any guidance here on the best way to implement a client-side timeout that will cleanup the connection?

**Comment by sedouard** [comment]
This issue happens almost all the time for us, but sometimes (rarely) the code as it is works. I'm sure in other network situations, the code may work more reliably but this issue causes the upload to not work in some scenarios.

**Comment by sedouard** [comment]
And FYI - I've had to do [a similar implementation](https://github.com/Azure/bosh_azure_cpi/pull/9) for the bosh azure cpi.

It would be great to get something like this into the ruby sdk. I'm not a ruby pro though and I'm not sure what timeout we'd want to use but I'd be happy to PR a change here if you guys think you'll take it.
