### ISSUE TITLE
NetworkManagementClient should be NetworkResourceProviderClient

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-ruby#265]
In the [https://github.com/Azure/azure-sdk-for-ruby/blob/master/resource_management/azure_mgmt_network/README.md](https://github.com/Azure/azure-sdk-for-ruby/blob/master/resource_management/azure_mgmt_network/README.md)

client = NetworkManagementClient.new(credentials) 
should be
client = NetworkResourceProviderClient.new(credentials)

**Comment by garethr** [comment]
I just found this as well and was about to file an issue.

**Comment by devigned** [comment]
Thank you @AbelHu and @garethr. It's fixed.

**Comment by hunner** [comment]
This seems to be backwards now, @devigned . As of 0.3.1 NetworkManagementClient exists but NetworkResourceProviderClient does not.
