### ISSUE TITLE
v0.7.0: blob_service::get_blob_properties returns a blob instead of blob_properties

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-ruby#270]
v0.7.0: blob_service::get_blob_properties returns a blob instead of blob_properties

https://github.com/Azure/azure-sdk-for-ruby/blob/v0.7.0/lib/azure/blob/blob_service.rb#L777-778

**Comment by veronicagg** [comment]
issue is moved to the azure-storage-ruby repo.
