### ISSUE TITLE
Can't get operational insights workspace search results

### ISSUE THREAD

**Issue by jsmartt** [Azure/azure-sdk-for-ruby#2706]
I'm trying to use the Ruby SDK to get performance metrics (CPU & memory utilization) from an AKS cluster's OMS workspace, similar to what is shown in the Monitoring -> Insights tab in the Azure GUI.

However, even the most basic of query (which works on the GUI's log query form) returns an error like the following:

```json
MsRestAzure::AzureOperationError: {
  "message": "MsRestAzure::AzureOperationError",
  "request": {
    "base_uri": "https://management.azure.com",
    "path_template": "subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/search",
    "method": "post",
    "skip_encoding_path_params": null,
    "query_params": {
      "api-version": "2015-03-20"
    },
    "skip_encoding_query_params": null,
    "headers": {
      "Content-Type": "application/json; charset=utf-8",
      "Accept": "application/json",
      "accept-language": "en-US"
    },
    "body": "{\"query\":\"Perf | take 3\"}",
    "middlewares": [
      [
        "MsRest::RetryPolicyMiddleware",
        {
          "times": 3,
          "retry": 0.02
        }
      ],
      ["cookie_jar"]
    ],
    "log": null
  },
  "response": {
    "body": "",
    "headers": {
      "cache-control": "no-cache",
      "pragma": "no-cache",
      "expires": "-1",
      "x-ratelimit-remaining": "99",
      "x-ratelimit-limit": "100",
      "request-context": "appId=cid-v1:(filtered)",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "x-content-type-options": "nosniff",
      "x-ms-ratelimit-remaining-subscription-resource-requests": "149999",
      "server": "Microsoft-IIS/10.0",
      "x-powered-by": "ASP.NET",
      "x-ms-request-id": "(filtered)",
      "x-ms-correlation-request-id": "(filtered)",
      "x-ms-routing-request-id": "WESTUS:20190729T155222Z:(filtered)",
      "date": "Mon, 29 Jul 2019 15:52:22 GMT",
      "connection": "close",
      "content-length": "0"
    },
    "status": 410
  }
}
```

Here's the code:

```ruby
# Client Setup:
provider = MsRestAzure::ApplicationTokenProvider.new(
  credentials[:tenant_id],
  credentials[:client_id],
  credentials[:client_secret]
)
insights_client = Azure::OperationalInsights::Mgmt::V2015_03_20::OperationalInsightsManagementClient.new(
  MsRest::TokenCredentials.new(provider)
)
insights_client.subscription_id = credentials[:subscription_id]


# Get performance metrics from an AKS OMS workspace:
search_params = Azure::OperationalInsights::Mgmt::V2015_03_20::Models::SearchParameters.new.tap do |params|
  params.query ='Perf | take 3'
end
insights_client.workspaces.get_search_results(resource_group_name, workspace_name, search_params)
```

A [410 response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410) "indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent", so it looks like the SDK is using the wrong API.

Upon further inspection, here's the comparison of the URLs used by the SDK vs the GUI:
- Ruby SDK: `https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/search?api-version=2015-03-20`
- GUI: `https://management.azure.com/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/microsoft.operationalinsights/workspaces/{workspaceName}/query?api-version=2017-10-01`

The GUI is using an API version that is not available in the Ruby SDK, and the path is `/query`, not `/search`.

In addition, the GUI's AKS Logs Query Form appears to use yet another API: `https://api.loganalytics.io/v1/workspaces/{workspaceId}/query`

I don't need the latest API, but I do need to be able to access one that works. Any help on this is much appreciated.

**Comment by MyronFanQiu** [comment]
@jsmartt Thanks. I will contact the service team to see whether I should release new Ruby SDK containing new API-Version.

**Comment by seanmck** [comment]
Swapping labels since this is the Ops Insights API (even though the data is generated from AKS).

**Comment by yossi-y** [comment]
Hello,
We have done work on Log Analytics SDKs recently - Could you confirm if the issue is resolved please?

Thanks,
Yossi

**Comment by MyronFanQiu** [comment]
@yossi-y Hi. If you want to release new SDK, please send a request through https://portal.azure-devex-tools.com/

**Comment by shemers** [comment]
#need-author-feedback

**Comment by yossi-y** [comment]
Jared hi,
can you update if the issue is now resolved after the recent SDK refresh?

**Comment by jsmartt** [comment]
@yossi-y, I'm trying to figure out how to perform that search/query operation with the new SDK versions, because the `workspaces.get_search_results` method was removed by #2786. I'm struggling to find a replacement method. Any help would be appreciated.

**Comment by yossi-y** [comment]
The API that you used was deprecated and therefore you got the 410.
The way to query with higher limits is using when using the query API (https://docs.microsoft.com/en-us/rest/api/loganalytics/dataaccess/query/execute).

**Comment by jsmartt** [comment]
@yossi-y, I understand that, and that's what I'm doing with my own code, but it's either missing from the SDK, or I just haven't found it yet. If it's missing from the SDK, then I'd say the issue persists

**Comment by yossi-y** [comment]
The deprecation of workspace search results API actually removed the query option from the SDK. The only way to query Log Analytics is when using the query API (https://docs.microsoft.com/en-us/rest/api/loganalytics/dataaccess/query/get, https://dev.loganalytics.io/) which you probably using now.

**Comment by jsmartt** [comment]
@yossi-y, thanks for providing the link to the API docs. I'm on parent leave at the moment, so won't be able to check it out for a while, but can you confirm that that API is implemented in the Ruby SDK? A simple code example would be awesome if you can do that as well. It's clear that the API exists, but last I checked (July 2020), the Ruby SDK didn't have an updated method to access that API.

**Comment by yossi-y** [comment]
With the deprecation on  workspace search results API, there isn't a way to query workspaces using the Ruby SDK and you will need to call our query API that is on the data plane and not part of Ruby SDK.

Please refer to the API do for reference (https://dev.loganalytics.io/) and let us know if you have any question.
