### ISSUE TITLE
releases in GitHub differ from rubygems release version

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azure-sdk-for-ruby#2707]
Hello,

it looks like the releases on Github https://github.com/Azure/azure-sdk-for-ruby/releases differ from the releases available on rubygems.

According to the GitHub releases azure-sdk 0.22 is latest. Looking at rubygems it's 0.31.
https://rubygems.org/gems/azure_sdk

It just confuses me :-)

Thanks & Best

**Comment by MyronFanQiu** [comment]
@tbugfinder Hi. The latest one is 0.31 at rubygems.

**Comment by tbugfinder** [comment]
I understand, however the github page **https://github.com/Azure/azure-sdk-for-ruby/releases** doesn't refer to that at all.
If that one isn't used or applicable, how about removing it?

**Comment by bim-msft** [comment]
@MyronFanQiu It seems that the release page is out of maintenance, should we continue to update it after each release?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
