### ISSUE TITLE
Unexpected content-encoding generated by asm v0.7.10

### ISSUE THREAD

**Issue by whs-dot-hk** [Azure/azure-sdk-for-ruby#2720]
```ruby
require 'azure'

#https://rubydoc.info/gems/azure/
Azure.storage_account_name = <account name>
Azure.storage_access_key = <storage key>
default_blobs = Azure.blobs

default_blobs.create_container("content-encoding-test", {})

default_blobs.create_block_blob("content-encoding-test", "content-encoding-empty", "Hello world", {content_type: "application/json; charset=utf-8"})
```
an unexpected

ContentEncoding: utf-8

is generated by the code below

https://github.com/Azure/azure-sdk-for-ruby/blob/f9d1dcfc05e980c4452d53b10ea82b26095296f6/lib/azure/blob/blob_service.rb#L1373

**Comment by MyronFanQiu** [comment]
@whs-dot-hk Hello. Thanks! I may need some time to look at this issue. Because all of these sdk are auto-generated from swagger. Usually a manual PR is not acceptable.

**Comment by whs-dot-hk** [comment]
Hi, we came across this issue when trying to use the this library and azure cdn

with content encoding utf-8 the cdn won't serve our content

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
