### ISSUE TITLE
Missing operation begin_create_or_update_async on network_profiles

### ISSUE THREAD

**Issue by lttito** [Azure/azure-sdk-for-ruby#2723]
There is a missing operation, begin_create_or_update_async, on
azure-sdk-for-ruby/management/azure_mgmt_network/lib/2019-08-01/generated/azure_mgmt_network/network_profiles.rb that prevents a gem user to create network profiles for Azure Container Instances

When trying to execute method create_or_update on network_profiles, it says
NoMethodError (undefined method `begin_create_or_update_async' for #<Azure::Network::Mgmt::V2019_08_01::NetworkProfiles:0x0000563ec575df50>)

**Comment by MyronFanQiu** [comment]
@lttito Thanks! It's indeed an error. I need some time to investigate.

**Comment by MyronFanQiu** [comment]
/home/ruby/autorest.ruby/src/azure/Model/MethodRba.cs line 38. Should check whether the value is true or false instead of just checking the existence of the key. @lttito Hello. I think I have found the root casue and I will fix this issue later.

**Comment by MyronFanQiu** [comment]
@lttito I will release new Network SDK today or tomorrow. Thanks.
