### ISSUE TITLE
SharedAccessSignature

### ISSUE THREAD

**Issue by Talha5** [Azure/azure-sdk-for-ruby#2724]
How can one create Shared Access Signature Token for iot hub using this ruby client?

**Comment by MyronFanQiu** [comment]
@Talha5 Hello. I'm not sure whether this can be done through this SDK or not. Looks like it's a data plane operation. Let me ask for service team.

**Comment by Talha5** [comment]
@MyronFanQiu Thanks for responding, This SDK only provides [Operations](https://docs.microsoft.com/en-us/rest/api/iothub/operations), [ResourceProviderCommon](https://docs.microsoft.com/en-us/rest/api/iothub/resourceprovidercommon), [IotHubResource](https://docs.microsoft.com/en-us/rest/api/iothub/iothubresource) and [Cetificates](https://docs.microsoft.com/en-us/rest/api/iothub/certificates) till this date. One of the most important part thats left is Services.

**Comment by MyronFanQiu** [comment]
@Talha5 This SDK is used for Azure resource management. Especially for IoT, I'm familiar with the service whether it's related with resource management or not. So we can wait for @iluican  and @jlian
