### ISSUE TITLE
Possible incorrect constant error in KeyVaultClient

### ISSUE THREAD

**Issue by scarfacedeb** [Azure/azure-sdk-for-ruby#2740]
I'm trying to create new key in my Azure KeyVault and I keep getting the same NameError:

```
> client = Azure::KeyVault::Profiles::Latest::Client.new(options)
> client.create_key("https://secret.vault.azure.net/", "Testkey", "RSA-HSM")
NameError: uninitialized constant Azure::KeyVault::V7_0::KeyVaultClient::KeyCreateParameters
```

It's coming from [KeyVaultClient#create_key_async](https://github.com/Azure/azure-sdk-for-ruby/blob/master/data/azure_key_vault/lib/7.0/generated/azure_key_vault/key_vault_client.rb#L216). 

I think that there're a couple of errors in that code: incorrect constant and camelCased method used, instead of snake_case.

Here's a quick fix that I applied to make it work again:

```
parameters = Azure::KeyVault::V7_0::Models::KeyCreateParameters.new
...
parameters.key_attributes = key_attributes
```

Furthermore, there're the same issues with [import_key_async](https://github.com/Azure/azure-sdk-for-ruby/blob/master/data/azure_key_vault/lib/7.0/generated/azure_key_vault/key_vault_client.rb#L362) and [update_key_async](https://github.com/Azure/azure-sdk-for-ruby/blob/master/data/azure_key_vault/lib/7.0/generated/azure_key_vault/key_vault_client.rb#L618).

**Comment by scarfacedeb** [comment]
I tested `KeyVaultClient#encrypt` and it doesn't work either.

First of all, it has the same [constant error](https://github.com/Azure/azure-sdk-for-ruby/blob/master/data/azure_key_vault/lib/7.0/generated/azure_key_vault/key_vault_client.rb#L1404) as the earlier methods.

Next, its [KeyOperationsParameters.mapper](https://github.com/Azure/azure-sdk-for-ruby/blob/master/data/azure_key_vault/lib/7.0/generated/azure_key_vault/models/key_operations_parameters.rb#L52) uses `Base64Url` type for the `value` parameter that isn't supported by [MsRest::Serialization#serialize](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest/lib/ms_rest/serialization.rb#L232).

Am I doing something wrong? Is Key Vault SDK just not finished yet?

**Comment by bim-msft** [comment]
@scarfacedeb Thanks for your feedback, I'll look into this next weekday.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
