### ISSUE TITLE
Azure ServiceBus Documentation

### ISSUE THREAD

**Issue by neilcarv** [Azure/azure-sdk-for-ruby#2745]
Hi,

I have followed the steps on [Azure-Service-Bus](https://docs.microsoft.com/en-gb/azure/service-bus-messaging/service-bus-ruby-how-to-use-queues#configure-your-application-to-use-service-bus) and everything is working fine. 

This documentation states to install azure using` gem install azure`. However, when I look at the last time the gem was updated on [azure-ruby-gems](https://rubygems.org/gems/azure), it was v0.7.10 on September 07, 2017.  I can see that various modules of this project is in active development though. So, could someone please help me understand if this documentation is outdated for Azure Service Bus(for queues) or point me towards some new documentation that I could use using (azure-sdk gem).

Thanks a lot in advance for helping me with this query.

Regards,
Neil

**Comment by MyronFanQiu** [comment]
@neilcarv Hello. Could you try `gem install azure_mgmt_service_bus` if you want to manage your service bus resource?

**Comment by axisc** [comment]
@neilcarv - the documentation is not out of date - the ruby SDK is quite dated for Service Bus.  [Here](https://rubygems.org/search?utf8=%E2%9C%93&query=azure) are all the Azure related gems.
