### ISSUE TITLE
No abort_copy_blob method in blob_service.rb

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-sdk-for-ruby#275]
From the document of the method `copy_blob`, a pending copy can be aborted by `abort_copy_blob`.
https://github.com/Azure/azure-sdk-for-ruby/blob/master/service_management/azure/lib/azure/blob/blob_service.rb#L1183
But, there is no `abort_copy_blob` method in blob_service.rb.

**Comment by veronicagg** [comment]
@yaxia does storage preview gem support this operation?

**Comment by yaxia** [comment]
It is supported in the azure-storage gem.

**Comment by veronicagg** [comment]
Please reopen in azure-storage repo if you see any issues with this.
