### ISSUE TITLE
Is there a way to dissociate public IP address from NIC through SDK?

### ISSUE THREAD

**Issue by wjia7** [Azure/azure-sdk-for-ruby#2750]
Hi,

I am looking for a way to dissociate public IP addresses from my nic that is associated with a VM that is part of a scale set. There is ways to do it through azure portal and CLI (https://docs.microsoft.com/en-us/azure/virtual-network/remove-public-ip-address-vm). My question is that is there a way to do it through SDK? 

Thanks

**Comment by MyronFanQiu** [comment]
should be able to do it. You can just set the corresponding field to `None` and call client.create_or_update.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
