### ISSUE TITLE
CRP behavior for the Imperative CreateVM calls from ruby script

### ISSUE THREAD

**Issue by nickzhums** [Azure/azure-sdk-for-ruby#2753]
Customer encounters an issue where provisioning large numbers of VMs from their Ruby script can lead to unexpected result

**Comment by yonzhan** [comment]
add to S165.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
