### ISSUE TITLE
Where is the documentation for the Key Vault gem?

### ISSUE THREAD

**Issue by jrmhaig** [Azure/azure-sdk-for-ruby#2760]
The link in the README to 'Key Vault' goes to the [Rubygems page.](https://rubygems.org/gems/azure_mgmt_key_vault) The documentation page there links to the [Microsoft Azure develop page](https://azure.microsoft.com/en-us/develop/ruby/) that shows how to install the `azure` gem and provides a link to 'Read the full Azure SDK for Ruby documentation'. This leads back to the [README file here.](https://github.com/Azure/azure-sdk-for-ruby/blob/master/README.md)

Where can I find the actual documentation?

I did find this example:

  https://github.com/Azure-Samples/key-vault-ruby-manage-vaults

but it only works up to version 0.14. From 0.15 onwards I get:

```bash
example.rb:32:in `run_example': uninitialized constant Azure::ARM (NameError)
Did you mean?  ARGV
```

**Comment by MyronFanQiu** [comment]
Based on my knowledge, we don't have enough docs for ruby sdk. Sorry about that.

**Comment by jrmhaig** [comment]
Thanks @MyronFanQiu 

I'll use the [`azure-key-vault`](https://rubygems.org/gems/azure-key-vault) gem instead. It is an unofficial, 3rd-party gem but it does what I need for the moment.

**Comment by manali14** [comment]
Do we have any references for the Documentation? How are we supposed to get/put secrets to keyvault?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
