### ISSUE TITLE
What does this middleware option do?

### ISSUE THREAD

**Issue by kac460** [Azure/azure-sdk-for-ruby#2765]
I'm new to Azure, and it's not clear to me what the `middlewares` option in the `VirtualMachines` class's `begin_run_command_async` method is for. https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/2019-07-01/generated/azure_mgmt_compute/virtual_machines.rb#L2559 Could someone explain it? In particular what is the significance of each of the items in that array?

**Comment by nickzhums** [comment]
@MyronFanQiu  could you take a look? thanks

@kac460 curious why you are using Ruby SDK ? :)

**Comment by MyronFanQiu** [comment]
@kac460 Hi. May I know the motivation behind this issue? middlewares is used to control the retry times for a request in case network issue. https://github.com/Azure/azure-sdk-for-ruby/blob/373a9a0fae0de9bbe4d3948c99a25d6656bef14b/runtime/ms_rest/lib/ms_rest/retry_policy_middleware.rb#L9 this line should help explain. It's a basic logic in ms rest and should not be exposed to user directly.

**Comment by allenjzhang** [comment]
Closing this as information provided to the question. Please reopen if you still have follow up questions.
