### ISSUE TITLE
Can I / do I need to pass the scope?

### ISSUE THREAD

**Issue by idrozd** [Azure/azure-sdk-for-ruby#2776]
Hello, 
all the best to you!

https://github.com/Azure/azure-sdk-for-ruby/blob/373a9a0fae0de9bbe4d3948c99a25d6656bef14b/runtime/ms_rest_azure/spec/application_token_provider_spec.rb#L12

So I'm trying to embed powerbi;
When I get the authentication token, do I need to pass scope also?
Don't see it in the code.

But [this python example](https://github.com/microsoft/PowerBI-Developer-Samples/blob/master/Python/App%20Owns%20Data/powerbiembedding/aadservice.py) 
does pass the scope and I wonder if I'm failing (403) to query[ this api endpoint ](https://docs.microsoft.com/en-us/rest/api/power-bi/reports/getreportingroup)due to the scope missing for requested token?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
