### ISSUE TITLE
Azure Gov environment uses an out-of-date default for the active directory endpoint url

### ISSUE THREAD

**Issue by ystros** [Azure/azure-sdk-for-ruby#2781]
The AzureUsGovernment environment embedded within the most recent version of the `ms_rest_azure` gem is currently set to `https://login-us.microsoftonline.com/`

https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/azure_environment.rb#L133

However, per this article, the Azure Gov environment should now be using `https://login.microsoftonline.us` instead:
https://devblogs.microsoft.com/azuregov/azure-government-aad-authority-endpoint-update/

This agrees with the Azure Government developer documentation on endpoint mapping (see the Active Directory Endpoint and Authority entry):
https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide#endpoint-mapping

It appears that the old `https://login-us.microsoftonline.com/` endpoint has finally been deprecated within the Azure Gov environment. Within the last week multiple customers have been reporting that code using the `azure_mgmt_compute` gem (which we believe uses the `ms_rest_azure` gem internally) has starting failing when connecting.

Would it be possible to get the default active directory endpoint updated to the new `https://login.microsoftonline.us` URL per Azure Gov documentation?

**Comment by MyronFanQiu** [comment]
@ystros I would take a look. Thanks for reporting it.

**Comment by jiasli** [comment]
Azure CLI never used `https://login-us.microsoftonline.com/`:

```
git log -p --all -S 'login-us.microsoftonline.com'
<Empty>
```

`https://login.microsoftonline.com` was changed to `https://login.microsoftonline.us` in https://github.com/Azure/azure-cli/pull/4877

```diff
git log -p --all -S 'login.microsoftonline.us' 
commit 06cd9c2160c2f792a3af76f71fb55368c92cf0d6
Author: Bernarldo Ellis <31703178+bernie-msft@users.noreply.github.com>
Date:   Wed Nov 15 16:09:06 2017 -0500

    Modified AzureUSGov Endpoint to .US (#4877)

-        active_directory='https://login.microsoftonline.com',
+        active_directory='https://login.microsoftonline.us',
```

We should make Ruby SDK use `https://login.microsoftonline.us` as well.

FYI: found `git log` from https://stackoverflow.com/a/44711340/2199657
