### ISSUE TITLE
ms_rest_azure 0.12.0 is breaking run for storage cache

### ISSUE THREAD

**Issue by rebecca-makar** [Azure/azure-sdk-for-ruby#2785]
Hi - in automation testing, we use the ruby sdk .
Normally do:
    sudo gem install azure_mgmt_resources
    sudo gem install azure_mgmt_network
    sudo gem install ms_rest_azure
    clone repo ---- make update to our service .rb file to allow mock since it is for testing purposes, 
    sudo rake install
    ruby test.rb 

I am now getting this error below:
```
/usr/local/lib/site_ruby/2.3.0/rubygems/specification.rb:2243:in `raise_if_conflicts': Unable to activate azure_mgmt_storagecache-0.18.0, because ms_rest_azure-0.11.2 conflicts with ms_rest_azure (~> 0.12.0) (Gem::ConflictError)
	from /usr/local/lib/site_ruby/2.3.0/rubygems/specification.rb:1371:in `activate'
	from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:217:in `rescue in try_activate'
	from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:210:in `try_activate'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:178:in `require'
	from sdk_mock.rb:6:in `<main>'
```

This change https://github.com/Azure/azure-sdk-for-ruby/pull/2784 I think is causing the breaking change.

Since in documentation it says to do a sudo gem install azure_mgmt_resources  and the latest version of that still is installing ms_rest_azure 0.11.2
I think this may effect most of the ruby sdks since the version change for ms_rest_azure seems to be in most repos. 

```
sudo gem install azure_mgmt_resources
Successfully installed unf_ext-0.0.7.2
Successfully installed multipart-post-2.1.1
Successfully installed faraday-1.0.1
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.20190701
Successfully installed http-cookie-1.0.3
Successfully installed faraday-cookie_jar-0.0.6
Successfully installed timeliness-0.3.10
Successfully installed ms_rest-0.7.6
Successfully installed ms_rest_azure-0.11.2        ----------------------------------Install here
Successfully installed azure_mgmt_resources-0.17.8
Parsing documentation for concurrent-ruby-1.1.6
Installing ri documentation for concurrent-ruby-1.1.6
Parsing documentation for unf_ext-0.0.7.2
Installing ri documentation for unf_ext-0.0.7.2
Parsing documentation for multipart-post-2.1.1
Installing ri documentation for multipart-post-2.1.1
Parsing documentation for faraday-1.0.1
Installing ri documentation for faraday-1.0.1
Parsing documentation for unf-0.1.4
Installing ri documentation for unf-0.1.4
Parsing documentation for domain_name-0.5.20190701
Installing ri documentation for domain_name-0.5.20190701
Parsing documentation for http-cookie-1.0.3
Installing ri documentation for http-cookie-1.0.3
Parsing documentation for faraday-cookie_jar-0.0.6
Installing ri documentation for faraday-cookie_jar-0.0.6
Parsing documentation for timeliness-0.3.10
```

I did try uninstalling sudo gem uninstall ms_rest_azure -v 0.11.2 but it is a dependency and failed to uninstall.

**Comment by MyronFanQiu** [comment]
Is there any reason why you need to install `ms_rest_azure` directly? Recently a new ms_rest_azure 0.12.0 package was released. Even though we have done the code change in this repo, but we didn't release any new package relying on 0.12.0 yet. That's why you saw such conflicts.

**Comment by rebecca-makar** [comment]
@MyronFanQiu Realizing it is effecting me since I am not doing a gem install for storage cache, but rather doing a rake install based off of the repo in the storage cache which was changed and needed the new file. I am trying to add a sed in the pipelines to change my fresh clone of the repo in the build pipeline back to old version until all packages are released.

**Comment by puma25ca** [comment]
@MyronFanQiu jumping on this bandwagon. I realize Ruby 2.5 isn't on the supported list yet, but this is affecting me too as ms_rest_azure 0.12.0 unpins the unf_ext dependency (from 0.0.7.2) allowing the other gems that call for latest 0.0.7.6.
Is there a timeframe for releasing new packages using the latest ms_rest_azure?

**Comment by MyronFanQiu** [comment]
> @MyronFanQiu jumping on this bandwagon. I realize Ruby 2.5 isn't on the supported list yet, but this is affecting me too as ms_rest_azure 0.12.0 unpins the unf_ext dependency (from 0.0.7.2) allowing the other gems that call for latest 0.0.7.6.
> Is there a timeframe for releasing new packages using the latest ms_rest_azure?

They should be released within this week.

**Comment by MyronFanQiu** [comment]
new sdks has been released. Please have a try.
