### ISSUE TITLE
Azure connection failing while using with test-kitchen kitchen-azurerm for Azureusgovernment cloud environment.

### ISSUE THREAD

**Issue by Vijay8888** [Azure/azure-sdk-for-ruby#2789]
Hi,

We are getting error while testing chef cookbook using kitchen-azurerm for azureusgovernment.

We have configured everything as per the documentation and declared environment as azureusgovernment. Error as below.

Couldn’t connect to azure please check tenant I’d, client I’d, client secret.

Could someone please help on this issue.

Thanks 
Vijay

**Comment by MyronFanQiu** [comment]
@Vijay8888 Hi. Could you open this issue through support ticket since it's related with aad and personal data. Based on the error message, it might be something wrong with the tenant id or client secret.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
