### ISSUE TITLE
Azure Database for Postgres/MySQL/MariaDB SDK support

### ISSUE THREAD

**Issue by baarkerlounger** [Azure/azure-sdk-for-ruby#2791]
Currently there is [azure_mgmt_sql](https://rubygems.org/gems/azure_mgmt_sql) gem for [SQL REST API](https://docs.microsoft.com/en-us/rest/api/sql/).

It doesn't appear there are equivalents for [MariaDB REST API](https://docs.microsoft.com/en-us/rest/api/mariadb/), [MySQL REST API](https://docs.microsoft.com/en-us/rest/api/mysql/) and [Postgres REST API](https://docs.microsoft.com/en-us/rest/api/postgres/).

Are gems for these planned?

**Comment by MyronFanQiu** [comment]
Hi. Ruby SDK is released according to the request of service team. I don't know the service's plan. Let me add service attention. Meanwhile, ruby sdk is going to be deprecated. If possible, please use other popular language sdks like python/java/c#/ts.

**Comment by baarkerlounger** [comment]
@MyronFanQiu is there any announcement you could link that the SDK is being deprecated and when?

**Comment by nickzhums** [comment]
> @MyronFanQiu is there any announcement you could link that the SDK is being deprecated and when?

Hi there is no official annoucement yet but this is the direction. The development focus has shifted to delivering a new set of Azure Management SDK that follows unified guidelines that should provide better developer experience. Recently, the first set of those new libraries are already released, please refer to here:
https://azure.github.io/azure-sdk/releases/2020-07/java.html
https://azure.github.io/azure-sdk/releases/2020-07/python.html
https://azure.github.io/azure-sdk/releases/2020-07/dotnet.html

**Comment by baarkerlounger** [comment]
Right and will a new Ruby library eventually also be released or is support for Ruby language likely to be dropped altogether?

**Comment by nickzhums** [comment]
> Right and will a new Ruby library eventually also be released or is support for Ruby language likely to be dropped altogether?

Currently there is no plan for Ruby because of the usage is relatively low, but if there is strong evidence we'll re-consider the plan

**Comment by ajlam** [comment]
@baarkerlounger - at the moment, we do not have plans to support the Ruby SDK for Azure DB for MySQL, MariaDB, and PG services.
