### ISSUE TITLE
Edit VM tags -> Location header is missing from long running operation

### ISSUE THREAD

**Issue by ross** [Azure/azure-sdk-for-ruby#2795]
Was looking to update the tags on a virtual_machine and have code that roughly looks like the following:

```ruby
          update = ::Azure::Compute::Profiles::Latest::Mgmt::Models::VirtualMachineUpdate.new
          update.tags = new_tags
          compute_client.virtual_machines.update(resource_group, instance.hostname, update)
```

The changes in tags are made as expected, but the call hangs for around 30s before returning:

```
{ "message": "Location header is missing from long running operation", "request": null, "response": null }
```

After a bunch of digging, debugging, searching, and reading here's what I've found/think:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations talks about async requests and seems to indicate that a status of 201 or 202 will be returned and that either `Azure-AsyncOperation` or `Location` response header will be included to tell the caller how to check on the status. The following is the status code and headers from the initial call, which is 200 and neither of the headers.

```
{:status=>200,
 :headers=>
  {"cache-control"=>"no-cache",
   "pragma"=>"no-cache",
   "transfer-encoding"=>"chunked",
   "content-type"=>"application/json; charset=utf-8",
   "expires"=>"-1",
   "vary"=>"Accept-Encoding",
   "strict-transport-security"=>"max-age=31536000; includeSubDomains",
   "x-ms-request-id"=>"xxx,
   "x-ms-ratelimit-remaining-subscription-writes"=>"1199",
   "server"=>"Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0",
   "x-ms-correlation-request-id"=>"xxx",
   "x-ms-routing-request-id"=> "xxx",
   "x-content-type-options"=>"nosniff",
   "date"=>"Wed, 05 Aug 2020 22:36:52 GMT",
   "connection"=>"close"}}
```

This seems to indicate that it's not an async call which lines up as by the point this response has been returned the tags on the VM have been updated. The library sites for another 20s+ before throwing the above error.

Is is possible that the vm update method is sometimes sync and sometimes async and the client library is assuming it's always async? I dug around a bit in the code but didn't figure out if the async code paths handle that case.

I found a NodeJS repos reporting an issue that sounds somewhat similar, editing tags gets that message, https://github.com/mjyeaney/NodeJS-Azure-SDK-Issues.

Any thoughts/suggestions here?

**Comment by MyronFanQiu** [comment]
According to swagger spec, it should be a long running operation and should return 201/202 first instead of 200. 

https://github.com/Azure/azure-rest-api-specs/blob/9ea4dc2d936d8eaae61d507242771b1d6447a96e/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L2774

To unblock you quickly, `create_or_update` method should also be able to update tags.

https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/2019-12-01/generated/azure_mgmt_compute/virtual_machines.rb#L181

https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/2019-12-01/generated/azure_mgmt_compute/models/virtual_machine.rb

**Comment by ross** [comment]
> To unblock you quickly, `create_or_update` method should also be able to update tags.

👍, will look into this in the morning. Thanks for the quick response.

**Comment by axayjo** [comment]
@ross let us know if create_or_update works as expected. In the meantime, @avirishuv can you please take a look at the update issue?

**Comment by ross** [comment]
> To unblock you quickly, `create_or_update` method should also be able to update tags.

That does seem to work and my debugging print shows that its call does have the async header, though it's still al 200 which doesn't line up [with what the doc saya](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations). 

```
{:status=>200,
 :headers=>
  {"cache-control"=>"no-cache",
   "pragma"=>"no-cache",
   "transfer-encoding"=>"chunked",
   "content-type"=>"application/json; charset=utf-8",
   "expires"=>"-1",
   "vary"=>"Accept-Encoding",
   "azure-asyncoperation"=> "<URL>",
...
```

The flow is quite a bit slower than the `update` version, but that should be OK as a work-around.

**Comment by avirishuv** [comment]
@ross For the API version 2019-07-01 or later, if the Update VM request is updating only the VM tags, then the VM will updated with the tags and a 200 response will be returned, without any async headers.

**Comment by ross** [comment]
> @ross For the API version 2019-07-01 or later, if the Update VM request is updating only the VM tags, then the VM will updated with the tags and a 200 response will be returned, without any async headers.

👍 that's kind of what it seemed like was happening. Depending on the details of the request it's sometimes sync and other times async.

**Comment by avirishuv** [comment]
@ross if no other open questions, can we close the issue?

**Comment by ross** [comment]
Does the client library handle the sync version when just changing tags and async otherwise? I worked around it by using a different API, but seems like this issue is still valid unless the client library now handles the original call's varying modes of operation.

**Comment by avirishuv** [comment]
Yes, it depends upon the request - when the request is for changing tags, then the async headers are not returned.

**Comment by ross** [comment]
:cool:, didn't see a PR linked up to the issue or anything so wasn't sure if it'd be addressed. If it has then this can be closed.

**Comment by anth1y** [comment]
Hey Folks, we recently upgraded our azure_mgmt_compute gem to 0.22.0 
and tried to use the same code @ross mentioned earlier:

```
  update = ::Azure::Compute::Profiles::Latest::Mgmt::Models::VirtualMachineUpdate.new
  update.tags = new
  compute_client.virtual_machines.update(resource_group, instance.hostname, update, custom_headers: {"Location" => site.region})
```

while the tags are being updated we are still seeing the call hang around for about 30s

```
{ "message": "Location header is missing from long running operation", "request": null, "response": null }
```

We're wondering if we are doing something wrong to implement this ?
