### ISSUE TITLE
Remove encoding lines from generated ruby code

### ISSUE THREAD

**Issue by tas50** [Azure/azure-sdk-for-ruby#2796]
Each of the files in this SDK starts with this encoding line:

```
# encoding: utf-8
```

Since Ruby 2.0 utf-8 has been the default so this line doesn't actually do anything. Since there are 26,356 files in this repo that extra encoding comment adds 26,356 lines to the codebase that do nothing.

You can use the RuboCop `Style/Encoding` cop to remove these lines from the existing files automatically.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
