### ISSUE TITLE
Unable to get the latest secret from KeyVault without providing the secret version

### ISSUE THREAD

**Issue by manali14** [Azure/azure-sdk-for-ruby#2799]
There is no support for getting the latest version of the secret from Key Vault. In order to get the version, we again have to hit versions API which seems broken 

API: 
```
keyvault_client.get_secret_versions("https://test-manali.vault.azure.net","name")
```
Error: 
```
NoMethodError: undefined method `get_secret_versions_as_lazy_as_lazy' for #<Azure::KeyVault::V7_0::KeyVaultClient:0x00007f89e65c1620>
Did you mean?  get_secret_versions_as_lazy_async
               get_secret_versions_as_lazy
from gems/ruby-2.7.1/gems/azure_key_vault-0.17.4/lib/7.0/generated/azure_key_vault/key_vault_client.rb:11370:in `get_secret_versions_as_lazy'
```

Similar response for get_secret_versions_as_lazy 

 keyvault_client.get_secret_versions_with_http_info seems to be responding but in case you have multiple versions of your secret(In my case, 94), it didn't send me the current version in response. How do I know what's the latest version of my secret?

**Comment by MyronFanQiu** [comment]
may I know which package you are using?

**Comment by manali14** [comment]
@MyronFanQiu I am using the KeyVault Package.

Client - Azure::KeyVault::V7_0::KeyVaultClient

**Comment by MyronFanQiu** [comment]
@manali14 AFAIK, this package is not maintained by us. This repo is used for Azure Management SDK. @bim-msft Could you help route this issue to correct person?

**Comment by bim-msft** [comment]
I think @heaths is the right contact person for KeyVault SDK.

**Comment by manali14** [comment]
@heaths can you confirm if this is something being worked upon? Or planned for later releases?

**Comment by heaths** [comment]
My team doesn't own this SDK. Adding @nickzhums from the team that does.

**Comment by yonzhan** [comment]
We will plan this and ship this around end of September.

**Comment by nickzhums** [comment]
@manali14 Ruby SDK is on a deprecation path in the future (likely to be announced in Feb next year), please plan your projects accordingly. The alternatives will be using REST API and SDKs of other languages. Thank you

**Comment by MyronFanQiu** [comment]
@manali14 we have released a new version. Please have a try.
https://rubygems.org/gems/azure_key_vault/versions/0.18.0

**Comment by manali14** [comment]
As suggested by @nickzhums, we have removed our dependency on the gem and are relying now on Azure Rest APIs.

**Comment by MyronFanQiu** [comment]
close this issue since it's solved.
