### ISSUE TITLE
Add 2020-01-01 profile for azure_mgmt_subscriptions

### ISSUE THREAD

**Issue by seandilda** [Azure/azure-sdk-for-ruby#2800]
azure_mgmt_subscriptions currently has 2019-11-01 as the latest profile, but API docs are showing sample from a 2020-01-01 API version.

Can we get the the newer API included in the gem? In particular, I'm interested in getting the subscription tags while listing subscriptions.

**Comment by nickzhums** [comment]
@seandilda
Ruby SDK will be deprecated pretty soon - we will be in maintenance mode. For future projects we suggest using Java, .NET and Python SDKs

If you still need to use Ruby, we would suggest directly using REST API in Ruby

In the mean-time, we will evaluate if we can do a release for this. cc @kairu-ms  for awareness

Let us know if you have other questions

**Comment by seandilda** [comment]
Thanks for the heads up!

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
