### ISSUE TITLE
issues with Azure container registry gem

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azure-sdk-for-ruby#2804]
Hi,

could you provide an example on how to get / search / list an Azure container registry within a given resource group?

Thanks

**Comment by MyronFanQiu** [comment]
Maybe you can check this [file](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_container_registry/lib/2019-05-01/generated/azure_mgmt_container_registry/operations.rb) as an example.

**Comment by tbugfinder** [comment]
I have the impression it's lacking methods.
The Azure Python seems to be more detailed.
https://docs.microsoft.com/en-us/python/api/azure-mgmt-containerregistry/azure.mgmt.containerregistry.v2019_04_01.operations.registriesoperations?view=azure-python

Ruby:
https://www.rubydoc.info/gems/azure_mgmt_container_registry/0.18.2/Azure/ContainerRegistry/Mgmt/V2017_10_01/Registries

latest:
https://www.rubydoc.info/gems/azure_mgmt_container_registry/0.18.2/Azure/ContainerRegistry/Mgmt/V2019_04_01/Registries

**Comment by tbugfinder** [comment]
I'm also wondering about this difference.
```
### Compute
irb(main):074:0> Azure::Compute::Profiles::V2018_03_01::Mgmt::Client
=> Azure::Compute::Profiles::V2018_03_01::Mgmt::Client
irb(main):075:0>

## ContainerRegistry
## Tried different versions though, not hitting the appropriate, yet.
irb(main):081:0> Azure::ContainerRegistry::Profiles::V2017_10_01::Mgmt::Client
Traceback (most recent call last):
       16: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
       15: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
       14: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
       13: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
       12: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
       11: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
       10: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        9: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
        8: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
        7: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
        6: from /test/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
        5: from /home/user/vendor/bundle/ruby/2.6.0/bin/irb:23:in `<top (required)>'
        4: from /home/user/vendor/bundle/ruby/2.6.0/bin/irb:23:in `load'
        3: from /home/user/vendor/bundle/ruby/2.6.0/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
        2: from (irb):80
        1: from (irb):81:in `rescue in irb_binding'
NameError (uninitialized constant Azure::ContainerRegistry::Profiles::V2017_10_01)
irb(main):082:0>

```

**Comment by tbugfinder** [comment]
Hi @MyronFanQiu 
sorry to bother you once more. Do you have any clue what's wrong here?

**Comment by tbugfinder** [comment]
I did some search within the repo azure-rest-api-specs.
It looks like not all versions (in API specs) have the method I'm looking for. Some versions in between lack it.
https://github.com/Azure/azure-rest-api-specs/search?q=%22lists+all+the+container+registries+under+the+specified+resource%22 
As the latest reference within this `Azure::ContainerRegistry` in azure-sdk-for-ruby doesn't point to version 2019-05-01 nor uses 2019-12-01-preview the method isn't there.

Would you kindly update the ruby-sdk matching current API specs?

**Comment by tbugfinder** [comment]
Is it recommended to point latest to a non-stable version?

**Comment by tbugfinder** [comment]
Anybody could rebuild the code for Azure::ContainerRegistry maybe including updated API versions?
I'm also wondering which patched autorest.ruby version you are using or which options are being used.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
