### ISSUE TITLE
Retrieve public pricing for Vm's

### ISSUE THREAD

**Issue by AndreiMGagiu** [Azure/azure-sdk-for-ruby#2805]
I was trying to find a way using the sdk to fetch public pricing for all vm families, not just ones present in my subscription id.

Is there such thing possible?

Thanks

**Comment by nickzhums** [comment]
@kairu-ms could you see if this is possible?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
