### ISSUE TITLE
README Developer’s guide to auth with Azure Resource Manager API - Dead end.

### ISSUE THREAD

**Issue by stonefield** [Azure/azure-sdk-for-ruby#2807]
The link on README.md is pointing to a non-existing page.

```
wget -O- http://aka.ms/arm-auth-dev-guide
--2020-10-08 16:45:45--  http://aka.ms/arm-auth-dev-guide
Resolving aka.ms (aka.ms)... 23.38.17.26
Connecting to aka.ms (aka.ms)|23.38.17.26|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.dushyantgill.com/blog/2015/05/23/developers-guide-to-auth-with-azure-resource-manager-api/ [following]
--2020-10-08 16:45:45--  http://www.dushyantgill.com/blog/2015/05/23/developers-guide-to-auth-with-azure-resource-manager-api/
Resolving www.dushyantgill.com (www.dushyantgill.com)... 40.121.212.165
Connecting to www.dushyantgill.com (www.dushyantgill.com)|40.121.212.165|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.dushyantgill.com/blog/2015/05/23/developers-guide-to-auth-with-azure-resource-manager-api/ [following]
--2020-10-08 16:45:46--  https://www.dushyantgill.com/blog/2015/05/23/developers-guide-to-auth-with-azure-resource-manager-api/
Connecting to www.dushyantgill.com (www.dushyantgill.com)|40.121.212.165|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-08 16:45:48 ERROR 404: Not Found.
```

**Comment by nickzhums** [comment]
Hi @stonefield  sorry the doc was causing you an issue, we will take a look at this

FYI Ruby SDK will be deprecated pretty soon - for future projects we suggest using Java, .NET and Python SDKs

If you still need to use Ruby, we would suggest directly using REST API in Ruby

Let us know if you have other questions

**Comment by RossBarnie** [comment]
@nickzhums Do you have a specific date for the Ruby SDK deprecation in mind? If so it would be very useful to make this prominent across all relevant READMEs, and perhaps a post-install message. There are over 80k downloads for the version released in December so clearly people are still relying on this.

**Comment by nickzhums** [comment]
Yes, we are planning to announce deprecation in late Feb. We will definitely add deprecation message to all places, let us know if we've missed any places once the announcement comes out

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
