### ISSUE TITLE
Any document/example for Service Bus

### ISSUE THREAD

**Issue by JonesChi** [Azure/azure-sdk-for-ruby#2811]
It seems the example on https://github.com/Azure/azure-sdk-for-ruby/tree/asm#topics is out of date.

However I found a new gem (**azure_mgmt_service_bus**) for service bus, but I can't find any document or example for how to create topics, send messages to topics, and receive messages from subscription. 

Should I use **azure_mgmt_service_bus**? Or what SDK should I use for Service Bus? Thanks.

**Comment by nickzhums** [comment]
Hi Jones
Ruby SDK will be deprecated pretty soon - we suggest Python SDK equivalent here

https://pypi.org/project/azure-mgmt-servicebus/

If you still need to use Ruby, we would suggest directly using REST API in Ruby 

Let us know if you have other questions

**Comment by JonesChi** [comment]
@nickzhums 
Thanks for the information. I currently works on integrating Service Bus with our RoR project, so I can not use Python SDK, will try REST API.

One more question, Will the Azure Storage Ruby SDK (https://github.com/Azure/azure-storage-ruby) keep maintaining? Or it will be deprecated?
Thanks.

**Comment by nickzhums** [comment]
@JonesChi  yes the storage SDK will still be maintained and not affected by deprecation, are you directly creating resources within your application?

**Comment by JonesChi** [comment]
@nickzhums yes, I need to create topics of Service Bus and send/receive messages to/from the topics on my application.

**Comment by cba7** [comment]
@azure @microsoft @azure-sdk @msftbot really guys, how can MS being dropping support for Ruby. Is MS seriously so disinterested in having predominately UNIX developers using Azure...?

It seems like you are just pushing developers to AWS or GCP.

No where in your Ruby documentation, written no more than 5 months prior, do you state you are dropping support of your Ruby SDK.

Suggesting a developer "swap" to another programming language is just quite rude really.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
