### ISSUE TITLE
SessionId is being mapped as SessionID.

### ISSUE THREAD

**Issue by jlimaESB** [Azure/azure-sdk-for-ruby#2815]
Hi, trying to use the Gem azure to send messages, but the message is going to Deadletter queue.

After some investigation, I think the problem is that sessionId is arriving null there. 

I open the code and I saw that the BrokeredMessageSerializer is mapping session_id to SessionID (uppercase D). 

When I change that, to SessionId, it worked.

BrokerProperties => {"ContentType":"application/json","CorrelationId":"..,",**"SessionID"**:"2d33aeba-e0b2-4134-8e13-ceec4424d5a7","MessageId":"d324f931-a295-40a4-bbdc-f72ace5b843d","Label":"..."}

gem 'azure', '~> 0.7.10'

here 

module Azure
  module ServiceBus
    # BrokeredMessageSerializer
    class BrokeredMessageSerializer
      PROPERTIES = {
        'ContentType'             => 'content_type',
        'CorrelationId'           => 'correlation_id',
        **'SessionID'               => 'session_id',**

and 

      def self.get_from_http_response(response)
        props = JSON.parse(response.headers['brokerproperties'])
        BrokeredMessage.new(response.body) do |m|
          loc_header = response.headers['location']
          m.location = URI(loc_header) unless loc_header.nil?
          m.content_type = response.headers['content-type']

          # String based properties
          m.lock_token = props['LockToken']
          m.message_id = props['MessageId']
          m.label = props['Label']
          m.to = props['To']
          **m.session_id = props['SessionID']**

**Comment by kairu-ms** [comment]
Hi @jlimaESB  'azure' gem is out of date. You should use [azure_mgmt_service_bus](https://rubygems.org/gems/azure_mgmt_service_bus) or [azure_sdk](https://rubygems.org/gems/azure_sdk) instead.

**Comment by kairu-ms** [comment]
BTW, Ruby SDK will be deprecated in plan in next year. Here is the [doc](https://github.com/Azure/azure-sdk-for-ruby/blob/3784068643d5a35e031617d7e31913f02986c62c/docs/README.md) that may help your transfer to REST API usage in Ruby.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
