### ISSUE TITLE
KeyVault get_*_as_lazy trying to .get_all_items from objects which don't support it

### ISSUE THREAD

**Issue by jstange** [Azure/azure-sdk-for-ruby#2830]
Related to #2826, KeyVault gem (`azure_key_vault-0.18.1`)

The `_async` methods called by things like `get_certificates_as_lazy` return a `Promise`, which doesn't know what `get_all_items` is:

```
    def get_certificates_as_lazy(vault_base_url, maxresults:nil, include_pending:nil, custom_headers:nil)
      first_page = get_certificates_as_lazy_async(vault_base_url, maxresults:maxresults, include_pending:include_pending, custom_headers:custom_headers)
      first_page.get_all_items
    end
```

```
NoMethodError: undefined method `get_all_items' for #<Concurrent::Promise:0x000000000a329a88>
["/var/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/azure_key_vault-0.18.1/lib/7.1/generated/azure_key_vault/key_vault_client.rb:11125:in `get_certificates_as_lazy'",
 "/var/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/azure_key_vault-0.18.1/lib/7.1/generated/azure_key_vault/key_vault_client.rb:131:in `get_certificates'"
 ```
 
You can append a `value!` to resolve the promise, which is what I did to get around this enough to validate my own code, but I don't know whether or not synchronously resolving it in these `get_foo_as_lazy` methods is the way it's intended to work.
 
In any case, if I do that, the live result doesn't respond to `get_all_items` either:
 
 ```
NoMethodError: undefined method `get_all_items' for #<MsRestAzure::AzureOperationResponse:0x0000000006d777c8>
 ```

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
