### ISSUE TITLE
looking for ruby replacement of azure-sdk-for-ruby

### ISSUE THREAD

**Issue by tbugfinder** [Azure/azure-sdk-for-ruby#2833]
Hi,
as the repo will be retired, I'm wondering how ruby developers deal with Azure?
Is there any project / library which already provides ruby interfaces to the Azure RestAPI?

**Comment by tbugfinder** [comment]
https://github.com/Azure/azure-sdk-for-ruby/blob/master/docs/README.md

**Comment by nickzhums** [comment]
Hi @tbugfinder 
Please check this guide (https://github.com/Azure/azure-sdk-for-ruby/blob/master/docs/README.md) to call Azure REST API in Ruby

**Comment by jsmartt** [comment]
In the absence of ongoing support, it would be nice if some generic REST methods (like `#get`, `#post`, `#delete`, etc.) were created to simplify manual API calls. The documented way of doing this right now is almost 100 lines long, but to be user-friendly, this really ought to be about 15, with the majority of that being client/auth setup that can be reused.

Also, if Microsoft won't be supporting this repo, will Microsoft grant interested community members access to continue maintaining it?

**Comment by nickzhums** [comment]
Hi @jsmartt , are you referring to this document (https://github.com/Azure/azure-sdk-for-ruby/blob/master/docs/README.md)

Regarding second question, I'm not exactly sure, let me ask and get back to you

**Comment by nickzhums** [comment]
@jsmartt double checked with the team, this repo is still under Microsoft maintenance until Dec 31st, 2021. After that, it will be released to community, by then i will be able to add you to the maintainer list. In the meantime, feel free to submit PR and we will help review, thanks

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
