### ISSUE TITLE
Using a proxy with the Ruby SDK

### ISSUE THREAD

**Issue by chris1984** [Azure/azure-sdk-for-ruby#2834]
Hi, 

We are using the SDK with Foreman so setting the proxy as env variables, won't work. Is there a way to pass proxy info for the connection etc with the SDK or no?

**Comment by nickzhums** [comment]
@chris1984 Ruby SDK is being retired, we highly suggest you start migrating to the REST API apporach, the docs can be found here:
https://github.com/Azure/azure-sdk-for-ruby/blob/master/docs/README.md

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
