### ISSUE TITLE
When we try to fetch Public IP Addresses it is not giving natGateway information attached to Public IP

### ISSUE THREAD

**Issue by amolkumolus** [Azure/azure-sdk-for-ruby#2836]
when we do https call it's giving information about natGateway
https://management.azure.com/subscriptions/{subscription_id}/resourceGroups/{resource_group_name}/providers/Microsoft.Network/publicIPAddresses?api-version=2020-11-01

You can see natGateway is coming in response but not coming through SDK gem

{
    "value": [
        {
            "name": "xxx",
            "id": "/subscription/yyyy",
            "etag": "",
            "location": "",
            "zones": [
                "1",
                "2",
                "3"
            ],
            "properties": {
                "provisioningState": "",
                "resourceGuid": "",
                "**natGateway**": {
                    ""
                },
                "ipAddress": "",
                "publicIPAddressVersion": "",
                "publicIPAllocationMethod": "",
                "idleTimeoutInMinutes": ,
                "ipTags": []
            },
            "type": "Microsoft.Network/publicIPAddresses",
            "sku": {
                "name": "",
                "tier": ""
            }
        }
    ]
}

**Comment by kairu-ms** [comment]
Hi @amolkumolus, that's because Ruby SDK is retired and we will not add new properties in SDK. Please use using [azure rest api](https://github.com/Azure/azure-sdk-for-ruby/tree/master/docs#using-azure-rest-api) directly. Thanks.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
