### ISSUE TITLE
Creating a shared Image Gallery using Azure SDK for Ruby fails with NameError

### ISSUE THREAD

**Issue by swordfish2104** [Azure/azure-sdk-for-ruby#2837]
I'm trying to create a Shared image gallery in the following snippet:

puts 'Creating a Shared Image Gallery'
  gallery_name = 'TestRubySIG'
  imageGallery = ComputeModels::Gallery.new.tap do |sigimg|
  sigimg.type = 'Microsoft.Compute/galleries'
  sigimg.location = 'eastus'
  end

compute_client.Galleries.create_or_update(GROUP_NAME,gallery_name,imageGallery)

This throws the following error:

1: from SIGCreate.rb:199:in `<main>'
SIGCreate.rb:64:in `run_SIGCreate': uninitialized constant Azure::Compute::Profiles::Latest::Mgmt::Models::Gallery (NameError)

Am i doing anything wrong here?

**Comment by nickzhums** [comment]
Hi @swordfish2104 the Ruby SDK is being retired (as indicated on the homepage), you might need to refer to the Azure REST API references

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
