### ISSUE TITLE
Edit VM tags take 2 -> Location header is still missing from long running operation 

### ISSUE THREAD

**Issue by anth1y** [Azure/azure-sdk-for-ruby#2838]
Hello friends:
It turns out that we are still seeing the same issues as described in #2795:

Even after we recently upgraded our azure_mgmt_compute gem to 0.22.0 
and tried to use the same code @ross mentioned:

```
  update = ::Azure::Compute::Profiles::Latest::Mgmt::Models::VirtualMachineUpdate.new
  update.tags = new
  compute_client.virtual_machines.update(resource_group, instance.hostname, update, custom_headers: {"Location" => site.region})
```

while the tags are being updated we are still seeing the call hang around for about 30s

```
{ "message": "Location header is missing from long running operation", "request": null, "response": null }
```

We're wondering if we are doing something wrong or if we implemented this incorrectly ? 
Thanks in advance

**Comment by archerzz** [comment]
Hi @anth1y have you tried the [work-around proposed](https://github.com/Azure/azure-sdk-for-ruby/issues/2795#issuecomment-669638570) in the original issue? That is actually a back-end service issue, as explained in [this comment](https://github.com/Azure/azure-sdk-for-ruby/issues/2795#issuecomment-708704004).
Ruby SDK has [entered retirement phase](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), so I regret to tell you that we would not fix for the back-end. I hope you could understand. Thanks.

**Comment by omgjlk** [comment]
We have used the work around, but unfortunately the work around is a very long process. It can take several seconds, even minutes, to complete the `create_or_update` call, just simply to add or change a tag. this is a significant regression in performance of our tooling compared to how quickly these types of calls return for AWS or our internal cloud tooling. This was never supposed to be al long term solution, and as more of our folks are using this code path the more pain we're experiencing.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
