### ISSUE TITLE
v0.7.0: copy_blob does not support to copy blobs across storage accounts.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-ruby#285]
v0.7.0: copy_blob does not support to copy blobs across storage accounts.

**Comment by yaxia** [comment]
@AbelHu Thanks. The issue has been noted and we will have it in a later release.

**Comment by devigned** [comment]
dup of #194

**Comment by yaxia** [comment]
Please update to the new [storage gem](https://rubygems.org/gems/azure-storage) for the fix. Thanks.

**Comment by AbelHu** [comment]
azure-storage-ruby works. Thanks.
