### ISSUE TITLE
'Error acquiring token from the Azure CLI' due to wrong cli_path

### ISSUE THREAD

**Issue by hunter86bg** [Azure/azure-sdk-for-ruby#2852]
It seems that [File.join](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#L74) returns an invalid cli_path like this on Server2019 and Windows 10:
```
irb(main):002:1* ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
irb(main):003:2*   exts.each do |ext|
irb(main):004:2*     executable = File.join(path, "az#{ext}")
irb(main):005:2*     puts executable if File.executable?(executable) && !File.directory?(executable)
irb(main):006:1*   end
irb(main):007:0> end
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin/az.CMD
=>
<OUTPUT TRUNCATED>
```
This leads to triggering the [rescue](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/credentials/azure_cli_token_provider.rb#L93) in acquire_token().

**Comment by hunter86bg** [comment]
https://github.com/Azure/azure-sdk-for-ruby/pull/2853 theoretically should fix it:
```
irb(main):042:1* ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
irb(main):043:2*   exts.each do |ext|
irb(main):044:2*     executable = File.join(path, "az#{ext}").gsub(File::SEPARATOR, File::ALT_SEPARATOR || File::SEPARATOR)
irb(main):045:2*     puts executable if File.executable?(executable) && !File.directory?(executable)
irb(main):046:1*   end
irb(main):047:0> end
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.CMD
=>
<OUTPUT TRUNCATED>
```

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
