### ISSUE TITLE
get_blob always returns 400

### ISSUE THREAD

**Issue by nw0428** [Azure/azure-sdk-for-ruby#294]
For some reason whenever I use get_blob it returns a 400:
InvalidUri (400): The requested URI does not represent any resource on the server. 

I have Azure gem version 0.7.1.

Example code:
```
blobs_client = Azure.blobs
blobs = blobs_client.list_blobs(container, {prefix: location})
loop do
    blobs.each { |blob|
        b, content = blobs_client.get_blob(container, blob.name) # This line throws the 400
        puts content
    }
    break if (blobs.continuation_token.to_s == "")
    blobs = blobs_client.list_blobs(container, {prefix: location, marker: blobs.continuation_token})
end
```

**Comment by nw0428** [comment]
The bug appears to be caused by extra query params on the URI. I am not sure where they are coming from.
They can be removed, however, by adding `blobs_client.client.reset_agents!` before you call get_blob.

**Comment by devigned** [comment]
closing as I believe this was fixed quite some time back
