### ISSUE TITLE
Update JSON gem dependency, since 1.8.3 requires native code compilation

### ISSUE THREAD

**Issue by Iristyle** [Azure/azure-sdk-for-ruby#298]
The [JSON gem](https://github.com/flori/json) carries with it native C extensions, that require a compiler toolchain be present on any machine that installs the latest `1.8.3` gem (since there are no precompiled binaries available for this gem).

Ruby carries the following JSON gem versions with the distribution by default:

* JSON 1.4.2 with 1.9.2 - https://github.com/ruby/ruby/blob/ruby_1_9_2/ext/json/lib/json/version.rb
* JSON 1.5.5 with 1.9.3 - https://github.com/ruby/ruby/blob/ruby_1_9_3/ext/json/lib/json/version.rb
* JSON 1.7.7 with 2.0.0 series - https://github.com/ruby/ruby/blob/ruby_2_0_0/ext/json/lib/json/version.rb
* JSON 1.8.1 with 2.1.0 - through 2.1.7 - https://github.com/ruby/ruby/blob/v2_1_7/ext/json/lib/json/version.rb
* JSON 1.8.1 with 2.2.0 - through 2.2.3 - https://github.com/ruby/ruby/blob/v2_2_3/ext/json/lib/json/version.rb

Requiring 1.8.3 unfortunately prevents Windows Puppet agents (latest, based on a vendored Ruby 2.1.7) from being to able to consume the Azure Ruby SDK (*) and use the Puppet Azure module (under development).  Please consider changing the minimum required gem version to something older based on the earliest version of Ruby the Azure SDK supports - see the changelog at https://github.com/flori/json/blob/master/CHANGES for more details on what was fixed in each version. 

A couple of solutions are:

* Lowering the version requirement from `~> 1.8.3` to `>= 1.8.1` or `>= 1.7.7` in https://github.com/Azure/autorest/blob/master/ClientRuntimes/Ruby/ms-rest-azure/ms_rest_azure.gemspec#L31
* Completely removing the version associated with the JSON gem
* Removing the reference to the Gem outright, since Ruby distributions ship with it

(*) Technically, users may install a compiler toolchain in production with the DevKit, but not only is this never really done in practice, we actively discourage it for security reasons.

Thanks in advance!

**Comment by Iristyle** [comment]
Note that the same would need to be done for the `ms_rest_azure` dependency as well - ticket filed at https://github.com/Azure/azure-sdk-for-ruby/issues/298

**Comment by djberg96** [comment]
@Iristyle I'm confused as to how this would help unless every gem with a json dependency follows suit. Couldn't you compile locally and bundle your own?

**Comment by Iristyle** [comment]
@djberg96 if you follow the gem dependency hierarchy here, the Microsoft controlled Azure gems are the only ones consuming the JSON gem.  Since the scope is limited, and they're in control of the code, it's reasonably straightforward to make this change in the 2 affected repositories (4 gemspecs here, 2 in the autorest repo).

For the next release that we're preparing, compiling and vendoring a native JSON gem is not something we can do at this stage.  As a general practice, Puppet tries to limit the amount of 3rd party code that we vendor, as this increases the release teams burden (in particular, for security reasons).

**Comment by Iristyle** [comment]
@djberg96 I just realized that I err'd here a bit, and should correct what I've stated.

We *do* ship the JSON 1.8.1 that comes with `rubyinstaller`. However, the reference in these gemspecs is to the newer `1.8.3`, which then triggers an install.  If that version number was relaxed, we should be OK.

**Comment by Iristyle** [comment]
@djberg96 I've updated the title and original request with some more details, since it was originally a bit off-based.  Sorry for the confusion!

**Comment by djberg96** [comment]
@Iristyle Thank you, and excellent work.

I dunno, maybe just eliminate the json version requirement altogether. *shrug*

**Comment by garethr** [comment]
I've also just tracked the same json dependency to the ms_rest gem, as well as the mentioned ms_rest_azure gem.

https://github.com/Azure/autorest/blob/master/ClientRuntimes/Ruby/ms-rest/ms_rest.gemspec#L31

I've put up https://github.com/Azure/autorest/pull/503 to address and kick of the conversation over there.

**Comment by Iristyle** [comment]
Thanks - verified against our latest puppet-agent builds in clean environment - https://tickets.puppetlabs.com/browse/CLOUD-468?focusedCommentId=240651&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-240651 has the specifics.
