### ISSUE TITLE
Forced to send private key for password-less ssh access.

### ISSUE THREAD

**Issue by misaka** [Azure/azure-sdk-for-ruby#301]
Using Azure SDK 0.7.1.

When creating a new VM, the interface to [`create_virtual_machine`](https://github.com/Azure/azure-sdk-for-ruby/blob/master/service_management/azure/lib/azure/virtual_machine_management/virtual_machine_management_service.rb#L95) only [accepts an ssh key as a certificate that includes my ssh private key](https://github.com/Azure/azure-sdk-for-ruby/blob/master/service_management/azure/lib/azure/virtual_machine_management/virtual_machine_management_service.rb#L507). Even though the [Azure REST API to Add Service Certificate is documented](https://msdn.microsoft.com/en-us/library/azure/ee460817.aspx) to accepts a `cer` file with just my public key.

I'm not terribly keen on sending my private key around, to say the least, never mind the fact that I haven't yet figured out how to generate the appropriate PKey file with my private key in it ... I think it would make more sense for the Azure SDK to support sending just the certificate.

**Comment by devigned** [comment]
I agree with you. You should have a much better experience with the Azure ARM libraries.

Take a look at [this deployment template example](https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-sshkey). You can use that template with azure_mgmt_resources gem to deploy with the public side of your ssh key. You can also do that through azure_mgmt_compute, but the template deployment is a lot less imperative code.

Does this help?

**Comment by devigned** [comment]
I'm going to close this issue as providing the private side of the key is required in Azure Service Management APIs. In Azure Resource Management, this is not required and can be reduced to just the public key. We support public keys via Azure Resource Management template deployments via `azure_mgmt_resources` and `azure_mgmt_compute`.

**Comment by misaka** [comment]
Thanks for the response. I'll take a look, unfortunately I've moved past this now and haven't been able to return to it yet.

**Comment by devigned** [comment]
Thank you for the ping back, @misaka. We'll be quicker to respond next time around.
