### ISSUE TITLE
Bad URI exception for non URI encoded paths in StorageService#generate_uri

### ISSUE THREAD

**Issue by creepycheese** [Azure/azure-sdk-for-ruby#302]
The following example raises URI::InvalidURIError:

    storage_service = Azure::Service::StorageService.new
    storage_service.host = 'http://dumyhost.uri'
    storage_service.generate_uri("path/file/фаф.jpg")

**Comment by creepycheese** [comment]
#303 PR

**Comment by devigned** [comment]
Closing since we've merged your pull request. Thank you very much for the contribution.
