### ISSUE TITLE
feature request - interacting with graph api objects

### ISSUE THREAD

**Issue by andrewelizondo** [Azure/azure-sdk-for-ruby#306]
There's missing feature parity between the node sdk and the ruby sdk.

One important feature that's missing is the ability to create/delete/update graphapi objects.

**Comment by devigned** [comment]
Thank you for your patience. We just released the azure_mgmt_graph gem which provides access to the AAD Graph APIs.

Let us know if you have some feedback. We're still iterating on the code generator.
