### ISSUE TITLE
SQL server commands

### ISSUE THREAD

**Issue by rept** [Azure/azure-sdk-for-ruby#307]
Thanks for the gem, I got it working.

Question though: most of the possible operations listed on this page: https://msdn.microsoft.com/en-us/library/azure/dn505719.aspx aren't possible through this gem.  Are they not implemented yet or are they out of scope (will never be implemented) in this gem and should I be using some other gem for this?

**Comment by devigned** [comment]
The intention is that https://github.com/Azure/azure-sdk-for-ruby/tree/master/resource_management/azure_mgmt_sql will have updated Resource Manager APIs based on https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2015-05-01/swagger/sql.json OpenAPI specifications. Currently, the spec doesn't have all of the APIs described. The code is generated from these specifications, so when we get the spec updated, the code will also be updated.

We'll follow up with the SQL team to get the APIs added to the specification.

**Comment by devigned** [comment]
I prompted the Azure SQL team to get the specs updated. I believe this should happen soon. When they are updated, we'll drop new bits.

I'm going to close the issue as I think this is all that can be done for the time being.

@rept if you would like to see some of operations you needed added sooner than later, please feel free to open a pull request against https://github.com/Azure/azure-rest-api-specs/blob/master/arm-sql/2015-05-01/swagger/sql.json. 

I've created an issue to track the spec enhancements in the rest specs repo.
