### ISSUE TITLE
Azure Search

### ISSUE THREAD

**Issue by adaam2** [Azure/azure-sdk-for-ruby#308]
Does the Ruby version of the SDK include Azure Search? Reference to the .NET version: https://azure.microsoft.com/en-gb/documentation/articles/search-howto-dotnet-sdk/

If not, is there any indication as to when this will be available?

**Comment by brjohnstmsft** [comment]
Hi Adam,

There is no Ruby SDK for Azure Search yet. Right now we're focusing on bringing the .NET SDK to feature parity with the REST API. After that (a few months from now at least) we will start figuring out how best to provide SDKs for other languages and platforms, including Ruby.

One key question for us is which languages to tackle first. I created this User Voice item for a Ruby SDK:

https://feedback.azure.com/forums/263029-azure-search/suggestions/11643450-provide-a-ruby-sdk-for-azure-search

Please vote on it to help us prioritize. Thanks!

**Comment by adaam2** [comment]
Okay thank you. I've upvoted this issue on the feedback forums!
