### ISSUE TITLE
SSL Version

### ISSUE THREAD

**Issue by trupel** [Azure/azure-sdk-for-ruby#310]
Is there a way to specify the ssl version via a config setting?

**Comment by devigned** [comment]
Can you expand on what you are interested in doing?

Are you thinking about something like: http://stackoverflow.com/questions/22550213/how-to-set-tls-context-options-in-ruby-like-opensslsslssl-op-no-sslv2/24237525#24237525

**Comment by devigned** [comment]
@trupel any updates on this?

**Comment by devigned** [comment]
Closing the issue due to inactivity. Please reopen if needed.
