### ISSUE TITLE
Expiry times like 1.hour.from_now don't work when creating a shared access signature

### ISSUE THREAD

**Issue by thomas-schreiter** [Azure/azure-sdk-for-ruby#311]
Creating a sas for a Blob does not work when the expiration time is set to `1.hour.from_now`:

```
require 'azure/blob/auth/shared_access_signature'
s = Azure::Blob::Auth::SharedAccessSignature.new(account_name, account_key)
expiry = 1.day.from_now
sas_url = (s.signed_uri(URI('https://myaccount.blob.core.windows.net/container/path/to/blob.txt'), { permissions: 'r', expiry: expiry } )).to_s
=> "https://myaccount.blob.core.windows.net/container/path/to/blob.txt?sr=b&sp=r&sv=2014-02-14&se=2016-02-13+22%3A35%3A07+UTC&sig=mLbmzEDm5mrDQkX%2Bb923nZbQgafZ%2FnBeq%2FI68shR5gQ%3D"
``` 

Pasting the result into the browser or Postman results in a response with the error message: `Signature fields not well formed.`

A **workaround** to provide the expiry argument in the correct ISO8601 format:
```
expiry = 1.day.from_now.iso8601 
sas_url = (s.signed_uri(URI('https://myaccount.blob.core.windows.net/container/path/to/blob.txt'), { permissions: 'r', expiry: expiry } )).to_s
=> "https://myaccount.blob.core.windows.net/container/path/to/blob.txt?sr=b&sp=r&sv=2014-02-14&se=2016-02-13T22%3A36%3A24Z&sig=hib3jEArqBYYeRQ6tTaa3C0RjbIV0io9YaMiLw1rDlA%3D"
```

A **proposal for a bugfix** is to explicitly convert the start and expiry times to the correct format by using `.iso8601` in [`SharedAccessSignature#signable_string`](https://github.com/Azure/azure-sdk-for-ruby/blob/db80afe9220e0e72348ff152069ea2e33a455169/service_management/azure/lib/azure/blob/auth/shared_access_signature.rb#L67).

**Comment by devigned** [comment]
Thank you! We'll get this fixed up.
