### ISSUE TITLE
VirtualMachineSizeTypes is missing values from the wild

### ISSUE THREAD

**Issue by DavidS** [Azure/azure-sdk-for-ruby#312]
Using the web interface I managed to create a VM with vmSize `Standard_D1_v2` which is not available in https://github.com/Azure/azure-sdk-for-ruby/blob/azure-v0.7.1/resource_management/azure_mgmt_compute/lib/azure_mgmt_compute/models/virtual_machine_size_types.rb . This causes the check at https://github.com/Azure/azure-sdk-for-ruby/blob/azure-v0.7.1/resource_management/azure_mgmt_compute/lib/azure_mgmt_compute/models/hardware_profile.rb#L56 to fail and error out.

If you're in there, it would also be great to have the to-level exception to be more informative than the current bland "Error occured in deserializing the response". An improvement would be to add the unrecognized value to the exception title at https://github.com/Azure/azure-sdk-for-ruby/blob/azure-v0.7.1/resource_management/azure_mgmt_compute/lib/azure_mgmt_compute/models/hardware_profile.rb#L57 and pass through the actual exception message in https://github.com/Azure/azure-sdk-for-ruby/blob/azure-v0.7.1/resource_management/azure_mgmt_compute/lib/azure_mgmt_compute/virtual_machines.rb#L841 using 

    fail MsRest::DeserializationError.new("Error occured in deserializing the response: #{e.message}", e.message, e.backtrace, response_content)

**Comment by devigned** [comment]
Ouch... Looks like there are a few things going on in the issue. 

1) We need some better error messaging
2) Enum constrains should be softer
3) We need to include more up-to-date libs

We’ll be addressing 1 and 2 over the next few weeks, perhaps sooner if I can get the time. I can get 3 fixed next week.

**Comment by DavidS** [comment]
:+1:

**Comment by devigned** [comment]
@DavidS can you verify the fix? The gem is in the master branch of the repo. There will be a warning, rather than a fail raised for any enum that isn't recognized.

**Comment by DavidS** [comment]
The code change looks good to me. I might have a run at it within the next days.

**Comment by devigned** [comment]
Thank you. I'll leave this open to get confirmation.

**Comment by YuzorMa** [comment]
Please reopen if the code change does not work out for you.
