### ISSUE TITLE
ruby 2.3

### ISSUE THREAD

**Issue by StasKoval** [Azure/azure-sdk-for-ruby#313]
What about ruby 2.3 support ?

With ruby 2.3.0 `2.3.0 (main):0 > blob = blobs.create_block_blob(container.name, "test.webm", content)
RuntimeError: can't modify frozen String
`

and ruby 2.2.0 `2.2.0 (main):0 > blob = blobs.create_block_blob(container.name, "#{file}", content)
=> #<Azure::Blob::Blob:0x0055cf5f6f05c0
`

**Comment by devigned** [comment]
That's not good... I'll add test that run under 2.3 next week & fix this.

**Comment by djberg96** [comment]
Ruby 2.3 added frozen string literals, but it's supposed to be opt-in. Wonder what happened here.
