### ISSUE TITLE
Azure ARM libraries

### ISSUE THREAD

**Issue by arax** [Azure/azure-sdk-for-ruby#314]
Is there any chance someone will continue with the development of Azure ARM libraries? Is that branch of the project dead?

Could someone point me in the right direction regarding more complete documentation? For example, [Azure ARM Compute](https://github.com/Azure/azure-sdk-for-ruby/tree/master/resource_management/azure_mgmt_compute#creating-new-virtual-machine) shows how to create a virtual machine ... but selecting an OS (version, type, ...) is not mentioned there. How can I select one of the appliances on offer?

I'll be very grateful for any pointers you can give me.

Thanks!

**Comment by Aliasgar16** [comment]
Hi @arax 

You can use Azure Resource Manager powershell cmdlets to retrieve the values for image Publisher, Offer, Sku and Version, click [here](https://msdn.microsoft.com/en-us/library/mt603484.aspx).

Also you can create your own wrapper using [this](https://github.com/Azure/azure-sdk-for-ruby/blob/master/resource_management/azure_mgmt_compute/lib/azure_mgmt_compute/virtual_machine_images.rb#L230) azure-sdk-for-ruby API and retrieve the required values which you can use later while VM creation.

Let me know if you face any issue.


Thanks

**Comment by devigned** [comment]
@arax the ARM gems are not dead. They will get some attention this next week, and increasing attention indefinitely into the future.

Per your question about images... They are a pain to list. The REST API expects a bunch of data prior to returning the list of images (publisher, sku, location and offer). I'm going to try to simplify this portion of the SDK by gluing some of those calls together into something more manageable.

**Comment by arax** [comment]
@Aliasgar16 @devigned Thank you!
