### ISSUE TITLE
template_deployment fails when parameter file contains secret data from keyvault

### ISSUE THREAD

**Issue by rbagai** [Azure/azure-sdk-for-ruby#315]
The template deployment fails when I try to pass secret ssh key using keyvault in parameters file.

Interesting, same works with azure-cli but fails to work with ruby sdk.

Sample Parameters file
```
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "sshKey": {
      "reference": {
        "keyVault": {
          "id": "/subscriptions/28c5cd47-cee9-4b56-b21c-9b2b5ea085e2/resourceGroups/expediaewe/providers/Microsoft.KeyVault/vaults/ExpediaEWEKeyVault"
        },
        "secretName": "SSHKey"
      }
    }
  }
}
```

Template file Snippet
```
"parameters": {
      "sshKey": {
          "type": "securestring"
      }
  },
```

Sample Code for Template Deployment
```
deployment = Azure::ARM::Resources::Models::Deployment.new
    deployment.properties = Azure::ARM::Resources::Models::DeploymentProperties.new
    deployment.properties.template = createJSON(<template-in-string-format>)
    deployment.properties.parameters = parameters_in_values_format(<parameters-in-hash-format>)
    deployment.properties.mode = Azure::ARM::Resources::Models::DeploymentMode::Incremental

    begin
      result = @client.deployments.create_or_update(@resource_group_name, @deployment_name, deployment).value!
      puts "Template Deployment Done - #{result.body.inspect}"
      follow_deployment_until_end_state
    rescue MsRestAzure::AzureOperationError => operation_error
      puts operation_error.body['error']
      raise "#{operation_error.body['error']['code']}: #{operation_error.body['error']['message']}"
    end
```

The error that i encounter is below:-
```
Resrouce Group Created - #<Azure::ARM::Resources::Models::ResourceGroup:0x007fdd19094a18 @location="eastus", @id="/subscriptions/28c5cd47-cee9-4b56-b21c-9b2b5ea085e2/resourceGroups/rahultest102", @name="rahultest102", @properties=#<Azure::ARM::Resources::Models::ResourceGroupProperties:0x007fdd190b80a8 @provisioning_state="Succeeded">, @tags=nil>
{"code"=>"InvalidTemplate", "message"=>"Deployment template validation failed: 'The provided value for the template parameter 'sshKey' at line '1' and column '169' is not valid.'."}
./azure/resource-templates/vpc/bin/create_vpc.rb:52:in `rescue in template_deployment': InvalidTemplate: Deployment template validation failed: 'The provided value for the template parameter 'sshKey' at line '1' and column '169' is not valid.'. (RuntimeError)
	from ./azure/resource-templates/vpc/bin/create_vpc.rb:46:in `template_deployment'
	from ./azure/resource-templates/vpc/bin/create_vpc.rb:32:in `initialize'
	from ./azure/resource-templates/vpc/bin/create_vpc.rb:132:in `new'
	from ./azure/resource-templates/vpc/bin/create_vpc.rb:132:in `<main>'
```

**Comment by devigned** [comment]
Looks like the reference parameter isn't defined in the template. Is that true?

**Comment by singhkay** [comment]
@devigned David, I'm working with Rahul. Interestingly this succeeds in PS and CLI but fails in Ruby. If you need a sample template to repro this with the Ruby SDK, try this one https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-secure-password

**Comment by rbagai** [comment]
@devigned is it something that i missed - i have added the parameters file and template file snippet.

**Comment by devigned** [comment]
@rbagai I think you were working with Kay on this. Did you get to the bottom of this issue?

**Comment by singhkay** [comment]
@devigned This passed with the CLI and failed with Ruby. I think the Ruby SDK needs to be updated. I sent you an email with the templates files for repro

**Comment by devigned** [comment]
@rbagai could you give this a try with the latest azure_mgmt_resources gem in the master branch?

**Comment by devigned** [comment]
@rbagai we published the latest azure_mgmt_resources v0.2.1. You should be able to update from rubygems. Please ping back with your results.

**Comment by devigned** [comment]
@vishrutshah would you verify this scenario?

**Comment by vishrutshah** [comment]
@devigned I verified this scenario with azure_mgmt_resources v0.2.1. Now deployment template supports KeyVault and successfully creates VM. 

@rbagai Could you please verify & confirm that this has been resolved with azure_mgmt_resources v0.2.1?

**Comment by rbagai** [comment]
@devigned @vishrutshah I did installed the newer version of azure_mgmt_resources v0.2.1 but it still seems to be throwing same error. Can you help:-

[1.9.3-p551] (azure) chef-repo$ bundle show azure_mgmt_resources
/Users/rbagai/.rvm/gems/ruby-1.9.3-p551/gems/azure_mgmt_resources-0.2.1

./azure/bin/create_vn.rb:171:in `rescue in template_deployment': InvalidTemplate: Deployment template validation failed: 'The provided value for the template parameter 'sshKey' at line '1' and column '169' is not valid.'. (RuntimeError)
	from ./azure/bin/create_vn.rb:165:in `template_deployment'
	from ./azure/bin/create_vn.rb:88:in `initialize'
	from ./azure/bin/create_vn.rb:294:in `new'
	from ./azure/bin/create_vn.rb:294:in `<main>'

Also Please let me know has something changed in this call?
result = @client.deployments.create_or_update(@resource_group_name, @deployment_name, deployment).value!

This used to be an async call earlier, and i wrote code to know the status for each resource creation, but now it seems to be a blocking call - is there any way i can know how to get the status of each resource creation?

**Comment by devigned** [comment]
You can use @client.deployments.begin_create_or_update and then get the operation status through: http://www.rubydoc.info/gems/azure_mgmt_resources/0.2.1/Azure/ARM/Resources/DeploymentOperations#get-instance_method.

**Comment by rbagai** [comment]
@devigned Thanks - begin_create_or_update worked.

Also, I would like to know if i missed anything in keyvault case. My code snippets are:-

In parameters.json
```
"sshKey": {
  "reference": {
    "keyVault": {
      "id": "/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.KeyVault/vaults/<key_vault_name>"
    },
    "secretName": "SSHKey"
  }
}
```

In resource template
```
"sshKey": {
    "type": “securestring"
}
```

In Ruby code
```
deployment = Azure::ARM::Resources::Models::Deployment.new
    deployment.properties = Azure::ARM::Resources::Models::DeploymentProperties.new
    deployment.properties.template = createJSON(Dir.getwd() + "/azure/resource-templates/vn/template.erb")
    deployment.properties.parameters = parameters_in_values_format(createJSON(Dir.getwd() + "/azure/resource-templates/vn/parameters.json")['parameters'])
    deployment.properties.mode = Azure::ARM::Resources::Models::DeploymentMode::Incremental

result = @client.deployments.begin_create_or_update(<resource_group_name>, <deployment_name>, deployment).value!

def parameters_in_values_format(template_parameters)
    parameters = template_parameters.map do |key, value|
      { key.to_sym => { 'value' => value } }
    end
    parameters.reduce(:merge!)
  end
```

**Comment by vishrutshah** [comment]
@rbagai Your template snippets looks good to me. The only thing i did differently from you is, I uploaded templates to Azure blob storage with 'Container' access type and used them as below: 

```
    deployment = Azure::ARM::Resources::Models::Deployment.new
    deployment.properties = Azure::ARM::Resources::Models::DeploymentProperties.new
    deployment.properties.template_link = Azure::ARM::Resources::Models::TemplateLink.new
    deployment.properties.template_link.uri = "https://{resourceGroup}.blob.core.windows.net/{containerName}/create_vpc.json"
    deployment.properties.parameters_link = Azure::ARM::Resources::Models::ParametersLink.new
    deployment.properties.parameters_link.uri = "https://{resourceGroup}.blob.core.windows.net/{containerName}/parameters.json"
    deployment.properties.mode = Azure::ARM::Resources::Models::DeploymentMode::Incremental
```

Can you please try using the uri link instead of manually converting them to json parameters & let us know your results?

**Comment by devigned** [comment]
Here's an example of using a template and parameters to deploy: https://github.com/Azure/azure-sdk-for-ruby/issues/309#issuecomment-200442105.

To help with debugging, perhaps add HTTP logging, so we can see what's actually on the wire via `export AZURE_HTTP_LOGGING=full`

see: https://github.com/Azure/autorest/blob/master/ClientRuntimes/Ruby/ms-rest/lib/ms_rest/http_operation_request.rb#L74-L77

**Comment by rbagai** [comment]
@vishrutshah @devigned Thanks, it worked with parameters uri, but from disk it did not work. It keeps throwing error. I think after loading the json into memory and passing to deployment.properties.parameters, it needs some conversion. Can you please test and let me know, or something needs to be fixed at disk based scenario.

**Comment by vishrutshah** [comment]
@rbagai Thanks for confirmation that uri scenario works. 
We'll try out the the scenario for using deployment.properties.parameters instead of uri and update you.

**Comment by vishrutshah** [comment]
@rbagai I have verified that using the deployment.properties.parameters with sshKey works as expected. From the your code snippet it looks like there is potential problem in the following lines

```
deployment.properties.template = createJSON(Dir.getwd() + "/azure/resource-templates/vn/template.erb")
deployment.properties.parameters = parameters_in_values_format(createJSON(Dir.getwd() + "/azure/resource-templates/vn/parameters.json")['parameters'])   
```

I am not sure what is the function of '**_parameters_in_values_format_**' method. Below is the code snippet that uses the parameters instead of uri and successfully deploys the template:

```
require 'json'

token_provider = MsRestAzure::ApplicationTokenProvider.new({tenetId}, {clientId}, {clientSecret})
credentials = MsRest::TokenCredentials.new(token_provider)

client = Azure::ARM::Resources::ResourceManagementClient.new(credentials)
client.subscription_id = {subscriptionId}

file = File.read('create_vpc.json')
template_hash = JSON.parse(file)

file = File.read('parameters.json')
param_hash = JSON.parse(file)

deployment = Azure::ARM::Resources::Models::Deployment.new
deployment.properties = Azure::ARM::Resources::Models::DeploymentProperties.new
deployment.properties.template = template_hash
deployment.properties.parameters = param_hash['parameters']
deployment.properties.mode = Azure::ARM::Resources::Models::DeploymentMode::Incremental

begin
  result = client.deployments.create_or_update("{resourceGroup}", "{deploymentName}", deployment).value!
  puts "Template Deployment Done - #{result.body.inspect}"
rescue MsRestAzure::AzureOperationError => operation_error
  puts operation_error.body
end
```

Could you please verify? Thanks.

**Comment by devigned** [comment]
I use the following to take a hash of key value pairs and transform them into the template parameters:
```ruby
# {a: 'foo', b: 'bar'} tranforms to {a: {value: 'foo'}, b: {value: 'bar'}}
def build_parameters(options)
  Hash[*options.map{ |k, v| [k,  {value: v}] }.flatten]
end
```

Please give that a try and if it works, I think we might be able to close this issue.

**Comment by rbagai** [comment]
@vishrutshah @devigned this works for me as well. thanks

**Comment by vishrutshah** [comment]
@rbagai Thank you very much for the confirmation. We appreciate your time & efforts.

**Comment by atd80** [comment]
When you have solution you give,  and when not its better not to give instead of just keep on throwing something and wasting everyone time. Thread trails tail said all.
