### ISSUE TITLE
SDK not compatible with Azure Government endpoints

### ISSUE THREAD

**Issue by jbeyer05** [Azure/azure-sdk-for-ruby#316]
Specifically, when trying to access a queue in a storage account called 'foobar', if I refer to the storage account as 'foobar' in my code, the SDK appends '.queue.core.windows.net' to the name of the storage account.  The full URI that the SDK accesses is then 'foobar.queue.core.windows.net'.

However, if trying to access a queue in a storage account whose full name is 'foobar.queue.core.usgovcloudapi.net', I can't pass the full name, or it becomes '.queue.core.usgovcloudapi.net.queue.core.windows.net', and if I pass 'foobar', it tries to access 'foobar.queue.core.windows.net', as opposed to 'foobar.queue.core.usgovcloudapi.net'.

Am I missing something obvious here?

Thanks in advance for your help!

**Comment by jbeyer05** [comment]
Sorry, realized that I simply need to set Azure.storage_queue_host to the full URI.  I'll leave this open as a suggestion that perhaps the README should specifically mention Azure Gov in the same section where Azure.storage_queue_host is mentioned.

**Comment by devigned** [comment]
We'll get that added to the readme.

**Comment by jbeyer05** [comment]
Thanks!

**Comment by devigned** [comment]
@veronicagg can you add this to the readme where it seems appropriate?
