### ISSUE TITLE
Missing automated AD Authentication process

### ISSUE THREAD

**Issue by NimishaS** [Azure/azure-sdk-for-ruby#317]
Currently in order to use the `azure-sdk` methods, we have to provide `tenant-id`, `client-id` and `secret` for the AD authentication. For that we need to follow these steps http://aka.ms/cli-service-principal.

This is a bit complicated for the end user to do so many things manually. We would like to achieve something like the way `azure-powershell` and `azure-xplat-cli` do for AD auth. The user only has to run `Login-AzureRmAccount` or `azure login` and then he can run any ARM command. No need to create the `AD application` and `service principal` separately.

**Comment by devigned** [comment]
Hi @NimishaS. I completely understand. It is little complicated to setup a service principal, and it takes a fair amount of domain knowledge to understand what / why a developer needs one in the first place.

Let me start out with a bit of background. Anything that is going to run non-interactive in Azure needs to authenticate as a service principal. User credentials are only intended for interactive authentication (user accounts may have multi-factor auth, etc.).

With that said, we are working together with the Azure Active Directory team to set a standard location for authentication tokens which would enable the scenario you have mentioned.

As for now, AAD service principal is the route we want to recommend to developers using the SDKs.

**Comment by devigned** [comment]
I'm going to close this issue for the time being. We'll likely add an interactive flow in the future, but it's not near term.
