### ISSUE TITLE
Semver failure/breaking changes between azure_mgmt_* and ms_rest_azure

### ISSUE THREAD

**Issue by stuartpreston** [Azure/azure-sdk-for-ruby#321]
The azure_mgmt_resources.gemspec has a gem dependency on ms_rest_azure at version ~> 0.1 (i.e. >=0.1 and <1.0) and on 'clean' machine, this currently brings down v0.2.1 (see https://github.com/Azure/azure-sdk-for-ruby/blob/master/resource_management/azure_mgmt_resources/azure_mgmt_resources.gemspec#L37)

To take an example of where this is an issue, creating a Resource Group using 0.1.1 of azure_mgmt_resources makes a call with **3** arguments: ```@client.get_put_operation_result(response, custom_headers, deserialize_method)``` (see https://github.com/Azure/azure-sdk-for-ruby/blob/master/resource_management/azure_mgmt_resources/lib/azure_mgmt_resources/resource_groups.rb#L224)

However, in 0.2.1 of ms_rest_azure this method only takes **2** arguments: ```def get_put_operation_result(azure_response, custom_deserialization_block)``` (see https://github.com/Azure/autorest/blob/master/ClientRuntimes/Ruby/ms-rest-azure/lib/ms_rest_azure/azure_service_client.rb#L23)

Whilst I noticed this pretty quickly (happened to be building a clean system today), and was able to put in a fix higher up the dependency chain in my software to pin down the versions of ms_rest_azure and ms_rest, I suspect a better answer in the short term would be to fix the dependencies within azure_mgmt_* to the 0.1 gems, and of course to regenerate/republish the newer azure_mgmt_* gems so everything lines up correctly.

@devigned

**Comment by devigned** [comment]
We will get this fixed immediately.

**Comment by devigned** [comment]
These constrains should have been locked down to the minor version rather than major. Until we reach 1.0, we'll likely introduce breaking changes for the minor versions, but we'll not introduce breaking changes within the patch version increments.

We'll do our best to keep breaking changes to a minimum.

**Comment by devigned** [comment]
@stuartpreston version 0.1.2 of the gems has been pushed with the dependencies locked down to the 0.1'ish version of the client runtime. This should fix the issue. Please let me know if that is not the case.

**Comment by stuartpreston** [comment]
@devigned Looks ok on a clean machine now - thanks for speedy resolution. I've also gone for a protectionist strategy and pinned the ms_rest and ms_rest_azure gems to specific minor versions for now in my own software. Will look to move up when everything lines up at latest versions. Thanks again.
