### ISSUE TITLE
Newly released ms_rest_azure gem breaks azure-sdk-for-ruby.

### ISSUE THREAD

**Issue by Aliasgar16** [Azure/azure-sdk-for-ruby#324]
**ms_rest_azure-0.1.2** gem which is internally used by **azure_mgmt_resources**, **azure_mgmt_compute**, **azure_mgmt_storage** and **azure_mgmt_network** gems of **azure-sdk-for-ruby** has recently got updated with newer version **ms_rest_azure-0.2.1** and then with **ms_rest_azure-0.2.2**.

This update has caused azure-sdk-for-ruby gems to fail on [this](https://github.com/Azure/autorest/blob/master/ClientRuntimes/Ruby/ms-rest-azure/lib/ms_rest_azure/azure_service_client.rb#L23) line for **ms_rest_azure-0.2.2** gem as same thing for older version of **ms_rest_azure-0.1.2** gem (which azure-sdk-for-ruby is currently using) has [this](https://github.com/Azure/autorest/blob/azrb-v0.1.2/ClientRuntimes/Ruby/ms-rest-azure/lib/ms_rest_azure/azure_service_client.rb#L24) method definition.

Because of this mismatch in method definition in different versions of the **ms_rest_azure** gem has caused it to give error `Wrong number of arguments (3 for 2)`.

**Comment by devigned** [comment]
This should be resolved in ms_rest_azure-0.1.2 with a dependency on ms_rest ~>0.1.0. See: https://github.com/Azure/azure-sdk-for-ruby/issues/321.

Can you verify you are still seeing this issue with ms_rest_azure-0.1.2?

**Comment by devigned** [comment]
Also, the gems were republished with stricter ms_rest_azure dependencies. See version 0.1.2 of the azure sdk gems, for example: https://rubygems.org/gems/azure_mgmt_compute/versions/0.1.2.

**Comment by Aliasgar16** [comment]
@devigned The fix is working. Thanks.

**Comment by devigned** [comment]
Awesome! Thank you.
