### ISSUE TITLE
ARM gems error out with uninitialized constant Azure

### ISSUE THREAD

**Issue by jervill** [Azure/azure-sdk-for-ruby#327]
The 0.2.0 versions of the Azure Resource Management gems throw an error "uninitialized constant Azure".

To repro, either
1. Download the source.
2. Set up your AZURE_TENANT_ID, etc.
3. `rspec`

or
1. Install the gem `gem install azure_mgmt_compute:0.2.0`
2. Open `irb`
3. In irb, `require 'azure_mgmt_compute'`

Rather than loading the required gem, I get the error that Azure is an uninitialized constant.

> `azure_mgmt_resources.rb:21:in `<top (required)>': uninitialized constant Azure (NameError)`

**Comment by devigned** [comment]
Thank you. Looking at it now.

**Comment by devigned** [comment]
Looks good locally. Please ping back with your results.

**Comment by jervill** [comment]
Hi @devigned thanks for the update. I pulled your latest changes and installed v.0.2.1. I'm no longer hitting the uninitialized constant error when requiring the gems. I see other errors with rspec, but I think those might be issues on my end. Thanks! Marking this as closed.

**Comment by devigned** [comment]
Yeah... the project setup right now has an excepectation that you will do a `bundle install` in the root of ./resource_manager and then run `rake arm:spec` to execute test across all of the gems.

We need to clean up the test / developer workflow as it's rather awkward right now.

Thank you for the issue report and for the prompt response. Please don't hesitate to provide feedback. Cheers!

**Comment by jervill** [comment]
Hi @devigned , just a question here about auth and service principals, only loosely related to this issue. I tried running the tests again and I get an error stating: 

`The client '[redacted]' with object id '[redacted]' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/write' over scope '/subscriptions/[redacted]/resourcegroups/RubySDKTest_72cc1e98d6464f4fb812e7b2388a3abd'.\`

That make sense to me because as I understand it, the tests generate a new resource group each time. Thing is, my service principal does not have access to those groups yet. Is there a way to give my service principal access to all the resource groups in my subscription? Or at least to all the resource groups that it creates? Thanks in advance!

**Comment by devigned** [comment]
Awesome question! You can give your service principal contributor rights to your subscription.

In the Azure portal, click on Subscriptions, click on the user icon, then add your user or find the service principal / application and give the service principal rights to contribute to the subscription. See below.

![sub-role](https://cloud.githubusercontent.com/assets/386473/13848815/c158feee-ec10-11e5-86c4-a72c37a3529f.png)

**Comment by jervill** [comment]
Ah cool, I didn't realize you could dig deeper into subscriptions via the portal. Thanks!
