### ISSUE TITLE
Gem install fails with nokogiri dependency 

### ISSUE THREAD

**Issue by kenazk** [Azure/azure-sdk-for-ruby#332]
When installing the Azure gem, it fails on Ubuntu 14.04 LTS with the following error:

`ERROR:  Error installing azure:\`
` ERROR: Failed to build gem native extension.\`
`    /opt/puppetlabs/puppet/bin/ruby extconf.rb\`
`Using pkg-config version 1.1.7\`
`checking if the C compiler accepts ... yes\`
`Building nokogiri using packaged libraries.\`
`Using mini_portile version 2.1.0\`
`checking for gzdopen() in -lz... yes\`
`checking for iconv using --with-opt-* flags... yes\`

Can you update the documentation to identify what gems need to be installed (and how to install them) prior to installing the Azure module? I imagine that there are a number of customers with perhaps limited Ruby background (like myself) who run into a lot of issues with the installation due to these dependencies.

**Comment by devigned** [comment]
What happens when you try to `gem install nokogiri`?

Also, please see: http://www.nokogiri.org/tutorials/installing_nokogiri.html

**Comment by devigned** [comment]
@kenazk any updates on this one?
