### ISSUE TITLE
Net::Http.open_timeout is not set so sometimes it hangs.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-ruby#334]
Before Ruby v2.3.0, read_timeout is set to 60 seconds by default but open_timeout is set to nil by default. open_timeout is not set so that sometimes it hangs.

https://github.com/Azure/azure-sdk-for-ruby/blob/db80afe9220e0e72348ff152069ea2e33a455169/service_management/azure/lib/azure/core/http/http_request.rb#L127

**Comment by AbelHu** [comment]
Ping. Cloud Foundry project depends on azure-sdk-for-ruby. We need your fix for this issue.

**Comment by devigned** [comment]
@vishrutshah and @veronicagg let's take a look at this tomorrow.

Thx for the heads up, @AbelHu!

**Comment by veronicagg** [comment]
@AbelHu The issue should be resolved now.
