### ISSUE TITLE
Resource Group is available on resources

### ISSUE THREAD

**Issue by devigned** [Azure/azure-sdk-for-ruby#340]
Resource group is not available as a property on the virtual machine. You can ascertain it from the URI. This is a pain as it will probably change in the future. An accessor would be better.

All resources should provide the resource group based on the uri of the resource.

**Comment by veronicagg** [comment]
we could obtain the resource group name from the ID of the MsRestAzure::Resource::ID, and surface it to the properties.

**Comment by sarangan12** [comment]
Closing the issue
