### ISSUE TITLE
Management certificate not valid. Error: PKCS12_parse: mac verify failure

### ISSUE THREAD

**Issue by DavidR91** [Azure/azure-sdk-for-ruby#347]
I followed the 'Get Started with OpenSSL' guide, and generated a generic cert.pem

The certificate begins with a private key and ends with the actual certificate block.

I receive a PKCS12_parse error for the cert.pem that is generated. From what I understand of the code, this precedes any kind of remote communication at all, and is just the certificate format itself.

I am using the gem via vagrant-azure, which appears to be using 0.7.0 (embedded inside of itself)

	 /root/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/configurable.rb:184:in `rescue in management_certificate=': Management certificate not valid. Error: PKCS12_parse: mac verify failure (ArgumentError)
	        from /root/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/configurable.rb:167:in `management_certificate='
	        from /root/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/action/connect_azure.rb:29:in `block in call'
	        from /root/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/configurable.rb:113:in `configure'
	        from /root/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/action/connect_azure.rb:27:in `call'

I know that obviously you're not responsible for how vagrant-azure utilises this gem - that I understand. 

But do you have any pointers (e.g. related to versioning?) as to why I would be seeing this error?

If I switch to using an inline certificate (from a string), the error instead becomes a problem with asn1 (`Management certificate not valid. Error: nested asn1 error (ArgumentError)`)

Is there something dumb I'm likely to be doing related to the format of the pem? (e.g. line endings? Should I be stripping BEGIN and END out myself?)

**Comment by LiliDeng** [comment]
+1 hit the same issue against azure-0.7.5 version

**Comment by devigned** [comment]
Use this to derive your cert: https://github.com/Azure/vagrant-azure/issues/118#issuecomment-217056502. It's likely you don't have the formatting just right.

**Comment by LiliDeng** [comment]
hmm, should be our fault, the value is Azure.management_certificate = "C:\OpenSSL-Win64\bin\lilitest512.pem" when get the complie error, after changed into Azure.management_certificate = "C:\\OpenSSL-Win64\\bin\\lilitest512.pem", it works.

**Comment by LiliDeng** [comment]
thanks @devigned

**Comment by devigned** [comment]
Anytime, @LiliDeng!

Can we close this issue?

**Comment by lilidengostc** [comment]
Sure, thanks @devigned
