### ISSUE TITLE
[Test] Unable to record test with non-UTF-8 character set in response body

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#351]
Currently few set of integration tests have been disabled because of the problem faced in recording non-UTF-8 character set recordings on VCR YAML cassettes. 

[File:sb_queue_gb18030_test.rb line No 57](https://github.com/Azure/azure-sdk-for-ruby/blob/master/service_management/azure/test/integration/service_bus/sb_queue_gb18030_test.rb#L57)

Find a way to record these integration tests for increased test coverage.

**Comment by sarangan12** [comment]
This is an old issue and does not seem to be important now as this is in the old asm model. I am closing this.
