### ISSUE TITLE
Security: Validate HTTPS responses

### ISSUE THREAD

**Issue by guangyang** [Azure/azure-sdk-for-ruby#36]
One of the reasons for using HTTPS is that you can be sure that there is no man-in-the-middle, intercepting and potentially altering your requests.

However, the `Azure::Core::Http::HttpRequest` contains this alarming code:
```ruby
          if uri.scheme.downcase == 'https'
            # require 'net/https'
            http.use_ssl = true
            http.verify_mode = OpenSSL::SSL::VERIFY_NONE
          end
```
It appears that the server's SSL key is not verified, which means that *if* I can hijack your router, *then* all your HTTPS traffic is as open as HTTP traffic.

**Comment by arax** [comment]
I agree. This is a potentially critical security issue. Is fixing this issue in the roadmap yet?

**Comment by devigned** [comment]
Close in favor of tracking via #210
