### ISSUE TITLE
Can not upload file with spaces

### ISSUE THREAD

**Issue by malibeg** [Azure/azure-sdk-for-ruby#360]
With new version 0.7.3. I can not upload files with spaces in filename. On azure file is created with content-length of zero and filename contains html encoding with %20

**Comment by devigned** [comment]
Thank you for the issue report. We'll take a look at this asap.

@veronicagg or @vishrutshah, please take a look.

**Comment by vishrutshah** [comment]
@malibeg & @devigned 

We have reproduced the problem and it seems like regressed from PR #303 We are looking into it why we are encoding the path twice.

**Comment by vishrutshah** [comment]
@malibeg Thanks for reporting this. It'd be great if you'd like to review the PR for the fix, we'd appreciate it.

**Comment by vishrutshah** [comment]
Hi @malibeg, we have fixed the problem and released a new version of azure gem v0.7.4. 

Please use [Azure Gem v0.7.4](https://rubygems.org/gems/azure/versions/0.7.4) and let us know your feedback, 

Thanks,
