### ISSUE TITLE
Detach datadisk VHD from azure compute 

### ISSUE THREAD

**Issue by kowsalyapalaniappan** [Azure/azure-sdk-for-ruby#382]
There is no support to detach the VHD from the compute. I am looking for a way do exact job of this cli azure vm disk detach <virtual-machine-name> <LUN> using this sdk.

**Comment by veronicagg** [comment]
@kowsalyapalaniappan Have you tried detaching the datadisk by using create_or_update with empty DataDisk in StorageProfile?
See https://github.com/Azure/azure-sdk-for-ruby/blob/master/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/storage_profile.rb#L22 
There's a python sample doing it this way, if you want to take a look at https://github.com/Azure-Samples/virtual-machines-python-manage/blob/master/example.py#L155
Let us know if this works for you, thanks!
