### ISSUE TITLE
ASM - hit issue when invoke vm_management.list_virtual_machines

### ISSUE THREAD

**Issue by LiliDeng** [Azure/azure-sdk-for-ruby#389]
I use below code to list VM, but hit below exception, the cert comes from command azure account cert export (Azure CLI), does't anyone know the reason, thanks much, I am newbie of ruby.

Code
require 'azure'
Azure.management_certificate = "C:\\OpenSSL-Win64\\bin\\lilitestglobal.pem"
Azure.subscription_id        = "id"
vm_management = Azure.vm_management
vm_management.list_virtual_machines

Exception
C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
	from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1156:in `get'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/azure-core-0.1.1/lib/azure/http_response_helper.rb:27:in `set_up_response'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/azure-0.7.5/lib/azure/base_management/management_http_request.rb:51:in `call'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/azure-0.7.5/lib/azure/cloud_service_management/cloud_service_management_service.rb:66:in `list_cloud_services'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/azure-0.7.5/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:31:in `list_virtual_machines'
	from C:/Bitnami/wampstack-5.5.34-0/apache2/htdocs/liliruby/lili.rb:10:in `<main>'

**Comment by devigned** [comment]
Are you behind a proxy?

**Comment by lilidengostc** [comment]
Cloud you clarify what is 'behind a proxy'?

**Comment by lilidengostc** [comment]
You mean IE proxy? No, I didn't set it. @devigned

**Comment by devigned** [comment]
It sounds like your http traffic is being routed through a different machine than the Azure management endpoint. This would cause the issue above where the certificate provided by the proxy server isn't trusted.

It's also possible that if you are on Windows, you don't have a collection of trusted certs specified. See: https://gist.github.com/fnichol/867550.

The general issue is that Ruby http is unable to verify the host's certificate you are trying to communicate with.

**Comment by lilidengostc** [comment]
hmm. my cert [Azure.management_certificate = "C:\OpenSSL-Win64\bin\lilitestglobal.pem"]  get from Azure CLI on machine A (azure account export). Code located on machine B, both are windows machine. Do you mean I should export the cert from machine B which the code lcated? @devigned

**Comment by devigned** [comment]
The computer running the Azure Ruby sdk process that is trying to connect to Azure is unable to verify that the certificate provided by https://management.core.windows.net is trusted by your trusted certificate pack. If the sdk can't verify the certificate from https://management.core.windows.net derives from a trusted root certificate, then it will raise an error. This is to protect developers from a 'man in the middle' attack (https://en.wikipedia.org/wiki/Man-in-the-middle_attack).

Please see: https://gist.github.com/fnichol/867550#the-manual-way-boring for a description of how to setup your collection of trusted root certificates.

**Comment by LiliDeng** [comment]
@devigned The cert is from by run command azure account export -f, I am not sure what is the issue there. For this link https://gist.github.com/fnichol/867550#the-manual-way-boring, should I follow the steps one by one? Could you please tell me what exact steps you did when using the cert to operate azure resource?

**Comment by LiliDeng** [comment]
@devigned thanks for your help, thanks much!!! My issue resolved when add below lines in the beginning, search from http://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat

require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

**Comment by devigned** [comment]
So glad to help. Sorry for the rough experience, but it's often the case when dealing with openssl + ruby + windows.

We've tried to stay away from distributing a cert pack with the gem, but I might change my mind on this subject given the number of people that run into this issue.
