### ISSUE TITLE
Service Bus topics: Faraday::ConnectionFailed

### ISSUE THREAD

**Issue by cmager** [Azure/azure-sdk-for-ruby#396]
ruby 2.2.0, azure gem 0.7.5

Hi, i am trying to receive Service Bus topics but i am always receiving the `Faraday::ConnectionFailed` error message shown below. Am i doing something wrong here or is it related to https://github.com/Azure/azure-sdk-for-ruby/issues/232?

```ruby
require 'azure'
require 'azure/service_bus/service_bus_service'

# namespace and access_key changed, of course
Azure.sb_namespace = 'namespace-ns'
Azure.sb_access_key = 'access key'
Azure.sb_issuer = 'message-receiver' # Permissions: manage, send, listen

sb = Azure::ServiceBusService.new
msg = sb.receive_queue_message("topic-name")
=> Faraday::ConnectionFailed: getaddrinfo: nodename nor servname provided, or not known
from /Users/xmager/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
```
Looking at the `sb` object it looks like this:

```
#<Azure::ServiceBus::ServiceBusService:0x007fb86551cfc8
 @account_name=nil,
 @client=Azure,
 @filters=
  [#<Azure::Core::Http::SignerFilter:0x007fb86551c9d8
    @signer=#<Azure::ServiceBus::Auth::WrapSigner:0x007fb86551ced8 @tokens={}, @wrap_service=#<Azure::ServiceBus::Auth::WrapService:0x007fb86551cd70 @access_key="access key", @client=Azure, @filters=[], @host="https://namespace-ns-sb.accesscontrol.windows.net", @issuer="message-receiver">>>,
   #<Proc:0x007fb86551c7f8@/Users/cmager/.rvm/gems/ruby-2.2.0/gems/azure-0.7.5/lib/azure/service_bus/service_bus_service.rb:35>],
 @host="https://namespace.servicebus.windows.net",
 @signer=#<Azure::ServiceBus::Auth::WrapSigner:0x007fb86551ced8 @tokens={}, @wrap_service=#<Azure::ServiceBus::Auth::WrapService:0x007fb86551cd70 @access_key="access key", @client=Azure, @filters=[], @host="https://namespace-ns-sb.accesscontrol.windows.net", @issuer="message-receiver">>>
```

Thanks for your help.

**Comment by veronicagg** [comment]
Hi @cmager , 
Thanks for your question! 
Are you using ACS for your service bus? If so, #232 should not be related (as it was using SAS). 
For Service Bus topics, messages are not directly received from the topics (as they are from queues) but instead, they are received from subscriptions (associated with the topics), there's some information on this at [Service Bus queues, topics and subscriptions] (https://azure.microsoft.com/en-us/documentation/articles/service-bus-queues-topics-subscriptions/).
You can take a look at samples in our [test code for subscriptions] (https://github.com/Azure/azure-sdk-for-ruby/blob/master/test/integration/service_bus/subscriptions_test.rb) for help on how to use subscriptions (ex. 'should read a message from a subscription' test) .
Hope this helps, feel free to let us know if you need additional help.
Thanks,
Veronica

**Comment by cmager** [comment]
Hi and thanks for the reply.
Well, now i tried it this way:

```ruby
sub = sb.create_subscription("test-topic-name", "test1")
SocketError: Failed to open TCP connection to namespace-ns-sb.accesscontrol.windows.net:443 (getaddrinfo: nodename nor servname provided, or not known)
from /Users/cmager/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
```

I am starting to think the url it's trying to connecting to is not correct: `namespace-ns-sb.accesscontrol.windows.net`. Which one would be the correct one?

Thanks, Christian

**Comment by veronicagg** [comment]
Hi @cmager , 
The service bus endpoint should look something like `https://<sb-namespace-name>.servicebus.windows.net`. 

Here's what I've done:
 - First, I created a service namespace via Azure CLI ([guidance](https://azure.microsoft.com/en-us/documentation/articles/service-bus-ruby-how-to-use-queues/))

   Here's what I ran using Azure CLI:
   `azure config mode asm` 
      to set mode to asm (azure classic)
    `azure sb namespace create - 'namespacename' -r 'West US'`
      to create the service namespace

At this point, you should see the service bus created in your subscription in the Azure classic portal.
Once you see it, select it on the page, and at the bottom there should be an icon for "Connection Information", click to view it and get your ACS "Default key", you'll need it for configuration (see below).

 - Then in ruby code:

```ruby
Azure.config.sb_namespace = 'namespacename' #please replace with your namespace name
Azure.config.sb_access_key = 'default-key' # please replace with your default key here
servicebus = Azure::ServiceBus::ServiceBusService.new
servicebus.create_topic 'topic1'
servicebus.create_subscription 'topic1', 'subscription1'
```
Now, in the Azure classic portal, you should see the topic created in the Topics tab, and its subscriptions count.
If it doesn't work for you, feel free to let me know.
Thanks,
Veronica

**Comment by veronicagg** [comment]
Feel free to reopen the issue, if you encounter any other problems. thanks!

**Comment by Dunkirk** [comment]
I'd like to reopen it. I can't figure out what I'm supposed to be doing.

```
require 'azure'
Azure.config.sb_namespace='<namespace>'
Azure.config.sb_access_key='<key>'
servicebus = Azure::ServiceBus::ServiceBusService.new
servicebus.create_topic 'topic1'
servicebus.create_subscription 'topic1', 'subscription1'
```

/Users/david/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: nodename nor servname provided, or not known (Faraday::ConnectionFailed)
