### ISSUE TITLE
HTTP header crashes with Failed to receive message: 757: unexpected token at '{ "strict-transport-security" : max-age=31536000}'

### ISSUE THREAD

**Issue by slicke** [Azure/azure-sdk-for-ruby#400]
When receiving messages, as of June 28, this error occurs:
Failed to receive message: 757: unexpected token at '{ "strict-transport-security" : max-age=31536000}'

This seems to be fixable by adding strict-transport-security to the "header_names_black_list" in lib/azure/service_bus/brokered_message_serializer.rb

**Comment by slicke** [comment]
I created #401 for this :)

**Comment by vishrutshah** [comment]
@slicke You changes has been merged in. Should be fix on the next release.
