### ISSUE TITLE
How to attach template that will custom script on VM?

### ISSUE THREAD

**Issue by kavitakanojiya** [Azure/azure-sdk-for-ruby#404]
I am creating a VM that will run some kind of script. This script will install codebase with custom parameters. I see we can create JSON file with all necessary configs. This JSON will have this custom script too.

Is there a way to attach this script when VM is created ?

**Comment by devigned** [comment]
Checkout custom script extensions (https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-extensions-customscript/). They provide this functionality.

This repo doesn't contain the gem to deploy templates in Azure. For deploying templates, you want to use [Repo](https://github.com/Azure/azure-sdk-ruby/tree/master/azure_mgmt_resources) or [Gem] (https://rubygems.org/gems/azure_mgmt_resources).

Also, here's a sample for deploying a template: https://github.com/Azure-Samples/resource-manager-ruby-template-deployment. 

This can also be done imperatively through the [Azure Resource Manager Compute Gem] (http://www.rubydoc.info/gems/azure_mgmt_compute) via compute_client.virtual_machines.create_or_update(...)  in https://github.com/Azure/azure-sdk-ruby/blob/master/azure_mgmt_compute/lib/generated/azure_mgmt_compute/virtual_machines.rb#L170-L199.

**Comment by devigned** [comment]
Closing here as it doesn't apply to this repo. If that didn't answer your question, please open in https://github.com/Azure/azure-sdk-ruby/.

**Comment by kavitakanojiya** [comment]
Thanks
