### ISSUE TITLE
Support for service bus queue renew lock

### ISSUE THREAD

**Issue by mydiemho** [Azure/azure-sdk-for-ruby#441]
I can't seem to find the code for renew_lock, only release_lock for [blob service](https://github.com/Azure/azure-sdk-for-ruby/blob/09ab24e511889d41a1fef4755217baa595a279f5/lib/azure/blob/blob_service.rb#L1275).  Is this not a supported feature?

**Comment by sarangan12** [comment]
Recommending all users to move to ARM model. Since this is an old issue, I am closing this
