### ISSUE TITLE
Support for enable_partition in queue creation

### ISSUE THREAD

**Issue by mydiemho** [Azure/azure-sdk-for-ruby#445]
There's no support for enabling partition when creating queue in code.

https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.queuedescription.enablepartitioning.aspx

**Comment by sarangan12** [comment]
Recommending all users to move to the ARM model. No new enhancements are being done in the asm model. Since this is an old issue, I am closing this.
