### ISSUE TITLE
ASB Queue receive_queue_message time out

### ISSUE THREAD

**Issue by mydiemho** [Azure/azure-sdk-for-ruby#447]
It doesn't look like the timeout value is pass to faraday.

1) When I don't set a time out, which use default=60s, any request that takes longer than 60s throw [an exception](https://gist.github.com/mydiemho/ecb85d174264899d0d50d69f5a7f1f65)

Net::ReadTimeout
duration: 60.237244844436646

2) When I set a time out less than 60, ie. 30s, I don't get any exception, but just get a nil object

3) When I set a time out > 60, ie. 70s, request won't throw exception until it reaches 120s

Net::ReadTimeout
duration: 120.92066097259521

Net::ReadTimeout
duration: 120.90042495727539

**Comment by jfggdl** [comment]
@mydiemho, unfortunately, this issue was not seen earlier. I will close this issue, but feel free to reopen it if you still are interested in a resolution as this issue is almost 3 years old.
