### ISSUE TITLE
Relax mime-types gem pinning

### ISSUE THREAD

**Issue by dLobatog** [Azure/azure-sdk-for-ruby#482]
Hi devs,

I was looking at the latest gemspec and saw that mime-types is pinned to be < 3.0. Is there any reason for it to not be 4.0?

https://github.com/Azure/azure-sdk-for-ruby/blob/azure-v0.7.6/azure.gemspec

The reason I'm asking is that other programs that use this gem might have a dependency on newer mime-types gems. See https://github.com/theforeman/foreman-packaging/pull/1368 for an example.

I wanted to make a pull request myself fixing the dep and running tests, but it seems like the structure of the repository changes when you make a release (and that's when you do the gem pinnings). Anything I could do to fix this feel free to ask.

**Comment by sarangan12** [comment]
Fixes checked in . Closing this issue
