### ISSUE TITLE
Azure gem has hard dependency on JSON 1.8 and fails with newer ruby versions

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-sdk-for-ruby#490]
Azure gem is failing with newer Ruby versions (2.3 and 2.4) that bundle JSON 2.x gem by default because the dependency on JSON 1.8 gem

**Comment by vishrutshah** [comment]
@toddysm Thanks for reporting an issue with the latest version ruby due to JSON dependency. We are looking into it and we'll get back to you soon. 

Thanks for your time.

**Comment by sarangan12** [comment]
Fixes checked in.

**Comment by toddysm** [comment]
Confirmed it is working for us now.
