### ISSUE TITLE
Unable to connect to Graph API

### ISSUE THREAD

**Issue by pms1969** [Azure/azure-sdk-for-ruby#493]
I'm trying to connect to the graph api, and just get a list of applications (or indeed, and other graph api call)  code is as follows

```
require 'azure_mgmt_graph'
require 'openssl'

OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

tenant_id = "<redacted>"
client_id = "<redacted>"
secret = "<redacted>"
subscription_id = "<redacted>"

token_provider = MsRestAzure::ApplicationTokenProvider.new(tenant_id, client_id, secret)
credentials = MsRest::TokenCredentials.new(token_provider)

client = Azure::ARM::Graph::GraphRbacManagementClient.new(credentials)
client.tenant_id = tenant_id

response = client.applications.list

puts response
```

the response I get is 

```
"body": "{\"odata.error\":{\"code\":\"Authentication_MissingOrMalformed\",\"message\":{\"lang\":\"en\",\"value\":\"Access Token missing or malformed.\"},\"date\":\"2016-10-13T11:08:25\",\"requestId\":\"f4603257-4cac-4116-acca-349805de71df\",\"values\":null}}",
```

The same boilerplate code works with the storage api, so I'm pretty sure the service principal has been set up correctly.

Am I missing something obvious?

Cheers

EDIT:  obviously ignore the fact I'm ignoring the SSL certificate validation.  I have another, unrelated(?) problem to do with certificates.  Still searching for the answer to that one.

**Comment by vishrutshah** [comment]
@pms1969 Thanks for reporting an issue. 

Here are few thoughts to try out:

-  Please do not use `OpenSSL::SSL::VERIFY_NONE`. I believe that you are getting certificate error like below: 

```
Faraday::SSLError:
            SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```
We have tried to alleviate certification issue by bundling the certificates with our client runtime. Please use the bundled certificate instead like below:
```
MsRest.use_ssl_cert
```

- Graph scenario requires you to hit the correct authentication endpoint than the default one. Please see the reference spec that i am about to check-in at https://github.com/Azure/azure-sdk-for-ruby/pull/469/commits/dddde5493e6a9be3832fc24ee987f7134a8cef1e#diff-4f9e24110603a3b9653499a0afdc663fR19

More Information regarding configuration for graph can be found at https://msdn.microsoft.com/en-us/library/azure/hh974476.aspx#AppPrereqs 

Please let us know if you are still having trouble getting the graph case working. Thanks for your time.

**Comment by pms1969** [comment]
Thanks.  the use_ssl_cert worked a treat.  I'm still working on the rest.
