### ISSUE TITLE
Utilize gemnasium for dependency checking and hound for static code analysis

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#546]
gemnasium 
https://gemnasium.com/

RuboCop
https://github.com/bbatsov/rubocop
https://houndci.com/

**Comment by veronicagg** [comment]
@vishrutshah Let's transfer this to a doc under documentation folder, so we have it for future reference. Thanks!

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
