### ISSUE TITLE
If you get your virtual machine, the basic virtual machine object does not contain the FQDN of the node. You have to go searching in extensions.

### ISSUE THREAD

**Issue by jkwon2013** [Azure/azure-sdk-for-ruby#567]
cc:
@gregohardy

**Comment by salameer** [comment]
Lets dig into this on the SDK side and figure out if we can surface this info from our side

**Comment by sarangan12** [comment]
@gregohardy, @jkwon2013

Thanks for raising this issue. I have looked into this and summarized my findings below:

1. In the Azure ARM Model, the Virtual Machine - Network Interface - Public IP Address are all independent resources and could be created independently. 

2. After creation, you could associate and disassociate the resources. i.e. it is possible to create a VM and Network Interface without a Public IP address. Then you could create a Public IP Address (with FQDN) and then associate it with the Network Interface (and thus associating it with the VM) 

3. Considering the above 2 points, the FQDN (Fully Qualified Domain Name) is not exactly the property of VM. But, it is the property of the Public IP Address which is associated with the Network Interface which is associated with the VM.  This is the primary reason for the FQDN not appearing in the top level of the VM properties. (Also, this behavior is consistent with the other azure sdks).  

4. Now, there are several ways to get the FQDN of the VM. One simple way is to: 

```
............
............
compute_client                             = ComputeManagementClient.new(credentials)
compute_client.subscription_id  = azure_credentials['SUBSCRIPTION_ID']
test_vm                                         = compute_client.virtual_machines.get rg_name, vm_name
test_vm_nic_ref                            = test_vm.network_profile.network_interfaces[0]
test_vm_nic_name                       = get_nic_name test_vm_nic_ref

network_client                             = NetworkManagementClient.new(credentials)
network_client.subscription_id  = azure_credentials['SUBSCRIPTION_ID']
test_vm_nic                                 = network_client.network_interfaces.get rg_name, test_vm_nic_name
public_ip_name                           = get_ip_name test_vm_nic 
public_ip                                      = network_client.public_ipaddresses.get rg_name, public_ip_name

puts "VM Name: #{vm_name} - FQDN: #{public_ip.dns_settings.fqdn}"
..........
..........
```

5. Now, if the FQDN is such a common property used major number of times, this could be added at the top in the future. But, at this point, I do not see the necessity to warrant such inclusion. 

Please share your thoughts.

**Comment by sarangan12** [comment]
This is also related to the issue https://github.com/Azure/azure-sdk-for-ruby/issues/279 Since we are tracking the similar issue, I am closing this issue.
