### ISSUE TITLE
Build Reference Architecture sample of IaaS Ruby on Rails applications / DevOps flow

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#586]
Include CDN, Load Balancers, multi-vm or multi-container setups, key vault
Target Azure SQL using tiny-tds db gem
Optionally, include DocDB, Azure Search, Cognitive Services, Media Services, etc…

**Comment by sarangan12** [comment]
Moving this to backlog for now.

**Comment by salameer** [comment]
This is not a service team issue, removing the ARM tag, this will get routed to the ARM team for attention

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
