### ISSUE TITLE
Proposal for moving service_bus dataplane from azure to azure_sdk

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#587]

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
