### ISSUE TITLE
[Telemetry] Investigate how to categorize usage of azure-storage via azure_sdk 

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#597]
Find out number of calls made to Azure Storage Endpoint via out top level azure_sdk gems.

**Comment by sarangan12** [comment]
Moving this to backlog

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
