### ISSUE TITLE
environment names for AzureCloud and AzureChinaCloud do not match the names in azure-cli and azure-powershell

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-sdk-for-ruby#600]
`Azure` and `AzureChina` are used in below code. But in [azure-cli](https://github.com/Azure/azure-xplat-cli/blob/bea341b53149246fb61b95883aa34b72a7e980f2/lib/util/profile/environment.js) and [azure-powershell](https://github.com/Azure/azure-powershell/blob/2eaf6175bc2533b83689120dc7f595ff0bdf8001/src/Common/Commands.Common.Authentication/Models/AzureEnvironment.Methods.cs), they are `AzureCloud` and `AzureChinaCloud`.

https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/azure_environment.rb#L88-L123

**Comment by AbelHu** [comment]
typo in azure_environment:
`storage_endpoing_suffix` => `storage_endpoint_suffix`

**Comment by sarangan12** [comment]
Names changed in the runtime and will be released in the next version of the runtime. Closing this task now.
