### ISSUE TITLE
Support connecting to multiple storage accounts in a single process

### ISSUE THREAD

**Issue by slumos** [Azure/azure-sdk-for-ruby#61]
We have a need to connect to more than one storage account at a time.  Storing configuration in a singleton class inside a module makes that really difficult to accomplish.  There are many common use cases for this.  Consider a Rails version of http://storageexplorer.cloudapp.net/, or even a simple cron process that copies blobs from one account to another.

**Comment by atistler** [comment]
+1 one this.  There is no reason why configuration should be a singleton.  Need a nicer way to talk to multiple azure subscriptions.
