### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by devigned** [Azure/azure-sdk-for-ruby#611]
The SDK should work with an application's logger and should probably fit the interface of http://ruby-doc.org/stdlib-2.1.0/libdoc/logger/rdoc/Logger.html.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
