### ISSUE TITLE
Azure Recovery Services Backup ProtectedItems

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [Azure/azure-sdk-for-ruby#644]
Hi @vishrutshah 

I am using the `ProtectedItems` method `list` to list all items in a subscription that can be listed. I am using the following script for this purpose
```
require 'azure_mgmt_recovery_services_backup'

subscription_id = '########-####-####-####-############'
provider = MsRestAzure::ApplicationTokenProvider.new('########-####-####-####-############',
                                                     '########-####-####-####-############',
                                                     '############################################'
)
credentials = MsRest::TokenCredentials.new(provider)

recovery_services = Azure::ARM::RecoveryServicesBackup::RecoveryServicesBackupClient.new(credentials)
recovery_services.subscription_id = subscription_id

puts recovery_services.protected_items.list('TestVault', 'TestRG-RV').inspect
```

On the Azure Portal I have a recovery vault `TestVault` which has a protected vm item `testvm-windows`. There is also an unprotected vm item `testvm-ubuntu` which exists in the subscription. According to the documentation the `list` method should display the item that can be protected i.e. `testvm-ubuntu`. However, this method returns an empty array.

What is the functionality of the `list` method of the service? Why does it not display the items that can be protected in the subscription?

Thanks

**Comment by vishrutshah** [comment]
@bilal-naeem-confiz Thanks you very much for reporting this issue. 

@markgalioto / @dragonfly91 Could you please throw some light on understanding of `ProtectedItems` and why `list` doesn't show all the items?

**Comment by bilal-naeem-confiz** [comment]
Hi @vishrutshah 

Is there any update on this issue?

**Comment by dragonfly91** [comment]
Hi @bilal-naeem-confiz 

The VM has to be in the same region as that of the vault in order to be protectable by the Vault. Can you check if the vault and the VM are in the same location / region?

**Comment by bilal-naeem-confiz** [comment]
Hi @dragonfly91 

Yes the VM and the Recovery Vault are in the same location `eastus`

**Comment by vishrutshah** [comment]
@dragonfly91 Ping...

**Comment by vishrutshah** [comment]
Moving to milestone `v0.10.0-arm` as we are waiting from service team.

**Comment by bilal-naeem-confiz** [comment]
Hi @vishrutshah 
Is there any update on this issue?

**Comment by vishrutshah** [comment]
@dragonfly91 Do we have any updates on this for customer from service side?

**Comment by bilal-naeem-confiz** [comment]
So I inspected the latest code that is available and the `list` method has been removed for `ProtectedItems`. Instead I used `list` method for `BackupProtectedItems` which returns a list of all items that can be backed up which are added to the recovery vault.
