### ISSUE TITLE
Azure Recovery Services Backup ProtectionPolicy

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [Azure/azure-sdk-for-ruby#646]
Hi @vishrutshah 

I am using the `ProtectionPolicies` method `list` to list all protection policies in a Recovery Vault. The script I am using is the following
```
require 'azure_mgmt_recovery_services_backup'

subscription_id = '########-####-####-####-############'
provider = MsRestAzure::ApplicationTokenProvider.new('########-####-####-####-############',
                                                     '########-####-####-####-############',
                                                     '############################################'
)
credentials = MsRest::TokenCredentials.new(provider)

recovery_services = Azure::ARM::RecoveryServicesBackup::RecoveryServicesBackupClient.new(credentials)
recovery_services.subscription_id = subscription_id

puts recovery_services.protection_policies.list_as_lazy('TestVault', 'TestRG-RV').inspect
```

This script gives me a list of the policies of the vault `TestVault` in the resource group `TestRG-RV`

The problem that occurs is that I have a VM `TestVM` which is associated with the `DefaultPolicy` which is present in the `TestVault`. However, the attribute `protected_items_count` remains at 0. I have enabled protection for that VM using this policy, but the attribute remains unchanged.

Is there some way to refresh the policy item count so that it displays the correct number of protected items? Is there some way to fix this problem?

Thanks

**Comment by bilal-naeem-confiz** [comment]
Hi @vishrutshah 

Is there any update on this issue?

**Comment by vishrutshah** [comment]
Moving to milestone `v0.10.0-arm` as we are waiting from service team.

**Comment by bilal-naeem-confiz** [comment]
Hi @vishrutshah 
Is there any update on this issue?

**Comment by vishrutshah** [comment]
@bilal-naeem-confiz  Sorry for the significant delays here. Let me follow up with team internally.

**Comment by bilal-naeem-confiz** [comment]
The `list` method has been removed from `ProtectionPolicies`. Using the `list` method available in `BackupPolicies` gives me what I want. Since the method which was causing the issue is no longer present, I am closing this issue.
