### ISSUE TITLE
Azure Recovery Services Backup Job Supported Actions Enum

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [Azure/azure-sdk-for-ruby#650]
Hi @vishrutshah 

I am using `azure_mgmt_recovery_services_backup` to list all the jobs of a vault. The script I am using is the following
```
require 'azure_mgmt_recovery_services_backup'

subscription_id = '########-####-####-####-#############'
provider = MsRestAzure::ApplicationTokenProvider.new('########-####-####-####-#############',
                                                     '########-####-####-####-#############',
                                                     '############################################'
)
credentials = MsRest::TokenCredentials.new(provider)

recovery_services = Azure::ARM::RecoveryServicesBackup::RecoveryServicesBackupClient.new(credentials)
recovery_services.subscription_id = subscription_id

puts recovery_services.jobs.list('TestVault', 'TestRG-RV').inspect
```

This successfully lists all the jobs of the specified recovery vault. However, the enum attribute of `JobResource`, which is `actions_info` can accept the following values `Invalid`, `Cancellable` and `Retriable`. The server, on the other hand, returns the enum value of `1` which is not supported by the attribute. This is the warning which is received on the console
```
Enum does not contain 1, but was received from the server.
```

Kindly fix this issue so that the server returns the appropriate enum value for the attribute `actions_info`

Thanks

**Comment by vishrutshah** [comment]
@bilal-naeem-confiz Thank for reporting this issue. This looks like an inconsistency between API implementation and [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-recoveryservicesbackup/2016-06-01/swagger/recoveryservicesbackup.json). 

@dragonfly91 /@markgalioto Could please take a look at this.

**Comment by bilal-naeem-confiz** [comment]
Hi @vishrutshah 

Is there any update on this issue?

**Comment by vishrutshah** [comment]
Hi @bilal-naeem-confiz, 

Thanks for the reminder. I've reached out to the team working on Azure Recovery Back Services internally and they are looking into each of these and we should be hearing back soon from them regarding each of the Azure Recovery Back Services related issues. 

We apologize for the delay. Please stay tuned. Thanks for your patience. 

//cc:
@dragonfly91

**Comment by vishrutshah** [comment]
Moving to milestone `v0.10.0-arm` as we are waiting from service team.

**Comment by sarangan12** [comment]
Hi @bilal-naeem-confiz 

I looked into your issue and when I run the code through ruby sdk, I am not getting 1 in the actions_info. Could you please verify again and let me know

**Comment by bilal-naeem-confiz** [comment]
I tried the code again with the latest version of the gem and I am no longer getting the warning. Closing this issue now.
