### ISSUE TITLE
Documentation for azure_mgmt_event_hub 

### ISSUE THREAD

**Issue by yoannbi** [Azure/azure-sdk-for-ruby#669]
Hi,
There is no documentation or sample for (azure_mgmt_event_hub) => http://www.rubydoc.info/gems/azure_mgmt_event_hub/0.8.0/
Do you know where i can find it?

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
