### ISSUE TITLE
Evaluate auto-regenerating sdks when AutoRest Ruby generator is changed

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#677]
When AutoRest Ruby generator gets updated, automatic PRs (due to swagger changes) regenerate some sdks with the latest build, though other sdks aren't regenerated. This causes ruby-sdks in master to be in somewhat a half-state, and usually gets fixed only when we manually regenerate all sdks before release. 
We may want to create a job that submits an automatic PR with all regenerated sdks when ruby generator files in autorest are changed.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
