### ISSUE TITLE
Add mechanism to sync azure_mgmt_* versions and swagger_to_sdk versions

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#683]
In the release process, we have missed couple of times to update the versions of azure_mgmt_* sdks from [ARM_VERSION](https://github.com/Azure/azure-sdk-for-ruby/blob/master/ARM_VERSION) but the same file is not used for [swagger_to_sdk_config.json](https://github.com/Azure/azure-sdk-for-ruby/blob/master/swagger_to_sdk_config.json).

Most likely, we should add a task in rakefile to re-generate swagger_to_sdk_config.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
