### ISSUE TITLE
is ruby sdk use eventprocessorhost ?

### ISSUE THREAD

**Issue by yoannbi** [Azure/azure-sdk-for-ruby#718]
Hi, 
Is the sdk use eventprocessorhost with queue & lease ?
like this => https://github.com/Azure/azure-event-hubs-java/tree/e6413d059471d75224a62df89251c5dfd331f5e2/azure-eventhubs-eph

**Comment by sarangan12** [comment]
@yoannbi 

No. We do not use the eventprocessor host for the Ruby SDK
