### ISSUE TITLE
Application Gateways are created with a Provisioning State of Failed 

### ISSUE THREAD

**Issue by jjiadev** [Azure/azure-sdk-for-ruby#739]
ARM Issue
When I used the SDK to create an Application Gateway, the gateway is created with a Provisioning State of Failed. Resaving this gateway with the same information from the Azure Portal results in a Successful gateway.

**Comment by sarangan12** [comment]
An ICM 37292568 has already been opened. Jimmy Raiford is working with the customer. The fix has been rolled out yesterday. Once We get the confirmation, we will close the issue

**Comment by sarangan12** [comment]
The issue has been resolved and confirmed by the customer. Closing it
