### ISSUE TITLE
[Help] Creating VM Image from already uploaded VHD

### ISSUE THREAD

**Issue by balasankarc** [Azure/azure-sdk-for-ruby#754]
I am trying to create a VM Image from an already uploaded VHD. I was able to use `create_or_update` to create an ImageOSDisk from VHD and using that, an image. But, apparently, to deploy a VM from it, the option "type: fromImage" needs to be specified while creating the image. But ImageOSDisk doesn't have that option, only OSDisk does. I can't use OSDisk because it doesn't have the "os_state" property, which is required for `create_or_update`. Do you know any solution out of this?

This is the code I am using
```ruby
require 'azure_mgmt_compute'
include Azure::ARM::Compute
include Azure::ARM::Compute::Models
------------------------------------------------------------------------------------

  def process
    vhd = <blob url of the vhd>
    resource_group_name = <resource group name>
    client = ComputeManagementClient.new(credentials)

    image = Image.new
    image.location = "East US"
    storage_profile = StorageProfile.new

    ref = ImageReference.new
    ref.publisher = 'Canonical'
    ref.offer = 'UbuntuServer'
    ref.sku = '16.04-LTS'
    storage_profile.image_reference = ref

    os_disk = ImageOSDisk.new
    os_disk.blob_uri = vhd
    os_disk.os_type = "Linux"
    os_disk.os_state = "Generalized"
    storage_profile.os_disk = os_disk

    image.storage_profile = storage_profile
    client.images.create_or_update(resource_group_name, "Image Name", image)
  end
```

**Comment by puneetloya** [comment]
Do you have to mention ImageReference? I was able to create an image without it.

**Comment by veronicagg** [comment]
Closing issue, as there wasn't a response. If you're still encountering this issue, feel free to reopen. Thanks.
