### ISSUE TITLE
Examples for creating a load balancer?

### ISSUE THREAD

**Issue by lcc2207** [Azure/azure-sdk-for-ruby#776]
Are there any examples of creating load balancers?

I keep getting errors 

'},
  "response": {
    "body": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidRequestFormat\",\r\n    \"message\": \"Cannot parse the request.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"MissingJsonReferenceId\",\r\n        \"message\": \"Value for reference id is missing. Path properties.frontendIPConfigurations[0].properties.subnet.\"\r\n      }\r\n    ]\r\n  }\r\n}",
    "headers": {'

**Comment by robsonalves** [comment]
Same Error with probes, I Tried much solutions, but not solved...

I make this variable
` "vmssLBId": "[resourceId('Microsoft.Network/loadBalancers', variables('vmssLoadBalancerName'))]",`
` "vmssLoadBalanceProbesConfig": "[concat(variables('vmssLBId'),'/probes/',variables('vmssLoadBalanceRDPProbeName'))]"`

In the load balancer I put the informations id in LoadBalancer.
` "loadBalancingRules": [
          {
            "name": "[variables('vmssRDPLoadBalancerRule')]",
            "properties": {
              "frontendIPConfiguration": {
                "id": "[variables('vmssLoadBalanceFrontEndConfigID')]"
              },
              "backendAddressPool": {
                "id": "[variables('vmssLoadBalancerBackEndID')]"
              },
              "protocol": "Tcp",
              "frontendPort": 3389,
              "backendPort": 3389,
              "enableFloatingIP": false,
              "probe": {
                "id": "[variables('vmssLoadBalanceProbesConfig')]"
              }
            }
          }
        ],
        "probes": [
          {
            "name": "[variables('vmssLoadBalanceRDPProbeName')]",
            "properties": {
              "intervalInSeconds": 15,
              "numberOfProbes": 2,
              "port": 339,
              "protocol": "Tcp"
            }
          }
        ]`

**Comment by sarangan12** [comment]
@lcc2207 @robsonalves 

Here is a simple code snippet that I used to create a bare bones load balancer:


```
require 'yaml'
require 'azure_mgmt_network'

include Azure::ARM::Network
include Azure::ARM::Network::Models

azure_credentials               = YAML.load_file 'config/azure_credentials.yml'
rg_name                         = 'testissue567rg'

token_provider                  = MsRestAzure::ApplicationTokenProvider.new(azure_credentials['TENANT_ID'], azure_credentials['CLIENT_ID'], azure_credentials['SECRET'])
credentials                     = MsRest::TokenCredentials.new(token_provider)
network_client                  = NetworkManagementClient.new(credentials)
network_client.subscription_id  = azure_credentials['SUBSCRIPTION_ID']

load_balancer                   = LoadBalancer.new
load_balancer.location          = 'westus'

network_client.load_balancers.create_or_update(rg_name, 'testLB776', load_balancer)
```

I am able to create the LB without any issues. Please use similar code to create LB and if you still have any issues please report back with a code snippet that you use. (code snippet that I can use to test - so please make sure to provide all the details and execution steps if necessary)

**Comment by sarangan12** [comment]
Closing this now. If you still have issues, feel free to reopen the issue
