### ISSUE TITLE
Documentation for Service Bus Queues

### ISSUE THREAD

**Issue by sadikay** [Azure/azure-sdk-for-ruby#779]
Hi,
There is no documentation for service bus queues.
This one have some errors. [https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-ruby-how-to-use-queues](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-ruby-how-to-use-queues)

**Comment by sarangan12** [comment]
@sadikay 

Yes. The documentation has problems. You can use the following code that will work:

```
require 'azure'

Azure.configure do |config|
  config.sb_namespace    = 'YOUR_NAMESPACE'
  config.sb_sas_key_name = 'YOUR_SAS_KEYNAME'
  config.sb_sas_key      = 'YOUR_SAS_KEY'
end

signer = Azure::ServiceBus::Auth::SharedAccessSigner.new
sb_host = "https://#{Azure.sb_namespace}.servicebus.windows.net"
sbs = Azure::ServiceBus::ServiceBusService.new(sb_host, { signer: signer})

queue = sbs.create_queue('test-queue')
```

I will work with the documentation team to get the docs fixed.
