### ISSUE TITLE
Service bus connection failing.

### ISSUE THREAD

**Issue by hail2skins** [Azure/azure-sdk-for-ruby#782]
All.  Following the Microsoft example at https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-ruby-how-to-use-topics-subscriptions or trying with the code you guys provide at https://github.com/Azure/azure-sdk-for-ruby/tree/asm#topics when I create a topic I get an immediate error:

2.4.1 :011 > topic = azure_service_bus_service.create_queue("test-topic")
Faraday::ConnectionFailed: Failed to open TCP connection to NAME-sb.accesscontrol.windows.net:443 (getaddrinfo: Name or service not known)

I saw some past threads about this and I am not using the classic portal at all.   The example above is even a Powershell ARM created namespace.   I saw a recent note in the PHP SDK thread saying they are having the same problem.

https://github.com/Azure/azure-sdk-for-php/issues/917

Any ideas what may have happened?   I know SAS is my authentication method.

**Comment by hail2skins** [comment]
As a possibly helpful note, I can create topics with Powershell:

New-AzureRmServiceBusTopic -ResourceGroup Spike-AMQP -NamespaceName NAME -topicname powershell-test-topic -EnablePartitioning $true

That is confirmed to create the topic.

**Comment by sarangan12** [comment]
require 'azure'

Azure.configure do |config|
  config.sb_namespace    = 'YOUR_NAMESPACE'
  config.sb_sas_key_name = 'YOUR_SAS_KEYNAME'
  config.sb_sas_key      = 'YOUR_SAS_KEY'
end

signer = Azure::ServiceBus::Auth::SharedAccessSigner.new
sb_host = "https://#{Azure.sb_namespace}.servicebus.windows.net"
sbs = Azure::ServiceBus::ServiceBusService.new(sb_host, { signer: signer})

queue = sbs.create_queue('test-queue')
I will work with the documentation team to get the docs fixed.

**Comment by hail2skins** [comment]
Thank you.   I wound up going back around to a few different older documents.   Wound up writing:

require 'azure'

sb_key_name = "RootManageSharedAccessKey"

sb_key = "MYKEYHERE"

signer = Azure::ServiceBus::Auth::SharedAccessSigner.new(sb_key_name, sb_key)

sb_host = "https://MYNAMEHERE.servicebus.windows.net"

sb = Azure::ServiceBus::ServiceBusService.new(sb_host, { signer: signer })

sb.create_topic("test-topic-1")

And that worked too.   So it just appears I got confused by the fact the documents are looking for ACS connections being there.   It would be helpful if you can update docs, but enough internet searching works :).
