### ISSUE TITLE
Waiting new messages from service bus queue continuously

### ISSUE THREAD

**Issue by sadikay** [Azure/azure-sdk-for-ruby#783]
I m getting the queue message by following code:

`message = sbs.receive_queue_message("test-queue", { :peek_lock => false })`

It listens about 60 seconds then get time out. I'd like to do it in listener to process the messages without break the listener. It means after get the new message `receive_queue_message` could be renew itself and wait for new message without time out.

**Comment by veronicagg** [comment]
@sadikay we're not actively working on Service Bus code from azure gem, feel free to send us a PR to address this issue, we'd be happy to review it.

**Comment by sarangan12** [comment]
@sadikay You can reopen the issue if you are planning to submit the PR. Closing the issue
