### ISSUE TITLE
List Classic Images via azure-sdk for ruby

### ISSUE THREAD

**Issue by puneetloya** [Azure/azure-sdk-for-ruby#787]
I tried out the compute APIs for image listing, it was not able to find my image. I think its an expected behavior.

I still need a way to get the classic images list and tagged. Can someone help me out here?

The image type I need is 'Microsoft.ClassicStorage/storageAccounts/images'

**Comment by sarangan12** [comment]
@puneetloya 

You could use the asm (https://github.com/Azure/azure-sdk-for-ruby/tree/asm) to get the classic VMs. The recommendation is to move from classic VMs to ARM. 

Please try that out and let us know if there are any issues.

**Comment by puneetloya** [comment]
am trying to list classic Images not VMs. Another question, these images are actually VHDs. Can we tag VHDs?
