### ISSUE TITLE
Be able to create Azure object to have multiple connections and settings

### ISSUE THREAD

**Issue by evanwieren** [Azure/azure-sdk-for-ruby#80]
I am working on an application that has connections to multiple accounts at the same time. With global parameters this is a chore. 

Using the API for .net, I am not bound by this constraint. 

The main desire is not to be stuck with a single Azure object that is held for my entire app, but that I can manipulate for changing needs.

**Comment by atistler** [comment]
+1

**Comment by devigned** [comment]
Done in 0.7.0.pre
