### ISSUE TITLE
Move to swagger-to-sdk version 2.0

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#826]
[swagger-to-sdk](https://github.com/lmazuel/swagger-to-sdk) has been released with version 0.2.0 to support upcoming markdown changes. 

As per the current plan, on July 10  [azure-rest-api-specs](https://github.com/azure/azure-rest-api-specs) repository would move to new structure. To keep our CI system running we need to move to version 0.2.0.

**Comment by sarangan12** [comment]
Task Completed with PR https://github.com/Azure/azure-sdk-for-ruby/pull/848
