### ISSUE TITLE
What gem to use ?

### ISSUE THREAD

**Issue by dixpac** [Azure/azure-sdk-for-ruby#837]
Hey 👋 

What gem to use for azure storage `azure-sdk-for-ruby(azure_mgmt_storage)` or `azure-storage-ruby`.
What is the difference between these two ?

Thanks

**Comment by yaxia** [comment]
1. `azure_mgmt_storage` is for storage account management. You can create, delete, list and modify your storage accounts and `azure-storage` is for data (blob/table/queue/file) management under a storage account.
2. Comparing to the [asm](https://github.com/Azure/azure-sdk-for-ruby/tree/asm) branch of `azure-sdk-ruby`, `azure-storage` has more client side improvements and actively maintains the feature parity with those on the service. Please refer to #5 for details.
