### ISSUE TITLE
:management_endpoint should default to https://management.core.windows.net

### ISSUE THREAD

**Issue by Blackmist** [Azure/azure-sdk-for-ruby#84]
Currently (dev branch) to use any of the service management functionality (VMs, cloud services, storage services,) you must manually specify the management endpoint either via code or by setting an environment variable. For 95% of our customers, the correct value is going to be https://management.core.windows.net, so we should simply default to this. If something else is specified in code or env, then we should use that instead of the default.

**Comment by devigned** [comment]
If this is still an issue, please reopen.
