### ISSUE TITLE
create_block_blob doesn't accept an IO object?

### ISSUE THREAD

**Issue by jdelStrother** [Azure/azure-sdk-for-ruby#86]
Hi, I don't know if I'm missing something obvious, but the documentation claims that create_block_blob can accept either a String or an IO for the content parameter.

If I pass a File or IO object, I get `undefined method bytesize for #<File:public/favicon.ico>` from here - https://github.com/WindowsAzure/azure-sdk-for-ruby/blob/master/lib/azure/core/http/http_request.rb#L104.   In addition, the following line calls `Digest::MD5.digest(body)`, which I don't think works on IO objects.

Am I missing some way of uploading IO objects, or do I have to read the entire file into memory?

**Comment by devigned** [comment]
Added in a large refactor: #248
