### ISSUE TITLE
Missing shortcut for VirtualMachineDiskManagementService

### ISSUE THREAD

**Issue by Blackmist** [Azure/azure-sdk-for-ruby#88]
azure.rb contains lines similar to the following that make it easier/less verbose to work with management classes:

    Azure::VirtualMachineImageService = Azure::VirtualMachineImageManagement::VirtualMachineImageManagementService
    Azure::BaseManagementService = Azure::BaseManagement::BaseManagementService
    Azure::CloudService = Azure::CloudServiceManagement::CloudServicesManagementService

Currently there’s not a shortcut class for working with disk management like there is for images/vms/cloud services. They’re still accessible using Azure::VirtualMachineImageManagement::VirtualMachineDiskManagementService, but it seems to break the pattern we’re using with everything else.

**Comment by devigned** [comment]
Refactored the api to be more concise. Azure.blobs will return a blobs service rather than having to build services. This was done in a large refactor: #248
