### ISSUE TITLE
Enable Managed Service Identity features into ms-rest-azure runtime for azure_mgmt_* sdks

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#884]
**Introduction:**

The Managed Service Identity (MSI) scenarios enable an Azure VM to autonomously, using its own managed identity, to directly authenticate and interact with other Azure services using short-lived bearer tokens.  The life cycle of this identity is tied to the overall lifecycle of the VM itself

The Managed Service Identity infrastructure is presently deployed in all public cloud Azure regions, however, National Clouds are not yet enabled for MSI.

**Goal:**

Applications using [azure-mgmt_* ](https://rubygems.org/search?utf8=%E2%9C%93&query=azure_mgmt_) sdks, should be able to indicate to use new mechanism for acquiring the `access_token` & `refresh_token` and communicate subsequent resource requests based on that authentication & scope restrictions. 

**Design:**

Currently, `ApplicationTokenProvider` is being used to acquire `access_token` & `refresh_token` for the given [ActiveDirectoryServiceSettings](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/credentials/application_token_provider.rb#L49) with the `resource_uri` being supplemented by [token_audience](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/credentials/application_token_provider.rb#L99).

In the new MSI flow, we'd create a new token provider named as `MSITokenProvider` with potential constructor parameters as `tenant_id`, `port` & `settings`. The parameters `settings` would have default value of `MSIActiveDirectoryServiceSettings.get_azure_settings` & `port` would have default value of `50342`. Based on this information, we'll make following request using `Faraday`

_Request:_

Method:  `POST`
URL: `http://localhost:{port}/oauth2/token`
Data: `authority=https://login.microsoftonline.com/{tenant_id}&&resource={resource_id}`

_Response:_
```json5
{
    "access_token": "access_token",
    "refresh_token": "refresh_token",
    "expires_in": "3600",
    "expires_on": "1502295751",
    "not_before": "1502291851",
    "resource": "http://management.azure.com",
    "token_type": "Bearer"
}
```

**Usage:**
```ruby
MsRest::TokenCredentials.new(
            MsRestAzure::MSITokenProvider.new(
                {tenant_id}, {port}, {active_directory_settings}))
```

**Test:**
We'll be covering the unit test around this new token provider to validate the expectations and functional tests would be covered in samples we'll be writing to validate end-to-end scenarios.

@veronicagg @sarangan12 @devigned Feel free to throw your thoughts and ideas here for MSI feature :)

**Comment by veronicagg** [comment]
@vishrutshah Thanks for writing this up. 
Few questions: 
- Is port number `50342` being given to us as the default port to use for this?
- Flow wise, do we need to make a call to obtain the token from Azure first and then subsequent calls to the port return the same (previously obtained) token?
- Will we be modifying any code to try to make use of this first, and if this is not available, call the `ApplicationTokenProvider`?

**Comment by vishrutshah** [comment]
Thanks @veronicagg for reviewing. Good questions. Here are the answers:

1. Is port number 50342 being given to us as the default port to use for this?
**ans**: Yes, by default `50342` port at which authentication provider service would be running. There are ways VM creator can choose to use different port to run the service, so we'll be asking then as an optional parameter while create `MSITokenProvider`

2. Flow wise, do we need to make a call to obtain the token from Azure first and then subsequent calls to the port return the same (previously obtained) token?
**ans**: Nope. When user says their intention is to use "Managed Service Identity" features into their application, we do not need to talk to Azure to acquire token. We always go to `http://localhost:{port}/oauth2/token` to retrieve token. If we cannot get retrieve it we fail authentication. 

3. Will we be modifying any code to try to make use of this first, and if this is not available, call the ApplicationTokenProvider?
**ans**: Nope, `ApplicationTokenProvider` is not a fallback option for us when user's intention is to use "Managed Service Identity". We'll be creating new provider whose sole responsibility is to acquire token from "Managed Service Identity" service running on that machine. 

Let me know if anything doesn't make sense or needs more info :)

**Comment by vishrutshah** [comment]
Closing this as feature complete!
