### ISSUE TITLE
Provide customer samples to use managed service identity features

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#885]
The sample should target following scenarios:

- [x] create a VM with a system assigned identity
- [x] install the MSI extension on the VM
- [x] assign RBAC permissions to the managed identity
- [x] create another resource (storage account, vnet etc) using the token from the MSI identity

**Comment by veronicagg** [comment]
If we have a way to default or detect that we're in an MSI environment, and default to that token, we may want to have a scenario that simulates it and shows that behavior. thanks!

**Comment by vishrutshah** [comment]
I see that's a great point. Let me follow up with the other team and see if we can detect and does defaulting makes sense of all application scenarios or we can let app builder decide that.

**Comment by vishrutshah** [comment]
This sample has been **delayed** by computer server side changes on how MSI authentication works. 

Related Issue #930 #949

**Comment by vishrutshah** [comment]
Completed.
