### ISSUE TITLE
Reconsider VM create/delete logic

### ISSUE THREAD

**Issue by Blackmist** [Azure/azure-sdk-for-ruby#89]
While I like the functionality of creating or deleting a vm provided by https://github.com/WindowsAzure/azure-sdk-for-ruby/blob/dev/lib/azure/virtual_machine_management/virtual_machine_management_service.rb, the current implementation causes some non-trivial problems:

1. creating or deleting a vm is a multi-stage operation that creates/deletes a storage account, a disk in the storage account, a cloud service, and deployment. This is all performed synchronously, so the call blocks for minutes.
2. if something breaks halfway through, such as you've provided a password for the VM that doesn't meet security requirements, the call fails and you're left with whatever was created up to that step. Like the storage account that was created with randomly generated characters as part of the name.
3. there's no option to delete a VM, yet retain the disk for later use.

I would recommend implementing the core functionality following the REST API, where we make the call, get a request ID, and then can use that to retrieve the status of a call. Expose that to users. Then use that to build a convenience method that does all the bits (storage, disk, vm) on top of those, but it should have the ability to roll-back artifacts created automatically if it fails. Such as storage accounts with random names.

**Comment by devigned** [comment]
If you feel this is still an issue, please reopen.
