### ISSUE TITLE
Multi-api-version: create script to collect files for code generation

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#903]
Create a script (or include in rakefile) to get files from github up to the "resource-manager folder, grouped by versions.
Have it output a json with grouping and files that are in each group.
Would call autorest --input-file=<file1> --input-
file=<file2>... (check that client name gets picked up from readme file)

- keep version in the rakefile for each sdk

**Comment by veronicagg** [comment]
If we want this, we'll need to account for exclusions as there are some api-version that we're not shipping due to telemetry or generation issues.

**Comment by sijuman** [comment]
Is this still needed? @veronicagg

**Comment by veronicagg** [comment]
@mozehgir not sure why this was labeled with "Azure Stack" or "Service Attention", this is an SDK generation engineering task. 
@sijuman actually @sarangan12 is curently working on items to fully automate code generation, so this may get included as part of that. @sijuman may I know the reason for your question? thanks!

**Comment by mozehgir** [comment]
@veronicagg : seems like it was incorrectly tagged. Not a customer issue.

**Comment by sijuman** [comment]
@veronicagg Reason for my question is that I am doing GitHub Azure Stack cleanup and wanted to see what this was in relation to.

**Comment by veronicagg** [comment]
@sijuman ok, I think we answered the question since I removed the label. thanks!

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
