### ISSUE TITLE
Multi-api-version: update swagger_to_sdk.config

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#904]
Update swagger_to_sdk.config to work with the new structure

**Comment by vishrutshah** [comment]
I've talked with Laurent and discussed how we should update our swagger_to_sdk to enable the CI pipeline. 

Overall, I'll refer the python's structure https://github.com/Azure/azure-sdk-for-python/blob/master/swagger_to_sdk_config.json#L83 to enable for Ruby.

I am working on this to update our CI and test it out but overall, based on our discussion that it pretty feasible and supported by swagger_to_sdk version `2.0`

**Comment by vishrutshah** [comment]
Closing this task as completed and pushed to the `azure-stack` branch
