### ISSUE TITLE
[CUSTOMER QUESTION] - Data Lake Store Account Creation

### ISSUE THREAD

**Issue by ro-joowan** [Azure/azure-sdk-for-ruby#933]
From: https://social.msdn.microsoft.com/Forums/azure/en-US/e77524ad-3401-4714-bd66-63ba80b95e32/data-lake-store-azure-sdk-ruby?forum=AzureDataLake

#<Azure::ARM::DataLakeStore::Models::DataLakeStoreAccount:0x005580c6e71ea8
@name="testdlsabc",
@location="East US 2",
@type=nil,
@properties=
#<Azure::ARM::DataLakeStore::Models::DataLakeStoreAccountProperties:0x005580c6e68060
@encryption_state="Enabled",
@encryption_config=
#<Azure::ARM::DataLakeStore::Models::EncryptionConfig:0x005580c6e64230
@type="UserManaged",
@key_vault_meta_info=
#<Azure::ARM::DataLakeStore::Models::KeyVaultMetaInfo:0x005580c6e60018
@key_vault_resource_id="/subscriptions/<Subscription_ID here>/resourceGroups/TestRG-ZN/providers/Microsoft.KeyVault/vaults/testdlskey",
@encryption_key_name="dlskey",
@encryption_key_version="<Key Version 32 lenght>"
>>>>

This is the object i'm passing to the SDK for the creation of Data Lake Store Account but i'm getting this error

Invalid parameters: Payload.EncryptionConfig.MsiSecretUri

**Comment by sarangan12** [comment]
I have used the following code to test this out:

```
require 'yaml'
require 'azure_mgmt_datalake_store'

include Azure::ARM::DataLakeStore
include Azure::ARM::DataLakeStore::Models

azure_credentials               = YAML.load_file 'config/azure_credentials.yml'
rg_name                         = 'testissue567rg'

token_provider                  = MsRestAzure::ApplicationTokenProvider.new(azure_credentials['TENANT_ID'],
                                                                            azure_credentials['CLIENT_ID'],
                                                                            azure_credentials['SECRET'])
credentials                     = MsRest::TokenCredentials.new(token_provider)

datalake_store_client           = DataLakeStoreAccountManagementClient.new(credentials)
datalake_store_client.subscription_id = azure_credentials['SUBSCRIPTION_ID']

datalake_store_account_properties = DataLakeStoreAccount.new
datalake_store_account_properties.location = 'East US 2'
datalake_store_account_properties.firewall_state   = FirewallState::Enabled
datalake_store_account_properties.firewall_allow_azure_ips = FirewallAllowAzureIpsState::Enabled
firewall_rule = FirewallRule.new
firewall_rule.name = 'one'
firewall_rule.start_ip_address = '127.0.0.1'
firewall_rule.end_ip_address   = '127.0.0.1'
firewall_rules = [firewall_rule]
datalake_store_account_properties.firewall_rules = firewall_rules
datalake_store_account_properties.encryption_state = EncryptionState::Enabled
encryption_config = EncryptionConfig.new
encryption_config.type = EncryptionConfigType::UserManaged
keyvault_meta_info = KeyVaultMetaInfo.new
keyvault_meta_info.key_vault_resource_id  = '<YOUR_RESOURCE_ID>'
keyvault_meta_info.encryption_key_name    = '<YOUR_KEY_NAME>'
keyvault_meta_info.encryption_key_version = '<YOUR_ENCRYPTION_KEY_VERSION>'
encryption_config.key_vault_meta_info = keyvault_meta_info
datalake_store_account_properties.encryption_config = encryption_config
datalake_store_client.account.create(rg_name, 'testdlaccount', datalake_store_account_properties, nil)
```

I am getting the same error from the service. This is a service side issue and not a SDK issue.

**Comment by sarangan12** [comment]
I have spoken with @ro-joowan and confirmed that this is a service side issue. SDK has no pending action on this. @ro-joowan will coordinate with the customer in https://social.msdn.microsoft.com/Forums/azure/en-US/e77524ad-3401-4714-bd66-63ba80b95e32/data-lake-store-azure-sdk-ruby?forum=AzureDataLake

**Comment by sarangan12** [comment]
Closing this issue as there is no further action on the SDK side
