### ISSUE TITLE
Release by 25th Sept with updated specs

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#938]

**Comment by veronicagg** [comment]
FYI - @mayurid this is to accommodate your request on the new feature coming out.

**Comment by veronicagg** [comment]
Because of https://github.com/Azure/azure-sdk-for-ruby/issues/944, TrafficManager may need to be skipped, or released with a previous version of the spec. If we fix the issue, we should be good.

**Comment by sarangan12** [comment]
Related to PR: https://github.com/Azure/autorest.ruby/pull/7

**Comment by vishrutshah** [comment]
- [ ] https://github.com/Azure/azure-sdk-for-ruby/issues/938 : New Gem ACR

**Comment by vishrutshah** [comment]
- [ ] Generate all the gems, that has not been generated so far for ruby and have .NET SDK + Tests

**Comment by veronicagg** [comment]
We did not generate new gems, we'll do another release with all.
