### ISSUE TITLE
ClientModelExtensions condition - Sequence must have primary type of string

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-sdk-for-ruby#944]
This issue is related to Issue https://github.com/Azure/azure-rest-api-specs/pull/1580. In the ruby generator code, Look at the lines https://github.com/Azure/autorest.ruby/blob/master/src/vanilla/ClientModelExtensions.cs#L201. 

This condition is the reason for failure. The condition itself does not make perfect sense. Also, at this point, I do not know the reason for this condition added originally. This needs further analysis.

**Comment by veronicagg** [comment]
There's another issue with collection format that may need to be addressed too https://github.com/Azure/autorest/issues/717

**Comment by vishrutshah** [comment]
@sarangan12 Seems like you are already sent a PR regarding this https://github.com/Azure/autorest.ruby/pull/7/files so assigning this to you to keep track. Thanks!

**Comment by sarangan12** [comment]
The issue has been fixed. Closing it now
