### ISSUE TITLE
Not able to add tags when creating availability set

### ISSUE THREAD

**Issue by rameshjanjyam** [Azure/azure-sdk-for-ruby#951]
http://www.rubydoc.info/gems/azure_mgmt_compute/0.1.1/Azure/ARM/Compute/Models/AvailabilitySetProperties - we have policies set on our azure subscription to have some mandatory tags on the resources. 
we currently use `ComputeManagementClient` to create availability set like below 
```
rgname = "resource_group_name"
asname = "availability_set_name"

avail_set_props = Azure::ARM::Compute::Models::AvailabilitySetProperties.new
avail_set_props.platform_fault_domain_count = fault_domain_count
avail_set_props.platform_update_domain_count = update_domain_count
avail_set_props.virtual_machines = []
avail_set_props.statuses = []

avail_set = Azure::ARM::Compute::Models::AvailabilitySet.new
avail_set.location = @location
avail_set.properties = avail_set_props

client = Azure::ARM::Compute::ComputeManagementClient.new(creds)
client.subscription_id = subid
client.availability_sets.create_or_update(rgname,
                                          asname,
                                          avail_set).value!

```

seems there is no way for me to add tags to availability set properties - http://www.rubydoc.info/gems/azure_mgmt_compute/0.1.1/Azure/ARM/Compute/Models/AvailabilitySetProperties. 

is there anyway that tags can be added to availability set during creation time

**Comment by vishrutshah** [comment]
Hi @rameshjanjyam If i understand correctly you'd like to create tags while creating availability set. 

Did you try out setting `[tags](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/availability_set.rb#L86)` property on model `[AvailabilitySet](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/availability_set.rb)`? `tags` property is inherited from Model [MsRestAzure::Resource](https://github.com/Azure/azure-sdk-for-ruby/blob/master/runtime/ms_rest_azure/lib/ms_rest_azure/resource.rb#L22)

Please try following and let us know:

```ruby
avail_set = Azure::ARM::Compute::Models::AvailabilitySet.new
avail_set.location = @location
avail_set.tags = Hash.new
avail_set.tags['TagKey1'] = 'TagValue1'
avail_set.tags['TagKey2'] = 'TagValue2'
```

Thanks for reaching out to us!

**Comment by vishrutshah** [comment]
Feel free to let us know and reopen the issue if you still have trouble. Thanks!
