### ISSUE TITLE
Delete associated resources?

### ISSUE THREAD

**Issue by djberg96** [Azure/azure-sdk-for-ruby#955]
Is there any facility for automatically deleting associated resources when you delete an object? So, if I delete a VM, is there a way to automatically delete any associated nics, ips, storage, etc?

I understand that in practice users should put all associated resources in the same resource group and just delete that resource group, but sometimes that doesn't happen out in the wild.

In azure-armrest, for example, we added a `delete_associated` method for the virtual machine service class. This lets you pick and choose which associated resources that you want to delete:

    vms.delete_associated(vm_name, vm_group, :network_interfaces => true, :ip_addresses => true)

If that doesn't exist, is there any way something like that could be added?

**Comment by veronicagg** [comment]
@kirthik is there anything like this that could be coming from azure APIs? (so ruby and others could pick up?) Thanks!

**Comment by kirthik** [comment]
@ravbhatnagar to answer

**Comment by veronicagg** [comment]
ping @ravbhatnagar

**Comment by djberg96** [comment]
@veronicagg I've never seen anything on the Azure side. Their recommendation is to put related resources into the same resource group. To delete everything, just delete the resource group.

I suspect that isn't always going to be practical, though.

**Comment by veronicagg** [comment]
@djberg96 I understand, it's a good suggestion, we have not planned adding this feature soon, but will keep it in the backlog and update the issue if anything changes. If you'd like to contribute, feel free to open a PR - the change may require changes to the SDK generator https://github.com/Azure/autorest.ruby

**Comment by djberg96** [comment]
Doesn't seem to be much interest, and I'm not really working on this much any more, so closing.
