### ISSUE TITLE
[azure_mgmt_*] auto-generate better changelog for the SDKs 

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#969]
Requirements:

- [ ] Detect & note breaking changes
- [ ] Details on added methods / updated methods
- [ ] Auto generate the log from the swagger-to-sdk PRs
- [ ] Gem level changelog file instead of the top level changelog
- [ ] Each change-log should mention the api-version inside the gem

cc: @veronicagg

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
