### ISSUE TITLE
[Release] Azure Stack related releases

### ISSUE THREAD

**Issue by vishrutshah** [Azure/azure-sdk-for-ruby#976]
- [x] Release Autorest.Ruby azure-arm generator for azure stack
- [ ] Release azure_mgmt_* gems with all the api-version included
- [ ] Release Profiles gem
   - [ ] Stack profile
   - [ ] Latest profile
- [x] Find the version of the gems to release 
- [x] Make sure to update changelog for with the SHA of the public swagger repo from where we generated things for tracking purpose

**Comment by veronicagg** [comment]
- I've generated all the gems in PR https://github.com/Azure/azure-sdk-for-ruby/pull/925 waiting for confirmation on which ones to ship or not. 
- [] Need https://github.com/Azure/azure-sdk-for-ruby/issues/905 for each gem

**Comment by veronicagg** [comment]
- [ ] Need to update release jobs
- [ ] Need to know if we'll have swagger_to_sdk working https://github.com/Azure/azure-sdk-for-ruby/issues/904
- [ ] Updates to readmes and docs
