### ISSUE TITLE
Unified authentication support across language SDKs

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#985]
@mcardosos can you give us some context/details on this based on what you're planning to do for Golang? thanks!

**Comment by mcardosos** [comment]
Following python example here
https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python#mgmt-auth-file

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
