### ISSUE TITLE
Review Long-running operations design

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#986]
Search for email conversation with other language SDK owners about this topic, and add details

**Comment by vishrutshah** [comment]
Please add more information from the email regarding what is the design and then clear out assignment.

**Comment by sarangan12** [comment]
With the recent changes and discussions with @shahabhijeet The LRO operations logic have been modified and now consistent with all other language SDKs. 

Link to LRO Logic: https://github.com/Azure/adx-documentation-pr/blob/master/sdks/LRO/LRO_AzureSDK.md

@salameer @veronicagg FYI...
